### ISSUE TITLE
Key and Secret exposed for johns apparel

### ISSUE THREAD

**Issue by myjanky** [MONEI/Shopify-api-node#107]
tests contain johns-apparel api key and secret. 

maybe should obfuscate.

**Comment by lpinca** [comment]
The api key and secret are fake. I used the "johns-apparel" name because I found it in the docs.

**Comment by lpinca** [comment]
If I remember correctly those were the "secrets" of an app I used for testing on another shop.
That app no longer exists so everything should be fine.

**Comment by lpinca** [comment]
If you are wondering why tests work, that's because of [nock](https://github.com/node-nock/nock). The real endpoint is not hit.

**Comment by myjanky** [comment]
@lpinca 
Good to know. Just wanted to make your team aware in case of an oversight. 
I believe this to be a non-issue 
thanks,
