### ISSUE TITLE
customCollections not working

### ISSUE THREAD

**Issue by TheGame2500** [MONEI/Shopify-api-node#109]
When I try to do
```
shopifyAPI.customCollection.get({ product_id : product_id })
```
it throws 
```
TypeError: Request path contains unescaped characters.
```

I've also tried 
```
shopifyAPI.customCollection.get({ id : collection_id}) 
```
as a sort of workaround, but for that it says 404 not found and shows host as undefined , even though the path looks ok.

```
[HTTPError: Response code 404 (Not Found)]
  message: 'Response code 404 (Not Found)',
  host: undefined,
  hostname: 'micro-clone.myshopify.com',
  method: 'GET',
  path: '/admin/custom_collections/358753670.json',
  statusCode: 404,
  statusMessage: 'Not Found' }
```

**Comment by lpinca** [comment]
The method signature is:
```
shopify.customCollection.get(id[, params])
```

you should pass only the id if you don't want to specify what fields should be included in the response.

```js
shopify.customCollection.get(358753670)
```

should work.

**Comment by TheGame2500** [comment]
@lpinca same not found error

**Comment by lpinca** [comment]
That's weird, unfortunately I don't have a shop to check where the error is atm.
Can you log the `url` argument here https://github.com/MONEI/Shopify-api-node/blob/a710aaa5852f3a5f41fa84cba4edb8800b9b9873/index.js#L81 and see if it is correct?

If so, try to make the same request with curl or postman and see if you still get a 404 error.

Stupid question: does the collection you are requesting exist?

**Comment by TheGame2500** [comment]
@lpinca the collection does exist, just checked manually. The url argument is an object in the format : 
```
{ path: '/admin/custom_collections/12498982.json?limit=1',
  auth: false,
  hostname: 'blabla.myshopify.com',
  protocol: 'https:' }
```

Should I manually build it?

**Comment by lpinca** [comment]
@TheGame2500 yes.

Try

```
curl -i -H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "X-Shopify-Access-Token: <your_token_here>" \
https://blabla.myshopify.com//admin/custom_collections/12498982.json?limit=1
```

**Comment by TheGame2500** [comment]
@lpinca turns out it still says not found. Hold on, maybe it's a mistunderstanding on my part.

**Comment by TheGame2500** [comment]
@lpinca so it seems like their API has suffered an undocumented change.It work with 
```
/admin/collections/1298479879.json
```
 instead of 
```
/admin/custom_collections/1298479879.json
```

And that's why programmers die young.

**Comment by TheGame2500** [comment]
@lpinca when I do a call to /admin/custom_collections.json it returns an empty array. Perhaps the fault's with me after all

**Comment by lpinca** [comment]
Hmm still weird, there isn't a `Collection` resource so I'm sure why `/admin/collections/` works.

**Comment by lpinca** [comment]
It looks like that is a [private](https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/get-both-custom-smart-collections-in-a-single-api-call-201612) API.

Given that you get an empty array from `/admin/custom_collections.json` (this explains why you get a 404 when using a specific id) I guess that your `1298479879` collection is smart collection?

What you get if query the start collections? Is the array still empty?

**Comment by TheGame2500** [comment]
My fault after all. There was no customCollection, it was a smartCollection
but I was unfamilliar with their data format.

2016-12-14 18:56 GMT+02:00 Luigi Pinca <notifications@github.com>:

**Comment by lpinca** [comment]
No problem. Closing this, please comment or reopen if needed.
