### ISSUE TITLE
Cannot Get Product Metafields

### ISSUE THREAD

**Issue by mcmurter** [MONEI/Shopify-api-node#110]
`shopify.metafield.list()` only returns shop metafields. I would like to get product metafields. Is this possible? Am I missing some crucial piece of information?

**Comment by alexandresaiz** [comment]
Did you take a look at product metafields or variants metafields?


-- 
Alexandre Saiz
a@alexandresaiz.com 
Phone: +34 (659) 07 85 44  |    alexandre.saiz 


El 13 des 2016, a les 23:27, Aaron McMurter <notifications@github.com> va escriure:

**Comment by lpinca** [comment]
@mcmurter 

```js
const promise = shopify.metafield.list({
  metafield: { owner_resource: 'product', owner_id: 632910392 }
});
```

**Comment by mcmurter** [comment]
@lpinca Thank you, this is what I was looking for. Oversight on my part. It is a shame that it takes one api call per product, but that is just Shopify's dodgy api.
