### ISSUE TITLE
Make the `autoLimit` feature work

### ISSUE THREAD

**Issue by etherealite** [MONEI/Shopify-api-node#111]
I used the following constructor call,
```javascript
const shopify = new Shopify({
  shopName: 'dizzy-lizzie',
  apiKey: '4e8f95a3d04b272de92cdd060932e180',
  password: 'ff5ded17c15177277308c0454a9a6bc3',
  autoLimit: { calls: 2, interval: 3000 },
});
```

with the following call to the API
```javascript
        invalids.forEach(invalid => {

            shopify.productVariant.update(invalid.id, { weight: 1 });
        });
```

The outgoing http request sent are going out as fast as the node loops will allow, with no respect in regards to the configured limits.

I've also try to use ` autoLimit: true,` which similarly had no effect on the rate at which requests were sent.

**Comment by lpinca** [comment]
Hi,
there is a [test](https://github.com/MONEI/Shopify-api-node/blob/f0fccb012e37566d83ade97bf9c2a4302a0d34ab/test/shopify.test.js#L311-L342) for the `autoLimit` option, so it should work.

Stupid question: are you using version 2.3.0?

**Comment by etherealite** [comment]
Hmm, did I goof on this one? I'm using 2.20.

**Comment by lpinca** [comment]
Closing, please comment or reopen if needed.
