### ISSUE TITLE
Product Metafields

### ISSUE THREAD

**Issue by daslicht** [MONEI/Shopify-api-node#112]
Hi,
How to get metafields of a product,  please?

The Shopify api says:
```
GET /admin/products/#{id}/metafields/#{id}.json

or:

GET /admin/products/632910392/metafields.json
```
Cheers 
Marc

**Comment by lpinca** [comment]
Hi,
try this.

```js
const promise = shopify.metafield.list({
  metafield: { owner_resource: 'product', owner_id: 632910392 }
});
```

**Comment by daslicht** [comment]
That seams to return the product

**Comment by lpinca** [comment]
It used to work, see #110, #105.

**Comment by daslicht** [comment]
ok

**Comment by lpinca** [comment]
@daslicht just tested it and I can confirm that it still works.

**Comment by daslicht** [comment]
Seams to work here now as well ! thanks
I assume that creating metafiles supposed to work with the same pattern?

```
const promise = shopify.metafield.create({
  metafield: { owner_resource: 'product', owner_id: 632910392 }
});
```

Like this ?

**Comment by lpinca** [comment]
That's correct. If you don't need to get the created metafield back you can also use `shopify.product.update()`.

**Comment by daslicht** [comment]
does update also work if there is no metafielcd set yet ?

**Comment by lpinca** [comment]
Yes, it should create a new one.

**Comment by daslicht** [comment]
and since metafields is an array It should be possible to create multiple meta fields with one call ?

**Comment by daslicht** [comment]
I try

**Comment by lpinca** [comment]
yes, that should work.

**Comment by daslicht** [comment]
is that function async or sync ?
```const shopify = new Shopify(``` please?

**Comment by lpinca** [comment]
The constructor is sync.

**Comment by daslicht** [comment]
thanks !

**Comment by UlisesCandela1** [comment]
> That's correct. If you don't need to get the created metafield back you can also use `shopify.product.update()` like this:
> 
> ```js
> const promise = shopify.product.update(632910392, {
>   id: 632910392,
>   metafields: [
>     {
>       key: 'new',
>       value: 'newvalue',
>       value_type: 'string',
>       namespace: 'global'
>     }
>   ]
> });
> ```

this is giving me a 422 response, could you help me to figure out what's going on?

**Comment by dheerajppl** [comment]
i have created multiple metafields for single product 

function abc(productId, key, value) {
    shopify.metafield.create({
        key: key,
        value: value,
        type: ["date", "date", "decimal_number"],
        namespace: 'custom',
        owner_resource: 'product',
        owner_id: productId
    })
        .then(
            (metafield) => console.log(metafield),
            (err) => console.error(err)
        );
}
abc("8486664470837", "end_date", "2023-05-17");

abc("8486664470837", "start_date", "2023-05-19");

abc("8486664470837", "price", "1000");

**Comment by dheerajppl** [comment]
code for multiple metafields for single products
function abc(productId, key, value) {
    shopify.metafield.create({
        key: key,
        value: value,
        type: ["date", "date", "decimal_number"],
        namespace: 'custom',
        owner_resource: 'product',
        owner_id: productId
    })
        .then(
            (metafield) => console.log(metafield),
            (err) => console.error(err)
        );
}
abc("8486664470837", "end_date", "2023-05-17");

abc("8486664470837", "start_date", "2023-05-19");

abc("8486664470837", "price", "1000");
