### ISSUE TITLE
Format of params for webhook.create

### ISSUE THREAD

**Issue by gregorwilson** [MONEI/Shopify-api-node#118]
I'm a little confused what the format for `params` should be in this context, since the method already has `create`, and normally the `topic` would be something like `"customers\/create"`. Can someone clarify? My app can create webhooks fine (using another package), but using this package I just keep getting a 422 when trying to create.

**Comment by lpinca** [comment]
When in doubts take a looks at the tests :)

https://github.com/MONEI/Shopify-api-node/blob/711fe192f88c103c93e41dc1142b9027c6e558c6/test/webhook.test.js#L87-L88

`input.webhook` in that test is

```js
{
  topic: 'orders/create',
  address: 'http://whatever.hostname.com/',
  format: 'json'
}
```

**Comment by gregorwilson** [comment]
got it, thank you!
