### ISSUE TITLE
session.product.count usage

### ISSUE THREAD

**Issue by ganeshkbhat** [MONEI/Shopify-api-node#119]
I am trying to use the function 
`session.product.count([{published_status: 'any'}], orders => console.log(orders))` and it always returns null. I have tried `session.product.count({published_status: 'any'}, orders => console.log(orders))` as well. What am I doing wrong. Seems like I am stuck with the usage here. I have both read and write scopes.

**Comment by lpinca** [comment]
It looks like you are not using `Promise` correctly.

```js
session.product.count({ published_status: 'any' })
  .then(orders => console.log(orders));
```

This should work.

**Comment by ganeshkbhat** [comment]
Ok this was nasty. I was able to use a callback. but I was unable to use a promise like this:

```
session.product.count({ published_status: 'any' })
  .then(count => console.log(count))
  .err(err => console.log(err));
```

or like this: 

```
session.product.count({ published_status: 'any' })
  .then(count => console.log(count));
```

What worked was this:

```
session.product.count({ published_status: 'any' }, function(err, count){
console.log(err, count);
});
```

I now am creating a promise myself. But, did I miss something or was this how it was supposed to work?

**Comment by lpinca** [comment]
Are you use that you are using `shopify-api-node@2.4.0`? This package uses promises since version 1.0.0 and passing a callback should not work. The callback shouldn't be called.

If you run this command from the root of your project what do you get?

```
npm ls shopify-api-node
```

**Comment by ganeshkbhat** [comment]
Sorry for the delayed response. I am not using shopify-api-node@2.4.0 . Let me try upgrading and see if it works. I am using nodify-shopify which point to your github dist.

**Comment by lpinca** [comment]
Yeah I thought so, please upgrade and use shopify-api-node if you can.

**Comment by lpinca** [comment]
Closing this, discussion can continue if needed.
