### ISSUE TITLE
New Price Rules API (deprecating Discounts API)

### ISSUE THREAD

**Issue by ktrain** [MONEI/Shopify-api-node#121]
Hello!

There is a new Price Rules API (https://help.shopify.com/api/price-rules), and the Discounts API is being deprecated on April 20, 2017. Is there a plan to update the package with the new Price Rule and Discount Code resources?

**Comment by alexandresaiz** [comment]
Hey! @ktrain 

We will wait until we see this new API stable. 

Best!
