### ISSUE TITLE
Products of collection

### ISSUE THREAD

**Issue by CrackerakiUA** [MONEI/Shopify-api-node#123]
With with option i can force collections to load with products?

**Comment by lpinca** [comment]
There is no built-in way, you have to make multiple requests.

**Comment by CrackerakiUA** [comment]
Which route, sorry for asking, i can't see connection between product and collection.

**Comment by lpinca** [comment]
Take a look here https://help.shopify.com/api/reference/collect#index

**Comment by lpinca** [comment]
Closing, feel free to continue discussing on the closed thread.
