### ISSUE TITLE
TypeError: shopify.on is not a function

### ISSUE THREAD

**Issue by Bek81** [MONEI/Shopify-api-node#124]
How can i use
`shopify.on('callLimits', limits => console.log(limits));`
?

Can be integrate in the code:
`shopify.product.list({ limit: data.n })
        .then(
            products => callback(null,products)
        )
        .catch(
            err => callback(err)
        );`

?

Tnx!

B.

**Comment by lpinca** [comment]
Are you using the latest version (2.5.0)?
From the root of your project type:

```
npm ls shopify-api-node
```

to verify.

**Comment by Bek81** [comment]
shopify-api-node@2.4.0
ok...I updated that. Now:
shopify-api-node@2.5.0
Tnx a lot.

Anyway, Can you tell me the right usage, please?
B.

**Comment by lpinca** [comment]
What you mean?
The `callLimits` event allows you to monitor how many calls you've already made.
If you want to regulate the request rate in order to not hit the rate limit use the [`autoLimit`](https://github.com/MONEI/Shopify-api-node#options) option.

**Comment by Bek81** [comment]
I'm really sorry...

I just want to verify the remaining calls after a call (or at other times).
Is not used for that?

**Comment by lpinca** [comment]
The event is emitted after every request so you can use it to check the remaining calls but it doesn't stop new requests if you are out of slots.

**Comment by Bek81** [comment]
Ok, tnx a lot.
You can close the issue.
