### ISSUE TITLE
shopify. metafield.get() not working

### ISSUE THREAD

**Issue by shahbits22** [MONEI/Shopify-api-node#126]
```
shopify.metafield.get()
                        .then(function(metaFieldArray){
                           // metaFieldArray is undefined
                        }).catch(function(err){
                            //
                        });
```
I am trying to retrieve all the meta fields attached to the shop [(GET /admin/metafields.json)](https://help.shopify.com/api/reference/metafield#index). Promise returns a success but metaFieldArray is undefined and [count()](https://help.shopify.com/api/reference/metafield#count) returns 1. I assume that if I don't pass any params in GET call, it should return all the metafields

**Comment by lpinca** [comment]
`shopify.metafield.get(id)` is to get a single metafield by its id. Use `shopify.metafield.list()` to get all metafields.

**Comment by shahbits22** [comment]
Thanks @lpinca
