### ISSUE TITLE
shopify.webhook.create(data) - getting HTTPError: Response code 422 (Unprocessable Entity)

### ISSUE THREAD

**Issue by shahbits22** [MONEI/Shopify-api-node#127]
```
 var webhookData = {
                "topic": "app\/uninstalled",
                "address": "https:\/\/localhost:8000\/shopify\/uninstall",
                "format": "json"
            };

            shopify.webhook.create(webhookData)
                .then(function(webhook){
                    console.log(webhook);
                }).catch(function(error){
                    console.log(error);
                });
```

Is there anything wrong in the above snippet?

**Comment by lpinca** [comment]
You can write your data like this:

```js
const data = {
  topic: 'app/uninstalled',
  address: 'https://localhost:8000/shopify/uninstall',
  format: 'json'
};
```

Escaping `/` is not needed but I see nothing wrong in your example.
Try to read the response body and see if there are more details. To do that use:

```js
console.log(error.response.body);
```

**Comment by shahbits22** [comment]
localhost keyword is not supported as webhook cannot be received on localhost. It must be a public URL. Closing the issue. Thanks

**Comment by mitchellporter** [comment]
This can also occur when you are trying to create a webhook for a resource that your app does not have permission to access.

**Comment by lomse** [comment]
@mitchellporter it totally makes sense. I've been pulling hair for the past hour lol.
