### ISSUE TITLE
Shop Metafield Cannot Find

### ISSUE THREAD

**Issue by ilrein** [MONEI/Shopify-api-node#132]
```
shopify.shop.get()
      .then(data => res.json({ result: data }))
      .catch(e => res.json({ result: e }))
```

Is a simple way to obtain my shop ID, which I then decided to use the metafield API:

```
shopify.metafield.list({
      metafield: { owner_resource: 'shop', owner_id: req.body.shop.id }
    }).then(
      data => {
        console.log('got data', data);
        res.json({ result: data })
      },
      e => {
        console.log('did not get shop metadata', e);
        res.json({ result: e })
      }
    )
```

I can certainly confirm I have access to the shop ID from the previous API call. However, attempting to use that configuration for the second request results in a 404. Any suggestions?

**Comment by lpinca** [comment]
You should be able to get the store metafields by simply using:

```js
shopify.metafield.list()
```

The `shopify` instance is bound to a shop.

**Comment by ilrein** [comment]
Got it. Thanks!
