### ISSUE TITLE
Verification Utility for webhooks *Feature Request*

### ISSUE THREAD

**Issue by yonib05** [MONEI/Shopify-api-node#133]
Super simple feature request would be cool to have function to verify incoming webhooks are from the correct store and valid.

https://help.shopify.com/api/getting-started/webhooks#verify-webhook

**Comment by lpinca** [comment]
I think this is out of the scope of the module.

The implementation depends on the server/framework that handles the HTTP request. For example with express it would be nice to have a middleware like this:

```js
'use strict';

const crypto = require('crypto');

function verifyWebhook(options = {}) {
  if (typeof options.sharedSecret !== 'string') {
    throw new TypeError('Missing or invalid "sharedSecret" option');
  }

  return function verify(req, res, next) {
    const hmac = crypto.createHmac('sha256', options.sharedSecret);

    req.on('error', next);

    //
    // For the sake of simplicity assume request body is not compressed.
    //
    req.on('data', (data) => hmac.update(data));
    req.on('end', () => {
      const digest = hmac.digest('base64');

      if (digest !== req.headers['x-shopify-hmac-sha256']) {
        return next(new Error('Invalid signature'));
      }

      next();
    });
  };
}

module.exports = verifyWebhook;
```

and use it on the webhooks routes.

**Comment by buggy** [comment]
Would it be worth having a framework independent implementation of `validateWebhook()` that could be used by a framework specific implementation? Basically it's just a function that takes in the body, X-Shopify-Hmac-Sha256 header and secret then returns true/false.

**Comment by lpinca** [comment]
@buggy yes maybe but it's literally 2 lines of code.

```js
function validateWebhook(body, signature, secret) {
  const hmac = crypto.createHmac('sha256', secret);
  return signature === hmac.update(body, secret).digest('base64');
}
```

I don't see a big value in adding this to the library.

**Comment by lpinca** [comment]
Closing for now.
