### ISSUE TITLE
Is there a tutorial or an example project using this?

### ISSUE THREAD

**Issue by AdityaAnand1** [MONEI/Shopify-api-node#137]
I'm new to shopify development and a sample project using this library would be an amazing addition. Or perhaps if you know of any it might be a good idea to link to them in the readme?

It's a bit hard to figure out how to use this from scratch to build a whole app around it, some code samples would be very helpful to get started quickly.

**Comment by lpinca** [comment]
This project: https://github.com/airmiha/create-shopify-app seems to use `shopify-api-node` under the hood.

Closing, feel free to continue discussing on the closed thread.
