### ISSUE TITLE
shopify.transaction.get undefined

### ISSUE THREAD

**Issue by jremi** [MONEI/Shopify-api-node#140]
If you call _shopify.transaction.get()_ passing in the required parameter _order_id_ 

**Result:** undefined

**Filename:** index.js
**Line:** 127   

`if (key) return body[key];
`
This is causing undefined because the Shopify API is returning the response with key set as transaction**s** NOT transaction. It contains the letter "s" at the end.

**Quick Fix:**

```
if (key) {
      if(key === 'transaction'){key = key + 's'}
      return body[key]
};
```

**Comment by lpinca** [comment]
The [`key`](https://github.com/MONEI/Shopify-api-node/blob/48c3f94dbce2f760ca8b1c9ef45381fdfe7145ba/resources/transaction.js#L20) is `'transaction'` and is used by the [`get`](https://github.com/MONEI/Shopify-api-node/blob/48c3f94dbce2f760ca8b1c9ef45381fdfe7145ba/mixins/base-child.js#L65) method as expected.
