### ISSUE TITLE
when you get a 422 on customer creation, the api eats the error explanation from shopify

### ISSUE THREAD

**Issue by glydeb** [MONEI/Shopify-api-node#141]
When a customer fails creation calling shopify.customer.create() and shopify returns a 422, the body of the error does not get returned in the error object.

Returned by the method: `{ HTTPError: Response code 422 (Unprocessable Entity)
    <stack trace>,
  name: 'HTTPError',
  host: undefined,
  hostname: '<store address>',
  method: 'POST',
  path: '/admin/customers.json',
  protocol: 'https:',
  url: undefined,
  statusCode: 422,
  statusMessage: 'Unprocessable Entity',
  headers:
   { <lots of headers> }`

But there's a body that I discovered by making the same request with postman: `{
    "errors": {
        "email": [
            "has already been taken"
        ]
    }
}`

This would be really nice to have returned by the method.

**Comment by lpinca** [comment]
You can get it from the `response` property on the error. Can't remember if it's parsed or not but it should.

**Comment by glydeb** [comment]
You are correct - it is there; I didn't look past what I got from the console log.  Thanks for getting back to me so quickly.

The errors appear, should anyone else run into the issue, as an object at `err.response.body.errors`.   The object's properties are the types of errors encountered, and each property contains an array of error messages for that type of error.

**Comment by lpinca** [comment]
@glydeb feel free to open a PR to document `err.response.body`.
