### ISSUE TITLE
Customer login authentification

### ISSUE THREAD

**Issue by miranos** [MONEI/Shopify-api-node#143]
Hi,

There is a way to create customer with email and password, but is there a method to check authentification login ? Chech if email and password mutch ?

Thank you.

**Comment by lpinca** [comment]
Hi,
the authentication and matching of email/password is handled by Shopify when the customer tries to log in to the shop.

**Comment by miranos** [comment]
It means that is impossible from the API ?

Or do you mean we must do it with AJAX call or similar ?

**Comment by lpinca** [comment]
Yes, as far as I know there is no way to authenticate a customer via the public API.
