### ISSUE TITLE
422 Unprocessable Entity

### ISSUE THREAD

**Issue by jprivillaso** [MONEI/Shopify-api-node#144]
HI, 

I haven been facing this issue for a long time and I have no idea what can be happening. 
When I try to call the API productVariant.create(productId, data) after some requests I start receiving the message: Response code 422 (Unprocessable Entity) 

I am sending this object as shown in [this link](https://help.shopify.com/api/reference/product_variant#create)

`{ option1: 'Total Price 92.00', price: '92.00' }`

The funny fact is that it works sometimes. 

I would appreciate if you can help me with this.

Thank you

**Comment by lpinca** [comment]
I don't know, does the response body include more details? The response is attached to the error:

```js
try {
  await shopify.productVariant.create(productId, data);
} catch (err) {
  console.log(err.response.body);
}
```

**Comment by jprivillaso** [comment]
It worked and I found the cause of the error. Thank you so much!

**Comment by lpinca** [comment]
No problem.

**Comment by lagunasolutions** [comment]
@jprivillaso For some reason i'm having the same issue, would you mind publishing your solution?

Thanks

**Comment by jprivillaso** [comment]
> @jprivillaso For some reason i'm having the same issue, would you mind publishing your solution?
> 
> Thanks

Unfortunately I don't remember exactly what was the problem, but it was related to my app's logic.

**Comment by lagunasolutions** [comment]
@jprivillaso Thats fine, I found out that if we test on a dev store, some requests (in my case was to send a customer account invitation) are limited to 5 in 10 mins. Then, i was getting that error for that matter. No more problem when in production.

Thanks for your time

**Comment by BeyondSpace609520** [comment]
Hi, I have also faced same issue: 
`shopify.productVariant
    .create("6145561297087", {
      title: "CUSTOM / CUSTQTY01",
      price: "24.99",
    })
    .then((data) => console.log(data))
    .catch((err) => console.error(err));`
    
`HTTPError: Response code 422 (Unprocessable Entity)
    at Request.<anonymous> (E:\Work\custom-shopify-server\node_modules\got\dist\source\as-promise\index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,`
