### ISSUE TITLE
RecurringApplicationCharge redirect_url redirects to /undefined

### ISSUE THREAD

**Issue by ilrein** [MONEI/Shopify-api-node#148]
Almost done my app! Running into what I believe is the final problem. Basically, upon creating an application charge, the redirect_url behaves in a wonky fashion.

If manually visit the ```confirmation_url``` (actual response):

```
create charge { id: 7378032,
  name: 'Standard Plan',
  api_client_id: 1878414,
  price: '5.00',
  status: 'pending',
  return_url: 'http://localhost:3000/?charged=true&shop=easy-tiles-easy-life',
  billing_on: null,
  created_at: '2017-11-17T11:08:29-05:00',
  updated_at: '2017-11-17T11:08:29-05:00',
  test: true,
  activated_on: null,
  trial_ends_on: null,
  cancelled_on: null,
  trial_days: 14,
  decorated_return_url: 'http://localhost:3000/?charge_id=7378032&charged=true&shop=easy-tiles-easy-life',
  confirmation_url: 'https://easy-tiles-easy-life.myshopify.com/admin/charges/7378032/confirm_recurring_application_charge?signature=BAhpA3CUcA%3D%3D--985032b92eadb3003193e55f36646d7fd3fd4b3e' }
```

And click approve charge, I am properly redirect to the ```return_url```.

However, if a charge already exists, the user isn't asked to confirm it again -- it just automatically redirects you. When this happens, I am only redirected to ```http://localhost:3000/undefined```.

I built the frontend with create-react-app and React Router v3. Considering that manually visiting the confirmation url and manually selecting "approve charge" properly redirects to the frontend with no issues, I think the issue is hidden during that redirect, which I am struggling to debug.

Any thoughts or suggestions?

**Comment by lpinca** [comment]
¯\_(ツ)_/¯ is the URL ok after activation? I mean is the URL the same if you receive the charge by its id after it has been accepted?

I can't see how it is related to this library though.

**Comment by ilrein** [comment]
This is most definitely an issue with react-router and not this library.
