### ISSUE TITLE
An interface would be amazing

### ISSUE THREAD

**Issue by stephengardner** [MONEI/Shopify-api-node#149]
The documentation around this API was actually confusingly difficult to identify.  I couldn't tell what a Shopify Admin App exactly was.  There's public, private apps.  All sorts of stuff.  Anyways, I digress.

Going here https://help.shopify.com/api/reference and then clicking on an endpoint and then clicking again to find the return value of the method in question and then coming back here to see the correlating function to use on this module is a bit of a relative hassle in the age of excellent developer docs.  If this module had a Typescript interface that would make my day.

Thanks for the module.

**Comment by lpinca** [comment]
Any kind of help is appreciated. I don't use TypeScript so I can't write/maintain definitions. You could write and submit them to https://github.com/DefinitelyTyped/DefinitelyTyped if you want. Code is documented with JSDoc so it shouldn't be very hard.

**Comment by buggy** [comment]
I have partial TypeScript definitions file that I'm happy to contribute and help maintain. It's a start but it's missing a lot of API's. If this is going to be the official Shopify Node SDK then ideally we could include it here rather than DefinitelyTyped. If you're interested I can put together a PR.

**Comment by lpinca** [comment]
@buggy I'm fine with it, I just don't to want to have a broken/outdated definitions file.

I don't think this is the "official" library as it is still listed under "third-party" in their documentation https://help.shopify.com/api/supported-libraries. @alexandresaiz should have more info on this.

**Comment by stephengardner** [comment]
Yesterday I started a very basic amalgamation of some type rules and published it.  I'll drop the updated link here shortly.

The repo README says "Official module", so I wasn't sure if it was just semantics lol.  Cool, thanks

**Comment by stephengardner** [comment]
I've given the top level module a declaration, plugged every action with at least an "any" type and begun working on a few actions like `product`.
https://github.com/stephengardner/shopify-api-node-interface

**Comment by buggy** [comment]
I want to provide a quick update so everyone knows progress is being made. Late last week I scraped the API docs from the Shopify website to generate interfaces for the API objects. Unfortunately the API docs rarely seem to match the actual API and that is slowing down definition creation.

Given the problems with the API docs the only way we'll know for sure if the definitions are correct is when people start using them.

I'm only able to work on this in my spare time so it will probably take another 2-3 weeks to create all of the definitions. My goal is to have the first PR ready by the end of this week then a new PR each week as more definitions are added.

**Comment by buggy** [comment]
UPDATE: I have a `.d.ts` file at https://github.com/buggy/Shopify-api-node that's almost 1,800 lines long. It covers the `Shopify` object and defines interfaces for most of the objects returned by the Shopify API.

My next step is to create the definitions for the parameters for the create and update functions. This should be a lot faster as they're typically cut down versions of the interface used for the API response. My goal is to have them done before the new year.

That will leave interfaces for the parameters for get, list and any unique functions to be done sometime next year.

We need to talk about the right time to merge the definitions. Currently I think the best time would be after the create/update interfaces are added and before the get/list interfaces are added. The definitions are currently usable but by that point I think they'll provide some real value. I'd love feedback on this, especially if you think we should merge sooner or wait.

**Comment by lpinca** [comment]
> We need to talk about the right time to merge the definitions. Currently I think the best time would be after the create/update interfaces are added and before the get/list interfaces are added. The definitions are currently usable but by that point I think they'll provide some real value. I'd love feedback on this, especially if you think we should merge sooner or wait.

Whenever you think they'll provide some value.

**Comment by alexandresaiz** [comment]
@lpinca it is the official module as per what we've agreed with Shopify.

**Comment by lpinca** [comment]
Fixed by https://github.com/MONEI/Shopify-api-node/pull/155.

**Comment by khansahib1234** [comment]
hy can any tell me how to create customer account in my shopify store using ionic 2 framework
