### ISSUE TITLE
Slight inconsistency with the shopify.product.count() endpoint.

### ISSUE THREAD

**Issue by stephengardner** [MONEI/Shopify-api-node#151]
`shopify.product.count()` of this module returns a response of type `number` while the [API spec for count](https://help.shopify.com/api/reference/product#count) shows it returning a type Object with form: 
```
{
  count: number
}
```

Ex: `181` instead of `{ count: 181 }` which, while relatively benign, is still going against the API spec.

Unless the API spec is wrong, and this module is returning what has been passed to it without modification.  Poking around the `/mixins/base` file I didn't notice any immediate response manipulation going on.

**Comment by lpinca** [comment]
Yes, all endpoints in the lib works like this. The request body is automatically wrapped and the response body is automatically unwrapped.

The reason is historical and predates me. When I rewrote the lib this was the actual behavior and I didn't change it.

**Comment by stephengardner** [comment]
Ah I see - subtly happens right there on line `112`.
Hmm... It does pose an issue from a strict API spec standpoint if this is to end up being the official module one day.  It is getting a lot of downloads per week so it might be fair to note this in the readme.  

I'd suggest allowing a configuration parameter of something like `nounwrap: true` to let people specify when they'd like these values to conform exactly to the main shopify API spec and have that line be altered.  But it seems no one else has made a fuss about it...

**Comment by lpinca** [comment]
It is still possible to use/retrieve the full request/response body by using `Shopify.prototype.request()`.
I don't like to have an option for this, I prefer to cut a new major version if needed.

**Comment by lpinca** [comment]
FWIW the same manipulation seems to be done in their official [ruby](https://github.com/Shopify/shopify_api) and [python](https://github.com/Shopify/shopify_python_api) libraries.

I guess this is why it was implemented like this.

**Comment by stephengardner** [comment]
I see I see.  In that case, I'll close the issue.  Though I can't see an instance where you wouldn't expect any `.count` method (or otherwise) to return a different type than `{ param : value }` instead of `value` when the official spec says so.  Though I could again be wrong because it's interesting no one else has raised the issue.  Thanks a lot for the follow-up
