### ISSUE TITLE
Trying to get certain script tag

### ISSUE THREAD

**Issue by ycruzb** [MONEI/Shopify-api-node#152]
Hi all. I'm trying to get certain script tag by its url but honestly I can't do that it works.

I'm getting the script tag in order to check if it exists and then not create it again and again.

Here is the code:

```
const ShopifyQuerier = new ShopifyAPI({
    shopName: shop,
    accessToken: token
});

ShopifyQuerier.scriptTag.get({src: 'https:\/\/thepath.com\/assets\/js\/app.js'})
.then(script_tags => {
    // do something with the script tag
})
.catch((err) => console.log('error bla bla bla'));
```

I hope you can help me.
Regards.

**Comment by lpinca** [comment]
Hi, use `ScriptTag#list()` not `ScriptTag#get()`, `ScriptTag#get()` is to get a single script tag by its ID.

```js
const scriptTags = await shopify.scriptTag.list({ src: url });
```

**Comment by ycruzb** [comment]
Hi Luigi, I'll try your suggestion and I'll let you know.

Thanks for your answer!

**Comment by ycruzb** [comment]
It works Luigi. Thanks for your help !!
