### ISSUE TITLE
Problems with customer search

### ISSUE THREAD

**Issue by zenweasel** [MONEI/Shopify-api-node#156]
When I do (where `email` is a valid customer email, and `shopify` is a credentialed instance )

```
  const query = { email: email };
  const customerByEmailPromise = shopify.customer.search({ query });
```
the query always returns no results. The `url` created by the library is
```
'/admin/customers/search.json?query%5Bemail%5D=brent%40reactioncommerce.com
```

However when I modify the URL and change the URL-escaped characters to
```
/admin/customers/search.json?query=email:brent@reactioncommerce.com
```
The calls returns the correct value (one exact match). This seems like perhaps a bug where it's not correctly handling the parameters passed into "query" and they need to not be URL-escaped? Or maybe a bug in how the Shopify API server is dealing with these string?

If I can figure out how to get it working correctly I will submit a PR. Much thanks for any help.

**Comment by lpinca** [comment]
@zenweasel the parameter object seems incorrect. you are using something like this:

```js
{ query: { email: 'foo@bar.com' } }
```

try with

```js
{ query: 'email:foo@bar.com' }
```

**Comment by zenweasel** [comment]
Yep, that was the problem. Thanks! 👍

**Comment by dennisajacobs** [comment]
> @zenweasel the parameters object seems incorrect. You are using something like this:
> 
> ```js
> { query: { email: 'foo@bar.com' } }
> ```
> 
> try with
> 
> ```js
> { query: 'email:foo@bar.com' }
> ```

Bumped into this exact issue with 2.25.1- the fun part is with Shopify's fuzzy search it generally works, until it doesn't. Perhaps an example in the documentation would help :)
