### ISSUE TITLE
Remove JSDoc annotations from source

### ISSUE THREAD

**Issue by dhritzkiv** [MONEI/Shopify-api-node#158]
Now that there are Typescript definitions, would it be a good idea to remove the JSDoc declarations, to avoid duplication of definitions, and to improve correctness (the JSDoc ones are a bit limited - See #150)

**Comment by lpinca** [comment]
There are people, like me, who don't use TypeScript and find those annotations useful. I don't see any harm in keeping them so I'm 👎 on this.

**Comment by dhritzkiv** [comment]
That's fair
