### ISSUE TITLE
Webhook validation

### ISSUE THREAD

**Issue by ycruzb** [MONEI/Shopify-api-node#159]
Hi all. Does this module provides a mechanism for webhook validation ?

**Comment by ycruzb** [comment]
Hi @lpinca, I'm using ExpressJS.

**Comment by lpinca** [comment]
@ycruzb you can write a middleware like [this](https://github.com/MONEI/Shopify-api-node/issues/133#issuecomment-317722399) and use it in your webhook handlers.

**Comment by ycruzb** [comment]
Thanks @lpinca. I'll use it and I'll let you know.

**Comment by ycruzb** [comment]
Hi again @lpinca. How can I get the reqBody and hmacHeader params ? I have been proving the method but I only get errors.

**Comment by lpinca** [comment]
See https://github.com/MONEI/Shopify-api-node/issues/133#issuecomment-317722399. `reqBody` is the request body and `hmacHeader` the `x-shopify-hmac-sha256` header field value.

**Comment by ycruzb** [comment]
Thanks again @lpinca. I have tested this middleware in my project and I always receive a Request timeout response from the server. What do you think about it ?

**Comment by lpinca** [comment]
I don't know, I'm sorry but I can't debug this for you.

**Comment by ycruzb** [comment]
ok, I can understand ;) I'll trying to resolve this problem. I also want to thank you because this shopify api module works great. I'll close the issue because it is not related to the module itself.

Regards

**Comment by lpinca** [comment]
Thank you.
