### ISSUE TITLE
[typings] Add `.on` definition

### ISSUE THREAD

**Issue by dhritzkiv** [MONEI/Shopify-api-node#161]
Used in documentation:

```js
shopify.on('callLimits', limits => console.log(limits));
```

but not defined in typings

**Comment by lpinca** [comment]
Yes definitions are not complete yet. Any help is greatly appreciated especially on TypeScript side.

**Comment by buggy** [comment]
@dhritzkiv There's a PR ready to go (#162 ). I need @lpinca to merge is as I can't merge PR.
