### ISSUE TITLE
error doesnt include req.body

### ISSUE THREAD

**Issue by Freundschaft** [MONEI/Shopify-api-node#165]
since shopify stores most of its error details in the error body it would be nice to have those informations also attached to the error object
e.g. 
`{"errors":{"variant_id":"expected String to be a id"}}`

**Comment by lpinca** [comment]
Use

```js
err.response.body
```

**Comment by Freundschaft** [comment]
many thanks

**Comment by Freundschaft** [comment]
Have to repopen this, my issue is that when I log this error with Sentry Raven (https://sentry.io) then the body doesnt get serialized when its converted to json, can we change this behavior so the body is attached to the errro object as JSON?

**Comment by lpinca** [comment]
The feature is implemented by https://github.com/sindresorhus/got (the http client library used here). We can re-stringify the body an add it to error object but this is not needed in most cases. You can do this for your particular use case but I'm 👎 on adding to the library

```js
if (err.response && err.response.body) {
  err.errorBodyAsJSON = JSON.stringify(err.response.body);
}
```

**Comment by Freundschaft** [comment]
alright, thanks!, Im already doing it this way but thought it might be useful for others as well
