### ISSUE TITLE
ERROR in ./node_modules/shopify-api-node/index.js

### ISSUE THREAD

**Issue by pbrink231** [MONEI/Shopify-api-node#167]
I am new to this a little so sorry if this is not the right place.  I am using Angular 5.
I did:
`npm install -save shopify-api-node`

When I add it to my project i get the following error:

ERROR in ./node_modules/shopify-api-node/index.js
Module not found: Error: Can't resolve './package' in 'C:\Users\beast\repos\athlos-admin\node_modules\shopify-api-node'
resolve './package' in 'C:\Users\beast\repos\athlos-admin\node_modules\shopify-api-node'
  using description file: C:\Users\beast\repos\athlos-admin\node_modules\shopify-api-node\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Users\beast\repos\athlos-admin\node_modules\shopify-api-node\package.json (relative path: .)
    using description file: C:\Users\beast\repos\athlos-admin\node_modules\shopify-api-node\package.json (relative path: ./package)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\beast\repos\athlos-admin\node_modules\shopify-api-node\package doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\beast\repos\athlos-admin\node_modules\shopify-api-node\package.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\beast\repos\athlos-admin\node_modules\shopify-api-node\package.js doesn't exist
      as directory
        C:\Users\beast\repos\athlos-admin\node_modules\shopify-api-node\package doesn't exist
[C:\Users\beast\repos\athlos-admin\node_modules\shopify-api-node\package]
[C:\Users\beast\repos\athlos-admin\node_modules\shopify-api-node\package.ts]
[C:\Users\beast\repos\athlos-admin\node_modules\shopify-api-node\package.js]
[C:\Users\beast\repos\athlos-admin\node_modules\shopify-api-node\package]
 @ ./node_modules/shopify-api-node/index.js 13:12-32
 @ ./src/app/layout/order/order.component.ts
 @ ./src/app/layout/order/order.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

I have installed a couple other modules but never ran into this so not sure if this is a problem on my end or in the package.  Thank you for the help.

**Comment by lpinca** [comment]
This is a server-side module. There is no 'browser' field which specify how it should be bundled, thus the error.
