### ISSUE TITLE
shopify.customer.orders returns 403 error ?

### ISSUE THREAD

**Issue by IanFergusonZR** [MONEI/Shopify-api-node#169]
apologies if I am missing something obvious but I am attempting to call

                shopify.customer.orders(420919869469).then(function (corders) {
                    console.log(corders);
                }).catch(err => console.error(err));

I have used the other shopify.customer methods which are working correctly for me but I am getting an error : got.HTTPError: Response code 403 (Forbidden)
calling customer.orders for a valid customer id in my store ?

thanks for any assistance

**Comment by lpinca** [comment]
Try to see if there are more details in the response.

```js
err.response.body
```

Are you using an access token? If so check the scopes of the token.

**Comment by IanFergusonZR** [comment]
thank you Luigi - the scopes was the fix - closing
