### ISSUE TITLE
is it possible to support queries like "/admin/variants/search.json?query=sku:101-12"

### ISSUE THREAD

**Issue by IanFergusonZR** [MONEI/Shopify-api-node#172]
reading a post from shopify 
https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/api-product-variant-search-183152

it appears it is possible to search the api like this "/admin/variants/search.json?query=sku:101-12"
which I verified works for me on my own shopify admin instance

I can see why an api-wrapper like shopify-api-node would only want to officially support what is documented by the official shopify api but was wondering if there is any possibility to use/override the classes/api access in shopify-api-node to achieve this result 

could not find an example of anyone doing this but nevertheless was hoping to check if its possible

thanks again for the great work

**Comment by lpinca** [comment]
You can use the internal/private `Shopify#request()` method.

```js
const path = '/admin/variants/search.json?' + querystring.stringify({
  query: 'sku:101-12'
});
const url = Object.assign({ path }, shopify.baseUrl);

shopify.request(url, 'GET', 'variant').then(...);
```

**Comment by lpinca** [comment]
If you need something more elegant you can extend [`ProductVariant`](https://github.com/MONEI/Shopify-api-node/blob/caef37162e67a731a6909000404884c4c8d510fb/resources/product-variant.js) and add a `search()` method and then [instantiate the resource](https://github.com/MONEI/Shopify-api-node/blob/caef37162e67a731a6909000404884c4c8d510fb/test/shopify.test.js#L85-L95).

**Comment by IanFergusonZR** [comment]
thanks Luigi

that helps clarify everything and I will go ahead and close this one

as I keep experimenting with Shopify it sounds like there are still some features that even though they are accessible from in the admin dashboard, are actually restricted in their api layer so ultimately I am still running into this a little - thx again for your help

**Comment by spchuang** [comment]
I'm getting Response code 404 when I do this through the library but the same URL works fine on browser. Anyone gotten similiar issues before?

**Comment by Pankaj-Sakariya** [comment]
Yes, @spchuang  Getting same as you. 
 Need Help, Can anyone guide us?

**Comment by asalce** [comment]
I think the 404 is happening because the URL should really be called using the GraphQL api released this month - April 2019 : https://help.shopify.com/en/api/graphql-admin-api/examples/product#querying-products

**Comment by asalce** [comment]
@Pankaj-Sakariya @spchuang 

I got it to work like this, https://gist.github.com/asalce/6145019ace0a5549b1092b2690ff16b4

**Comment by lacabra-dev** [comment]
This is still a problem. I did what @lpinca suggested but doesn't work on my end. i get a 404  with the eexact same code.
