### ISSUE TITLE
Get layout/theme.liquid returns undefine

### ISSUE THREAD

**Issue by bluedge** [MONEI/Shopify-api-node#174]
This seems not to work. it return nothing. ThemeID is correct.
All other API calls work just fine in the Application

`shopify.asset.get(themeID, {key: 'layout/theme.liquid'})
	.then(resource => {
                console.log(resource) // returns undefine
	.catch(err => { 
		console.log(err); // Not triggered
	});`

**Comment by lpinca** [comment]
The `params` argument seems incorrect, it should be:

```js
shopify.asset.get(themeID, {
  asset: { key:  'layout/theme.liquid' }
})
```

**Comment by lpinca** [comment]
Closing, please reopen if the issue persists.
