### ISSUE TITLE
Implement DELETE /admin/marketing_events/#{marketing_event_id}.json

### ISSUE THREAD

**Issue by chris-klickly** [MONEI/Shopify-api-node#179]
I see we're missing this. Any plans to implement it?

**Comment by lpinca** [comment]
It's already available, see https://github.com/MONEI/Shopify-api-node/blob/31c99628dec72901e37a1cc8daafd15a3b821af9/test/marketing-event.test.js#L82-L89

**Comment by chris-klickly** [comment]
That’s marketing events.

I mean more like marketingEvent.engagements.delete()

**Comment by lpinca** [comment]
It seems there is no documentation for this? https://help.shopify.com/api/reference/marketing_event

**Comment by lpinca** [comment]
Maybe you can do this with:

```js
shopify.marketingEvent.engagements(id, []);
```

but I'm not sure.

**Comment by chris-klickly** [comment]
Oh you’re right. Nevermind thank you!

**Comment by lpinca** [comment]
Closing, let me know if it should stay open instead.
