### ISSUE TITLE
Implement location_id for fulfillments, refunds and restocks

### ISSUE THREAD

**Issue by petetnt** [MONEI/Shopify-api-node#182]
Related to #179, Shopify now requires `location_id` parameter to be set for fulfillment creation, refunds and restocks. 

https://help.shopify.com/api/tutorials/inventory-migration-guide#determining-whether-your-app-will-be-affected-by-multi-location-inventory

> Apps will no longer be able to set inventory_quantity or inventory_quantity_adjustment on the product variant.
> Apps will no longer be able to create fulfillments without specifying a location_id.
> Apps will no longer be able to refund and restock without specifying a location_id.

**Comment by lpinca** [comment]
It seems no API changes are required or am I missing something?

**Comment by petetnt** [comment]
Ah, I guess you are right, the location_id can be passed as params
