### ISSUE TITLE
Feature request: Access the queue length for debugging purposes

### ISSUE THREAD

**Issue by mendeljacks** [MONEI/Shopify-api-node#189]
When making API calls and waiting as a batch is being looped through, it would be helpful to have access to the queue.length property from the main shopify object.

Instead of having to manually increment and decrement or use an external job queue plugin.

**Comment by lpinca** [comment]
This module uses https://github.com/lpinca/stopcock under the hood and `stopcock` does not expose the queue so it's not possible to access the queue length directly. We can keep a counter in the `shopify` object but I'm not very happy with it.

**Comment by lpinca** [comment]
Fixed by https://github.com/lpinca/stopcock/commit/887a55d125fcf51c9729f845f19ae048e454d0c3. It will be available on the next version and will be accessible like this:

```js
console.log(shopify.request.size);
```

**Comment by lpinca** [comment]
It should actually work even now as all dependencies use caret ranges. All is needed is a reinstall.
