### ISSUE TITLE
Need a list of products, even if they're duplicates.

### ISSUE THREAD

**Issue by johnnunns** [MONEI/Shopify-api-node#190]
Without going into too much detail as to why, I was wondering if there's a way for my product list query to return duplicate data. My query looks like this: 

  query{
    shopify(
      method: "list"
      model: "product"
      params: {
        ids: "1234, 1234"
      },
    )
  }

translates to something like:
(GET /admin/products.json?ids=1234,1234)

Currently passing the same ID twice only returns data for single product, but I'd like to return both. This is because the list I'm wanting to show may have multiple products with the same ids, but different variants. Let me know if this needs additional clarification.

**Comment by lpinca** [comment]
I don't think this works as I guess the ids are deduplicated (not by this module). Isn't https://help.shopify.com/api/reference/products/product_variant what you want?

**Comment by johnnunns** [comment]
got it @lpinca thanks
