### ISSUE TITLE
Share one Shopify instance across Express app

### ISSUE THREAD

**Issue by tomblanchard** [MONEI/Shopify-api-node#191]
I'm developing a Shopify app which uses Express and this module for API calls and I've run into trouble sharing one Shopify instance across my routes. Here's a stripped down version of what I'm trying to achieve:

```javascript
var express = require("express");
var Shopify = require("shopify-api-node");
var app = express();

// Declare at highest scope so all routes can reference it
var shopify;

app.get("/", (req, res) => {
  var { shopName, apiKey, password } = req.query;

  // Re-declare to a Shopify instance using data from query string parameter
  shopify = new Shopify({ shopName, apiKey, password });

  shopify.shop.get()
    .then((shop) => {
      return res.send(JSON.stringify(shop));
    })
    .catch(() => {
      return res.status(500).send("Something broke.");
    });
});

app.get("/other-route", (req, res) => {
  shopify.product.list()
    .then((products) => {
      return res.send(JSON.stringify(products));
    })
    .catch(() => {
      return res.status(500).send("Something broke.");
    });
});

app.listen(3000, () => {
  console.log("Example app listening on port 3000!")
});
```

That actually works like how I want it to:

- Visit a URL like: http://localhost:3000/?shopName=your-shop-name&apiKey=your-api-key&password=your-app-password
- API call works
- Visit the URL: http://localhost:3000/other-route
- API calls works

What I'm struggling with is eventually all routes will be in separate files, how could I share that one Shopify instance between all files?

In my actual non-stripped-down app I'm using express-session, I tried storing the Shopify instance in that but that only takes JSON-serializable data so that doesn't work. Is there an Express-best practice I've missed when it comes to storing instances across routes/session? 

Right now I'm creating a new Shopify instance for each route which isn't ideal, it works but eventually I'll run into problems with the API call limit, I'd prefer to use one Shopify instance across all of my routes with `autoLimit: true` and not have to worry about it, any help would be greatly appreciated.

PS: Thanks once again for this module, it's great.

**Comment by lpinca** [comment]
A possible option is to define the route handlers like this:

```js
function otherRouteHandler(shopify) {
  return (req, res) => {
    shopify.product.list()
    .then((products) => {
      return res.send(JSON.stringify(products));
    })
    .catch(() => {
      return res.status(500).send("Something broke.");
    });
  }
}
```

and  then use it as follows:

```js
app.get("/other-route", otherRouteHandler(shopify));
```

If your `Shopify` instance is created at runtime, you probably also need to add the routes handlers at runtime after the `Shopify` instance is created.

**Comment by tomblanchard** [comment]
@lpinca I'll try that out, thanks! Is there any way to store the Shopify instance in an express session though?

**Comment by lpinca** [comment]
I don't follow, you only have to make sure to use the same instance and not reassign it. Using your code:

```js
const express = require('express');
const Shopify = require('shopify-api-node');
const app = express();

let shopify;

app.get('/', (req, res) => {
  const { shopName, apiKey, password } = req.query;

  if (shopify === undefined) {
    shopify = new Shopify({ shopName, apiKey, password });
    app.use(createRouter(shopify));
  }

  shopify.shop.get()
    .then((shop) => {
      return res.send(JSON.stringify(shop));
    })
    .catch(() => {
      return res.status(500).send('Something broke.');
    });
});

app.listen(3000, () => {
  console.log('Example app listening on port 3000!')
});

function createRouter(shopify) {
  const router = express.Router();

  router.get('/other-route', (req, res) => {
    shopify.product.list()
      .then((products) => {
        return res.send(JSON.stringify(products));
      })
      .catch(() => {
        return res.status(500).send('Something broke.');
      });
  });

  return router;
}
```

This is untested but it should work. You can't store the instance in the session as that requires the object to be serialised and deserialised for every request. It's much more efficient to create a new instance every time in this case.

**Comment by tomblanchard** [comment]
@lpinca Ah defining the other routes inside the "/" route is nice, I didn't know that was possible.

However, this method still depends on a higher-scope `shopify` variable, which has it's flaws. The way I need this app to work is every session starts from fresh, for example if I navigate to this URL in a new incognito window:

http://localhost:3000/?shopName=shop-one&apiKey=your-api-key&password=your-app-password

It'll display the info for the `shop-one` shop, now if I close this window and open a new incognito window and navigate to this URL:

http://localhost:3000

It'll still show info from the `shop-one` shop, when it should display an error because the query params weren't properly set. This is happening because when the first URL was visited, the higher-scope `shopify` variable was set.

Do you see the issue?

**Comment by lpinca** [comment]
Yes, but I don't see the problem. Can't you check the session and use/set the `shopify` object accordingly?

If you need multiple `Shopify` objects based on a session value, you can keep a map of them.

**Comment by tomblanchard** [comment]
@lpinca That sounds like a good way around it, I basically need a new `Shopify` instance for every new session.

Is this something you'd be able to provide an example of, or does this fall outside of the `Shopify-api-node` scope?

**Comment by lpinca** [comment]
I think it's out of the scope of this module, sorry.

**Comment by tomblanchard** [comment]
@lpinca Thought so, no worries, thanks for the help Luigi. Do you happen to know of any other open source projects which use the pattern of storing instances inside session maps, I've never seen that and I'd love some inspiration on how to achieve it.

**Comment by tomblanchard** [comment]
@lpinca Figured it out in the end:

```
var express = require("express");
var session = require("express-session")
var Shopify = require("shopify-api-node");

var app = express();

var shopifys = {};

app.use(session({
  secret: "gu2cQL7z2z4pKypm",
  resave: false,
  saveUninitialized: true
}));

app.use((req, res, next) => {
  if( !req.session.shopName || !req.session.apiKey || !req.session.password ) {
    req.session.shopName = req.query.shopName;
    req.session.apiKey = req.query.apiKey;
    req.session.password = req.query.password;
  }

  if( !req.session.shopName || !req.session.apiKey || !req.session.password ) {
    return res.status(500).send("Something broke.");
  }

  var { shopName, apiKey, password }  = req.session;

  if( !shopifys[req.session.id] ) {
    shopifys[req.session.id] = new Shopify({ shopName, apiKey, password });
  }

  return next();
});

app.get("/", (req, res) => {
  var shopify = shopifys[req.session.id];

  shopify.shop.get()
    .then((shop) => {
      return res.send(JSON.stringify(shop));
    })
    .catch((err) => {
      return res.status(500).send("Something broke.");
    });
});

app.get("/other-route", (req, res) => {
  var shopify = shopifys[req.session.id];

  shopify.shop.get()
    .then((shop) => {
      return res.send(JSON.stringify(shop));
    })
    .catch(() => {
      return res.status(500).send("Something broke.");
    });
});

app.listen(3000, () => {
  console.log("Example app listening on port 3000!")
});
```

Thanks again for the help, closing this now.

**Comment by lpinca** [comment]
Yes this is more or less what I was suggesting, the only problem is that it may create a leak if the session is destroyed and the corresponding instance is not removed from the map.

**Comment by tomblanchard** [comment]
@lpinca Yeah I was thinking that, in the real world I wouldn't be relying on the express-session default store `MemoryStore` - probably redis. Do you have any ideas how you'd manage correctly removing the instance from the map when the session has "expired"?

**Comment by lpinca** [comment]
A dirty way would be to periodically compare the ids in the map with the ones in redis `sess:*` and remove the one that no longer exists in redis.

**Comment by tomblanchard** [comment]
FYI: In case anyone is interested in reading about this more in-depth, I blogged about this here:

**Comment by tomblanchard** [comment]
FYI: In case anyone is interested in reading about this more in-depth, I blogged about this here:

https://tomblanchard.co.uk/storing-instances-in-express-sessions/

**Comment by patrickbolle** [comment]
Don't want to drag this back open, but...

Is there a way to use this method, but while having a manual autoLimit object?

Everytime I try to do @tomblanchard 's method with autoLimit: true - it works perfectly fine, but if I try to enter an object into the autoLimit, like { calls: 2, interval: 1000, bucketSize: 35 } for example; it breaks and says that my Shopify API object (this library) is not defined. It's like it has an issue with the object for some reason?

Any ideas?
