### ISSUE TITLE
RecurringCharges.activate returns value wrapped

### ISSUE THREAD

**Issue by arypbatista** [MONEI/Shopify-api-node#196]
When using `RecurringCharges.activate` method the result is wrapped within an object with attribute `recurring_application_charge`. I was expecting to receive the unwrapped charge object.

**Received**
```
{ 
  recurring_application_charge: { 
    id: <id>,
    name: 'Basic Plan',
    api_client_id: <id>,
    price: '1.00',
    status: 'active',
    return_url: <return_url>',
    billing_on: '2018-07-17',
    created_at: '2018-07-10T06:15:27-04:00',
    updated_at: '2018-07-10T06:15:35-04:00',
    test: true,
    activated_on: '2018-07-10',
    trial_ends_on: '2018-07-17',
    cancelled_on: null,
    trial_days: 7,
    decorated_return_url: '<app_url>/activate?charge_id=3164373049'
  }
}
```

**Expected**
```
{ 
    id: <id>,
    name: 'Basic Plan',
    api_client_id: <id>,
    price: '1.00',
    status: 'active',
    return_url: <return_url>',
    billing_on: '2018-07-17',
    created_at: '2018-07-10T06:15:27-04:00',
    updated_at: '2018-07-10T06:15:35-04:00',
    test: true,
    activated_on: '2018-07-10',
    trial_ends_on: '2018-07-17',
    cancelled_on: null,
    trial_days: 7,
    decorated_return_url: '<app_url>/activate?charge_id=3164373049'
}
```

I understand this happens because is not a normal CRUD method, so unwrapping doesn't take place. Would it make sense to modify the Node API implementation to unwrap this value?

**Comment by lpinca** [comment]
Yes it does, I think this was changed as originally the returned value was an empty object (or at least this is what was documented).

Would you mind opening a PR?

**Comment by arypbatista** [comment]
Sure

**Comment by lpinca** [comment]
It's just a matter of adding `.then(body => body[this.key]);` here https://github.com/MONEI/Shopify-api-node/blob/472b0f55cba68a5869f7d4109901eec60623efa8/resources/recurring-application-charge.js#L39 and updating the test.
