### ISSUE TITLE
How could I use an OR operator in the customer search? Search for customers with multiple tags in one API call.

### ISSUE THREAD

**Issue by patrickbolle** [MONEI/Shopify-api-node#198]
I'm looking to search for customers that have tag X or tag Y without doing multiple API calls. 
This page details a bit on how to do this but it is quite ambiguous and I'm not sure how that translates into this library - https://help.shopify.com/en/api/getting-started/search-syntax

I was hoping to do something like - 
```
    shopify.customer.search({ query: 'tag:' + tag1 + 'tag:' + tag2 })
```
but sadly that doesn't return any results.

Any ideas here?

**Comment by lpinca** [comment]
I'm not sure, maybe something like this?

```js
{ query: `tag:${tag1} OR tag:${tag2}` }
```

**Comment by patrickbolle** [comment]
That works perfect! Thanks so much.
