### ISSUE TITLE
Add backoff and retry option

### ISSUE THREAD

**Issue by corbinu** [MONEI/Shopify-api-node#199]
Hello,

The autoLimit works great when doing a bunch of operations in a row. However I have noticed in the last few days that Shopify must have speedup something in their system as I am getting Product/Update webhooks called against my API at faster than their own API limit. Each product update hook makes a single call for that products metafields so the autoLimit doesn't help. Thoughts?

**Comment by lpinca** [comment]
I'm not sure I understand the issue, are webhooks triggered too frequently? In that case the only thing to do is to reduce the request rate and the `autoLimit` option already allows to do that in a configurable way.

**Comment by corbinu** [comment]
@lpinca Yes the webhooks have been triggering faster than 2 a second. The autoLimit isn't helping because there is no way for it to cross process boundaries. It would work fine if we had one process on one server but we do not. 

So Shopify seems to be calling us more like 6 a second which is getting load balanced across our servers. We then reply to each at the same rate even with the autoLimit set only 1 response per second. 

I will try to find time to open a PR tomorrow with exponential back off.

**Comment by corbinu** [comment]
Just as a note we have known this was an issue and were planning to move all our webhook handlers to faktory however the business version with rate limting keeps getting delayed.

**Comment by lpinca** [comment]
> The autoLimit isn't helping because there is no way for it to cross process boundaries.

Yes the state is not shared between the processes/services. That case can be addressed by allowing each process to send up to only a fraction of the total limit no? For example if you have 4 processes let each process send up to `limit/4`.

I can't see how a retry + exponential back off strategy would help for this.

**Comment by corbinu** [comment]
@lpinca Yes but that both would be less performant most of the time and assumes that the number is static don't really want to have to change the value constantly around black friday for example.

Sorry I should be more clear this is happening in bursts. For example we have multiple regular and Shopify Plus clients that do large batch product updates from their ERP every few hours or every day. So ERP would be pushing like 40K product updates at once right at the API limit.

Used to be this was rare but in the last couple days it has happend everytime that happens I get emails from Shopify of our webhook failing. However I checked the logs and it is failing because we are getting these webhooks much faster than Shopify's API limits. The key is this is a burst that then dissipates. I believe that the sudden change has been caused by Shopify making a performance update on their end causing the webhooks to fire off faster. Eventually it settles down as Shopify keeps retrying and all the hooks eventually clear.

So backing off on for example both 429 failure and if the most recent request was within the autoLimit had a `X-Shopify-Shop-Api-Call-Limit` of less than lets say half (all of this would be configurable) would spread the hits to Shopify's api out and we would stop having to return a failure.

**Comment by lpinca** [comment]
In my opinion that is not the right way to handle rate limiting. Retrying and backing off is not good as you should never get a 429 in the first place. If you get a 429 it means that you are doing something wrong. If you can' stay below the limit, for example due to bursts, a queue + dispatch strategy should ensure that the limit is never reached.

**Comment by corbinu** [comment]
@lpinca I am sorry but it is Shopify who is doing something wrong. Ideally they would never call their webhooks faster than their own API limits but thats not what is happening in reality.

**Comment by corbinu** [comment]
I get this is a non ideal solution to a non ideal problem but the problem does not appear to have any ideal solutions. If faktory was at 1.0 and had throttling support we would be using that but it still has not been released.

**Comment by lpinca** [comment]
> Ideally they would never call their webhooks faster than their own API limits but thats not what is happening in reality.

Hmm, how can an event that is fired as a result of an API call be triggered faster that the API call itself?

Also assume that webhooks were completely decoupled from the API calls so that you would not know how often webhooks were triggered. How would you handle that? What I'd do is making sure that my "makeAPICall" function, invoked by the weebhook, does not create more that `x/timeslice` requests regardless of how many times the webhook calls it.

**Comment by corbinu** [comment]
Because multiple events can cause the events to fire orders are still causing product quantities to change and triggering their own product update events. 

Again that doesn’t work with multiple servers.

**Comment by corbinu** [comment]
I guess I will just create my own fork.

**Comment by lpinca** [comment]
> Because multiple events can cause the events to fire orders are still causing product quantities to change and triggering their own product update events.

Ok, now it makes sense, thank you.

Using a job queue seems a better solution to me, Faktory is not the only one, see for example https://github.com/OptimalBits/bull.

Again, in my opinion, the problem should not be "fixed", it should not be created.

**Comment by richardscarrott** [comment]
@corbinu the [Shopify docs](https://help.shopify.com/en/api/getting-started/api-call-limit) seems to recommend @lpinca's approach -- so having your code manage the call rate in an attempt to mimic Shopify's internal rate limiting state -- however we too have many independent services (and many instances of those services) which don't share memory so it's hard to know how one would reliably divi up the API limit.

Did you implement a retry mechanism and was it successful -- I was thinking it'd make sense to be able to configure a cron job to back-off further than, for example, a request from a user where response time is more critical -- basically some form of priority flag?

**Comment by corbinu** [comment]
@richardscarrott Yes they do and if Shopify respected their API limits when calling out to webhooks that would be fine. This should never be an issue when your calling them it is only when they call you and then that triggers something that calls them (for example our product/update hook goes and pulls that products metafields).

Yes I simply turned on retries with an exponential backoff and that is working for now. I have been making a lot of changes to my version since however. Do you need it asap or can you await a week?

**Comment by richardscarrott** [comment]
I'm not in production yet so can wait -- would be great to see how you've solved it 👍 

I still think it'd become a problem for us calling Shopify (without listening to webhooks), e.g. we have a one service which runs a cron job to fetch all products and another separate service (which doesn't share memory or state) fetching all orders -- isn't there a risk that they'll hit the API limit because they aren't aware that the API limit is being consumed by one another?

**Comment by corbinu** [comment]
@richardscarrott Sounds good 

Well that's something I am adding where the service would use the last known state to figure out if the API limit is getting close. That way even if two services were running at once they would see the limit was draining to fast. This could even be improved further by sharing state between the services (for example if both services can talk to a Redis DB that keeps track of the last know API level). Or even creating another service that they both can post to which just echos back the last API limit level it was given (consul has features for that built in actually).

However really the best solution would probably be a job queue which was my original way to solve the problem. Unfortunately finding one with decent rate limiting is next to impossible. So my solution was to go with the fastest fix then keep building smarter versions so that hopefully the bad quick fix never gets depended on (however I see no reason not to leave it there as a fail safe).

**Comment by brunolm** [comment]
I have the same issue mentioned with multiple servers.

What can I do when I have 20 servers calling the API? What if I scale down to 2 or up to 40?

Do I have to try/catch manually and retry? Does the package offer a retry option or something?
