### ISSUE TITLE
Create customer if cant find.

### ISSUE THREAD

**Issue by PrimalIan** [MONEI/Shopify-api-node#212]
Hey all. I am trying to Create a new customer if they don't already exist or update one if they do. Fairly simple and straightforward.

Right now I am trying:
`return shopify.customer.list({customer: { email: e }}).then(customers => { 
            console.log("Customers:   " + customers)
        }).catch(error => {
console.log(error);
            return error;
        })`

and 

`return shopify.customer.search({ query: 'email: ' + e }).then(customer => { 
             console.log(customer) 
         }).catch(error => {
console.log(error);
             return error;
         })`

As of right now neither are returning anything at all. I'm not really sure if I'm even doing the customer look up right.

any help would be awesome

**Comment by lpinca** [comment]
Try this:

```js
shopify.customer.search({ query: `email:${email}` })
```

Note the missing space after `email:`.

**Comment by lpinca** [comment]
I don't know, try with `curl`, https://insomnia.rest/ or something like that and see if it works.

**Comment by PrimalIan** [comment]
Nevermind! I am an idiot! I had an if statement surrounding it from early tests that it was never even getting to it. SMH

**Comment by lpinca** [comment]
It's a PUT see https://github.com/MONEI/Shopify-api-node/blob/ffa12ef657aaff8de33b3242afc93db972d111f3/mixins/base.js#L83-L86

**Comment by PrimalIan** [comment]
Am I doing this wrong?

`var t = tags
                if(cust.tags !== '' && cust.tags !== undefined ){
                    t = cust.tags + ',' + tags
                }
                return shopify.customer.update(cust.id,{id: cust.id, email: cust.email, tags: t})`
