### ISSUE TITLE
IProductImage with alt attribute

### ISSUE THREAD

**Issue by PabloRosales** [MONEI/Shopify-api-node#217]
Shopify API sends now the alt attribute, would be nice if IProductImage type is updated for this.

IProduct.image is not using IProductImage.

Also IPage has a typo in: template_suffic and is not using IObjectMetafield for metafield.

I can make a pull request for this in the next days if needed.

Thanks for the great lib :)

**Comment by lpinca** [comment]
Yes please do it.

**Comment by lpinca** [comment]
Fixed by #218.
