### ISSUE TITLE
Multiple webhook requests

### ISSUE THREAD

**Issue by mpopedeveloper** [MONEI/Shopify-api-node#221]
Edit: Just as a side note, my code is in TypeScript

Good morning! I'm currently working with the Shopify node API and was wondering if you could help me with an issue I am having with the web hooks feature. I am successfully creating web hooks, and they work and respond whenever I need for example, "customers/create", and my server request sends the web hook. However, multiple web hook server requests are made and I was wondering why this might be?

My code is similar to this:

```
router.js
router.post("/product/webhooks/*", ProductsController.ProductWebhook);

ProductController.js
public static ProductWebhook(req: Request, res: Response) {
        const headers = req.headers;
        let actionType = headers["x-shopify-topic"];
        let createdProductId = (headers["x-shopify-product-id"] as string);
        let accessToken = Shopify.accessToken;
        const shopify = new ShopifyAPI({
            shopName: "my shop name",
    
            accessToken: accessToken
        });
        if (actionType === "products/delete") {
            console.log("Product was deleted");

        } else {
            console.log("The action type was: " + actionType);
            shopify.product.get(parseInt(createdProductId))
                .then(result => {
                    console.log(result);
                    return result;
                })
                .catch(error => {
                    console.log(error);
                    return error;
                });
        }
    }
```
My only problem here is that while the webhook will fire correctly, it will fire the code two or three times, as if two or three products have been created when in fact, only one has been. At first I thought that this might be an issue with my code (which it may well be), I just simply thought it was something with Shopify API because the web hook its self is fired multiple times. Is this an issue with Shopify web hook API and if so is there a way for me to fix this issue? or am I simply missing something in my code?

Thanks in advance! Michael

**Comment by lpinca** [comment]
It seems you are not sending a response when your handler is called. Try to reply with 200

```js
res.end();
```

My guess is that the webhook times out so Shopify tries again.

**Comment by mpopedeveloper** [comment]
@lpinca Thank you for your reply!  I used:

`res.end();`

However it still sends multiple times.

**Comment by lpinca** [comment]
I don't know then.

**Comment by mpopedeveloper** [comment]
@lpinca Okay! Thank you anyways!

**Comment by xassan** [comment]
They !!! To be continued

**Comment by mpopedeveloper** [comment]
> I don't know then.

I was able to figure it out, I didn't see the part in your docs about webhooks that stated:

Respond to a webhook
Your webhook acknowledges that it received data by sending a 200 OK response. Any response outside of the 200 range will let Shopify know that you did not receive your webhook, including 301 Redirect. Shopify does not follow redirects for webhook notifications and will consider a redirection as an error response.

Shopify has implemented a 5-second timeout period and a retry period for subscriptions. We wait 5 seconds for a response to each request, and if there isn't one or we get an error, we retry the connection to a total of 19 times over the next 48 hours. A webhook will be deleted if there are 19 consecutive failures for the exact same webhook. You should monitor the admin of your webhook tool for failing webhooks.

If you're receiving a Shopify webhook, the most important thing to do is respond quickly. There have been several historical occurrences of apps that do some lengthy processing when they receive a webhook that triggers the timeout. This has led to situations where webhooks were removed from functioning apps.

To make sure that apps don't accidentally run over the timeout limit, we now recommend that apps defer processing until after the response has been sent.

**Comment by lpinca** [comment]
You mean the 5 seconds timeout? Are you waiting more than 5 seconds to send the 200 response?

**Comment by mpopedeveloper** [comment]
> You mean the 5 seconds timeout? Are you waiting more than 5 seconds to send the 200 response?

Yes, once I put the 200 ok response as soon as i received the web hook, it got rid of most of the duplicates

**Comment by lpinca** [comment]
Ok yes that makes sense, I thought you were already doing that.

**Comment by lpinca** [comment]
I'm going to close this then, discussion can continue if needed.

**Comment by mpopedeveloper** [comment]
> I'm going to close this then, discussion can continue if needed.

Thank You!
