### ISSUE TITLE
What is this library?

### ISSUE THREAD

**Issue by Nisthar** [MONEI/Shopify-api-node#223]
I am trying to build an app for shopify. I thought this is a helper library for building shopify apps. Is this library for creating api for a shopify store? 

Can i use this library for building shopify apps? Do i need to use my shop's name or clients shops name when initializing this library?

Sorry for bad english

**Comment by Nisthar** [comment]
I am following this guide: https://help.shopify.com/en/api/tutorials/building-node-app

Is there any way to use this library for it?

**Comment by lpinca** [comment]
This is a library that allows developers to work with the Shopify REST admin API in Node.js.
What are you looking for is probably this https://github.com/Shopify/shopify-node-app

**Comment by Nisthar** [comment]
@lpinca Thanks. Its what i was looking for.
