### ISSUE TITLE
What is input.customer for customer.create and customer.update ?

### ISSUE THREAD

**Issue by amarg26** [MONEI/Shopify-api-node#229]
What is Format of params for for customer.create and customer.update i.e input.customer ? As per test ?

**Comment by lpinca** [comment]
See, https://github.com/MONEI/Shopify-api-node/blob/master/test/fixtures/customer/req/create.json#L2-L27

**Comment by amarg26** [comment]
Thanks. I have a query now that What is the way to pass the form values eg . email and number to the above param? Also I only need Email and Number , If I exclude the rest will it be fine ?

**Comment by lpinca** [comment]
Yes probably, try it, Shopify will answer with a validation error if it doesn't work.

**Comment by amarg26** [comment]
I have following code to create customer 
`const createCustomer = function(shopDomain, accessToken, customer) {
  const shopName=shopDomain.replace('.myshopify.com','');
  const shopify = new ShopifyAPIClient({ shopName: shopName, accessToken: accessToken });

shopify.customer.create(customer).then(
   response => console.log(`customer ${customer}  created`),
   err => console.log(`Error creating customer ${customer} ${JSON.stringify(err.response.body)}`)
);

}`
`createCustomer(shop,accessToken,{
    "email": "steve.lastnameson@example.com",
    "phone": "555-1212",
    "verified_email": true,
    "metafields": [
      {
        "key": "new",
        "value": "newvalue",
        "value_type": "string",
        "namespace": "global"
      }
    ]
      });`
I am getting error in console as `Error creating customer [object Object] {"errors":{"phone":["is invalid"]}}` What am I doing wrong here ?

**Comment by lpinca** [comment]
```
{"errors":{"phone":["is invalid"]}}
```

I guess the phone format is invalid.

**Comment by amarg26** [comment]
Format is 10 digit ?

**Comment by lpinca** [comment]
I don't know, try it or search on Google, this is not an issue in the library.

**Comment by amarg26** [comment]
I used right format and I got response as `customer [object Object]  created` at console .When I check my store admin customer panel. I do not found this entry. Is anything additionally need to be done to get every customer entry at admin store ?

**Comment by lpinca** [comment]
If you got a 200 response then the customer was created and should appear in the admin interface.

**Comment by amarg26** [comment]
`  createCustomer(shop,accessToken,{
    "email": "steve3.lastnameson@example.com",
    "phone": "8237966000",
    "verified_email": true,
    "metafields": [
      {
        "key": "new",
        "value": "newvalue",
        "value_type": "string",
        "namespace": "global"
      }
    ]
      });

const createCustomer = function(shopDomain, accessToken, customer) {
  const shopName=shopDomain.replace('.myshopify.com','');
  const shopify = new ShopifyAPIClient({ shopName: shopName, accessToken: accessToken });

shopify.customer.create(customer).then(
   response => console.log(`customer ${customer.email}  created`),
   err => console.log(`Error creating customer ${customer.email} ${JSON.stringify(err.response.body)}`)
);

}

`

I am getting the customer Hard values in this function call.When I make form and when user submits form (jquery ajax form on client) and I want to store it every time when user submits form . What will be parameters for email and number instead of hard values ?

`function signUpCall(){
  $.ajax({
  method: "POST",
  url: "https://dcf92d61.ngrok.io/signup",
  dataType: "text",
  data: $('#contact_form').serialize()
})
.done(function( data ) {
    alert(JSON.stringify(data)); 
  })
.fail(function(err) {
    alert( "error" + err );
  });
}
</script>

    <form method="POST" accept-charset="UTF-8" id="contact_form" class="contact-form" action="/contact#contact_form" onsubmit="signUpCall();return false;">
     <input type="email" class="" name="email" required placeholder="Please Enter Email" 
     style="width: 420px;  display: inline-block;" />
      <input type="number" class="" name="number" required placeholder="Please Enter Contact Number" 
      style="width: 420px;  display: inline-block;"/>
      <input type='submit'/>
    </form>    ` Thanks.
