### ISSUE TITLE
How to view how many items are oversold on customer

### ISSUE THREAD

**Issue by mpopedeveloper** [MONEI/Shopify-api-node#233]
Good afternoon! I am using this Shopify API for a project which utilizes web hooks for customer orders. The Shopify admin settings for product variants allow customers to purchase items that are out of stock. I have spoken with the Shopify customer support 4 times before this to gather information about this, and they informed me that Shopify's customer support is not equipped to help me with the Shopify API. 

My question is this, I know that the orders web hook response object gives information about a customers order in the object, such as "line_items", "customer", and other information about the order. If a customer buys more of an item than I have in stock, is there anything in the Shopify API such as a web hook that will show me on the customers order how many items that they purchased are in stock, and how many were oversold?

In the order web hook response object, in the nested object "line_items" there are two properties, one called "quantity", which is the amount purchased by the customer, and another property called "fulfilled_items" which I now know is the amount that you can manually fulfill in the Shopify admin page. Is there anything in the order web hook object or anywhere else in the API that will allow me to do this?

Thanks in advance, Michael

**Comment by lpinca** [comment]
I don't know, try to post the question in the Shopify API forum.

**Comment by mpopedeveloper** [comment]
> I don't know, try to post the question in the Shopify API forum.

Okay! Thank you!
