### ISSUE TITLE
How to pass priceRuleId to discount.create as param ?

### ISSUE THREAD

**Issue by amarg26** [MONEI/Shopify-api-node#236]
```
app.post('/referral',  bodyParser.json(),  withAppProxy((error,request,response)=>{

  const codeWord = "Friend";
  const result = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] //choose from those values
    .map(a => [Math.random(), a]) //assign each value a random number - this will create an array of arrays like [[0.123422, 1], [0.848354, 2], ...]
    .sort((a, b) => a[0] - b[0]) //sort by the random number order
    .map(a => a[1]) //pluck the values
    .join("");
    const couponcode=`${codeWord}-${result}`;

  if (error) {
    console.error(error);
    return;
  }
      
   const {
     proxy: {
       shop,
       accessToken
     },
     body: {
      email,
      phone
    }
   } = request;

   const shopify = new ShopifyAPIClient({
     shopName: shop,
     accessToken
   });


   //let priceRuleId = 
   shopify.priceRule.create({
    email,
    phone,
    title: "REFERRALFRIEND",
    allocation_method: "each",    
    once_per_customer: true,
    target_type: "line_item",
    target_selection: "all",
    value_type: "percentage",
    value: -15.0,
    customer_selection: "all",
    starts_at:"2018-10-10T1:00:10Z"
    }).then(
     data => {
      // console.log(`price rule created = `, data);
       response.json({
          status: 'success',
           price_rule: {
             id: data.id
           }
        });
     },
     err => {
       console.log(`Error in create price rule'. = `, err);
       console.log(`Error creating price rule'. ${JSON.stringify(err.response.body)}`);
       response.status(err.statusCode).send(err.response.body);
     }
   );  
  shopify.discountCode.create({ 
  couponcode
  }).then(
    // async data => {
    // let v = await priceRuleId;
    // console.log(`priceRuleId `,v.price_rule.id);
    // console.log(`coupon code created = `, data);
    
    data => {
      console.log(`coupon code created = `, data);
     response.json({      
       status: 'success',
       discount_code: {
         code:data.code,
         //priceRuleId: data.priceRuleId,
         couponcode: data.couponcode
       }
     });
  },
  err => {
    console.log(`Error in create coupon code'. = `, err);
    console.log(`Error creating coupon code'. ${JSON.stringify(err.response.body)}`);
    response.status(err.statusCode).send(err.response.body);
  }
);
}));
```

**Comment by lpinca** [comment]
```js
shopify.discountCode.create(priceRuleId, { code: 'foo' });
```

**Comment by amarg26** [comment]
I got `data.id` as the first call. Now my problem is I am unable to pass `data.id` to discount.create ```app.post('/referral',  bodyParser.json(),  withAppProxy((error,request,response)=>{

  const codeWord = "Friend";
  const result = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] //choose from those values
    .map(a => [Math.random(), a]) //assign each value a random number - this will create an array of arrays like [[0.123422, 1], [0.848354, 2], ...]
    .sort((a, b) => a[0] - b[0]) //sort by the random number order
    .map(a => a[1]) //pluck the values
    .join("");
    const couponcode=`${codeWord}-${result}`;

  if (error) {
    console.error(error);
    return;
  }
      
   const {
     proxy: {
       shop,
       accessToken
     },
     body: {
      email,
      phone
    }
   } = request;

   const shopify = new ShopifyAPIClient({
     shopName: shop,
     accessToken
   });



   shopify.priceRule.create({
    email,
    phone,
    title: "REFERRALFRIEND",
    allocation_method: "each",    
    once_per_customer: true,
    target_type: "line_item",
    target_selection: "all",
    value_type: "percentage",
    value: -15.0,
    customer_selection: "all",
    starts_at:"2018-10-10T1:00:10Z"
    }).then(
     data => {
        price_rule: {
             id: data.id
        }

        console.log("price rule ID inside",data.id);
     },
     err => {
       console.log(`Error in create price rule'. = `, err);
       console.log(`Error creating price rule'. ${JSON.stringify(err.response.body)}`);
       response.status(err.statusCode).send(err.response.body);
     }
   );  

 }));

 app.post('/create-discount',  bodyParser.json(),  withAppProxy((error,request,response)=>{

  shopify.discountCode.create({ 

   }).then(    
     data => {
       console.log(`coupon code created = `, data);
      response.json({      
        status: 'success',
        discount_code: {
         code: ''
        }
      });
   },
   err => {
     console.log(`Error in create coupon code'. = `, err);
     console.log(`Error creating coupon code'. ${JSON.stringify(err.response.body)}`);
     response.status(err.statusCode).send(err.response.body);
   }
  );
}));```
