### ISSUE TITLE
Unable to retrieve list of orders given a comma-separated list of ids

### ISSUE THREAD

**Issue by grug** [MONEI/Shopify-api-node#237]
The Order spec (https://help.shopify.com/en/api/reference/orders/order#index) indicates that when retrieving orders you can provide a comma-separated list of ids to retrieve specific orders, however when executing the following code for my shop (have verified that I can retrieve these orders individually and that they exist):

```js 
  const shopify = new Shopify({
    shopName: 'myshop.com',
    apiKey: process.env.SHOPIFY_API_KEY,
    password: process.env.SHOPIFY_PASSWORD
  });

  return shopify.order
    .list({ ids: '1234,1200' })
    .then(orders => console.log(orders))
    .catch(error => console.error(error));
```

I get an empty array as a response. I have looked through the codebase and there are no tests for this and there doesn't seem to be the support for `ids` as a parameter through to the order API.

Can someone confirm this or point me in the right direction?

**Comment by lpinca** [comment]
Here is the test https://github.com/MONEI/Shopify-api-node/blob/67bf2cb305961ea75a38ca4f11821d65e9afb740/test/order.test.js#L25-L34. It uses `page` instead of `ids`, it's just a different search parameter.

Try to make the same request manually, with curl for example, and see if it works.

**Comment by grug** [comment]
`page` is different to `ids` though - they can't be seen as equivalent. Are there any plans to add support for `ids`?

**Comment by lpinca** [comment]
Why is it different? `ids` is just another search parameter like `page`. The query string library user under the hood handles all search parameters according to their type and append them to the URL.

```js
qs.stringify({ ids: '1111,222' });
```

Did you try with `curl` or https://insomnia.rest/? Is this lib doing something different?

**Comment by grug** [comment]
Yep have tried it with curl :)

`ids` returns specific orders, `page` retrieves a certain page of results. With `page`, you can't retrieve a specific set of orders

**Comment by lpinca** [comment]
Yes I get that but there is no difference from any other search parameters. My point is, we should have one test to see if search parameters are handled correctly (we have that), if that works all other parameters should work too. Having tests for each possible parameter and any combination of them is silly.

**Comment by lpinca** [comment]
> I've tried it with 3 different stores and have spoken to other developers and nobody can make it work with this API client, but can make it work with a manually crafted curl request.

🤔 

Here is a working example. Test it yourself before I delete the test shop.

```js
const Shopify = require('shopify-api-node');
const { deepStrictEqual } = require('assert');

const shopify = new Shopify({
  shopName: 'prugne',
  apiKey: 'c269dfe019a3a20e42a1e70ecbd5dbc4',
  password: 'd51709784566352cc46f30af615cbf4b'
});

(async function () {
  // Get all open orders.
  let orders = await shopify.order.list();

  deepStrictEqual(orders.map(({ id }) => id), [
    683519574127,
    683519377519,
    683518951535
  ]);

  // Retrieve certain orders, specified by a comma-separated list of order IDs.
  orders = await shopify.order.list({
    ids: '683519377519,683518951535'
  });

  deepStrictEqual(orders.map(({ id }) => id), [
    683519377519,
    683518951535
  ]);
})().catch(console.error);
```

**Comment by lpinca** [comment]
You have to use the actual order IDs in the comma separated list, not the four digit numbers that are shown in admin dashboard.

**Comment by grug** [comment]
I'm an absolute moron... I'm sorry for bothering you about this, Luigi! The problem was the order ID thing and not using the 4 digit numbers shown in the dashboard.
