### ISSUE TITLE
Fulfillment - Create - location_id 422 Error

### ISSUE THREAD

**Issue by arbelh** [MONEI/Shopify-api-node#247]
The following

```
shopify.fulfillment.create(
    orderID,
    {
        "fulfillment": {
            "location_id": locationID,
            "tracking_number": null,
            "notify_customer": false,
            "line_items": [{ id: lineItemID }]
        }
    }
)
.then(fulfillments => {
    console.log(fulfillments);
})
.catch(err => console.error(err.response.body));
```
Returns a 422 error:

`{ error: 'location_id must be specified when creating fulfillments.' }`
Even when a valid `location_id` is present in the object.

Exactly the same object body works when directly sent to the following path by POST
`/admin/orders/orderID/fulfillments.json`

**Comment by lpinca** [comment]
See https://github.com/MONEI/Shopify-api-node#resources

> When using shopify-api-node you don't have to specify the full object but only the nested one as the module automatically wraps the provided data.
