### ISSUE TITLE
Feature request: Being able to execute ShopifyQL Analytics queries

### ISSUE THREAD

**Issue by RaphArbuz** [MONEI/Shopify-api-node#256]
Hi Everyone,

Thank you for this Shopify-api-node library, it proves very helpful!

I was wondering how come there was no way to run a ShopifyQL query to retrieve analytics? Is there a technical limitation to that?

Many thanks.

Raphael

**Comment by lpinca** [comment]
According to https://help.shopify.com/en/api/reference/analytics/shopify-ql, ShopifyQL requests must be made using the Embedded App SDK.

**Comment by RaphArbuz** [comment]
Thanks Luigi. I don't know why this limitation exists. Let's hope it's just temporary and something will be released.
