### ISSUE TITLE
Issue with Shopify.ITenderTransaction not exported

### ISSUE THREAD

**Issue by PabloRosales** [MONEI/Shopify-api-node#258]
Hey, just installed the latest version, but I'm getting this issue, seems like `Shopiy.` does not belong here.

Thanks

`node_modules/shopify-api-node/index.d.ts:546:45 - error TS2694: Namespace 'Shopify' has no exported member 'ITenderTransaction'.

546     list: (params?: any) => Promise<Shopify.ITenderTransaction[]>;
                                                ~~~~~~~~~~~~~~~~~~
Found 1 error.`

**Comment by PabloRosales** [comment]
Actually seems like ITenderTransaction does not exist.

**Comment by lpinca** [comment]
Fixed in https://github.com/MONEI/Shopify-api-node/commit/1e00a5d6ffec8c44fd4231e3c74eaf56b5edf9aa.
Thank you for reporting.

**Comment by PabloRosales** [comment]
Great, thanks to you :)
