### ISSUE TITLE
Retrieving Shipping Rates

### ISSUE THREAD

**Issue by penguinbroker** [MONEI/Shopify-api-node#261]
The shipping rates API has a special case where it returns a 202 status code, this means the shipping rates are not available yet and should be retried later. Right now I don't see how to distinguish between the 202 status code and 200 status code, both of which return empty arrays but need to be handled differently by the sales channel app.

Any ideas on the best way to go about this in the context of this lib? Can't think of an approach that doesn't require changing the api signature for basically everything method. Alternative is something completely separate (and hacky) for this use case.

Thoughts?

**Comment by lpinca** [comment]
Yes, this is not handled because at the time of writing no endpoint returned 202. There is indeed no proper way to know when 202 is returned. I can only think of adding an additional argument to `Shopify.prototype.request()` to make it return the whole response object but it is a private method.

**Comment by lpinca** [comment]
Or better make `Shopify.prototype.request()` return a new request recursively when status code is 202, possibly handling the `Retry-After` header. In this way it is totally transparent for the end user.

**Comment by jbgrunewald** [comment]
This would also be the case with the checkout API's then. I think this is something worth working on. Polling for a 200 is very common in that API set.
