### ISSUE TITLE
Response code 422 (Unprocessable Entity) when creating products

### ISSUE THREAD

**Issue by BrownieBits** [MONEI/Shopify-api-node#262]
Hello. I have been trying to figure this issue out for a few days now and haven't been able to find a reason I am getting the error.

I have created an API Call that takes a JSON Object with a list of Products to create. It loops through the list and creates the products. Right now I am testing with three products. Two products will look like duplicates in everything but the image and possibly a meta.

Right now the two products that are the same, one gets created and one errors out with the 422 response.

In the error response I get back there is no Body so I cannot tell what I am doing wrong.

Here are my bits of code and response...

I put --removed-- for items in the response that I didn't want to be shown

 

I get one Men's jersey and one Women's... the Second Men's object in the list errors out.

**The Product Array:**
`"products": [
    {
      "title": "Men's Evo Corsa Bibs",
      "body": " ",
      "vendor": "T05840A",
      "type": "Women's Evo Corsa Bibs",
      "tags": "test",
      "img": "https://image.shutterstock.com/image-photo/funny-portrait-hero-260nw-410898763.jpg",
      "variants": [
        {
          "option1": "XS",
          "price": "100.00",
          "sku": "PW-99-059-XS"
        },
        {
          "option1": "SM",
          "price": "100.00",
          "sku": "PW-99-059-SM"
        },
        {
          "option1": "MD",
          "price": "100.00",
          "sku": "PW-99-059-MD"
        },
        {
          "option1": "LG",
          "price": "100.00",
          "sku": "PW-99-059-LG"
        },
        {
          "option1": "XL",
          "price": "100.00",
          "sku": "PW-99-059-XL"
        },
        {
          "option1": "2XL",
          "price": "100.00",
          "sku": "PW-99-059-2XL"
        },
        {
          "option1": "3XL",
          "price": "100.00",
          "sku": "PW-99-059-3Xl"
        }
      ],
      "pcp_id": "376b61c7-d419-46b8-bc30-23e347387585",
      "option": ""
    },
    {
      "title": "Men's Evo Corsa Bibs",
      "body": " ",
      "vendor": "T05840A",
      "type": "Women's Evo Corsa Bibs",
      "tags": "test",
      "img": "https://cdn-images.threadless.com/threadless-shop/products/6061/1272x920design_01.jpg?w=1272&h=920",
      "variants": [
        {
          "option1": "XS",
          "price": "100.00",
          "sku": "PW-99-059-XS"
        },
        {
          "option1": "SM",
          "price": "100.00",
          "sku": "PW-99-059-SM"
        },
        {
          "option1": "MD",
          "price": "100.00",
          "sku": "PW-99-059-MD"
        },
        {
          "option1": "LG",
          "price": "100.00",
          "sku": "PW-99-059-LG"
        },
        {
          "option1": "XL",
          "price": "100.00",
          "sku": "PW-99-059-XL"
        },
        {
          "option1": "2XL",
          "price": "100.00",
          "sku": "PW-99-059-2XL"
        },
        {
          "option1": "3XL",
          "price": "100.00",
          "sku": "PW-99-059-3Xl"
        }
      ],
      "pcp_id": "376b61c7-d419-46b8-bc30-23e347387585",
      "option": ""
    },
    {
      "title": "Women's Evo Corsa Bibs",
      "body": " ",
      "vendor": "T05840A",
      "type": "Women's Evo Corsa Bibs",
      "tags": "test",
      "img": "https://image.shutterstock.com/image-photo/funny-portrait-hero-260nw-410898763.jpg",
      "variants": [
        {
          "option1": "XS",
          "price": "100.00",
          "sku": "PW-99-059-XS"
        },
        {
          "option1": "SM",
          "price": "100.00",
          "sku": "PW-99-059-SM"
        },
        {
          "option1": "MD",
          "price": "100.00",
          "sku": "PW-99-059-MD"
        },
        {
          "option1": "LG",
          "price": "100.00",
          "sku": "PW-99-059-LG"
        },
        {
          "option1": "XL",
          "price": "100.00",
          "sku": "PW-99-059-XL"
        },
        {
          "option1": "2XL",
          "price": "100.00",
          "sku": "PW-99-059-2XL"
        },
        {
          "option1": "3XL",
          "price": "100.00",
          "sku": "PW-99-059-3Xl"
        }
      ],
      "pcp_id": "376b61c7-d419-46b8-bc30-23e347387585",
      "option": ""
    }
  ]`
 
**The Product Add Code:**
`products.forEach(async (product, index) => {
    if(product.title !== '' && product.title !== undefined){  
      // metas.push({'key': 'pid', 'value': product.pcp_id,'value_type': 'string','namespace': 'pcp_id'});
      let gender = "NS"
      if(product.title.includes("Women")){
        gender = "Womens"
      }
      else if(product.title.includes("Men")){
        gender = "Mens"
      }
      if (product.design_option !== "" && product.design_option !== undefined){
          metas.push({'key': 'option', 'value': product.design_option,'value_type': 'string','namespace': 'design_option'});
      }
      if (product.variants.length === 1){
          varis.push({"option1": product.variants[0].option1,"price": product.variants[0].price,"weight": 0.5, "sku": product.variants[0].sku})
      }
      else{
        product.variants.forEach(variant => {
          variant.weight = 0.5;
          if (variant.sku.includes("SM/MD")){
            variant.sku = variant.sku.replace("SM/MD", "C");
          }
          else if(variant.sku.includes("LG/XL")){
            variant.sku = variant.sku.replace("LG/XL", "D");
          }
          else if(variant.sku.includes("XS/SM")){
            variant.sku = variant.sku.replace("XS/SM", "A");
          }
          else if(variant.sku.includes("1Size")){
            variant.sku = variant.sku.replace("-1Size", "");
          }
        })
      }
      console.log('*** Index:', index)
      console.log("Title:  ", product.title);
      console.log("Body:  ", product.body);
      console.log("Vendor:  ", collection_title);
      console.log("Shipping:  ", shipping);
      console.log("Gender:  ", gender);
      console.log("Image:  ", product.img);
      console.log("Variants:  ", product.variants);
      try{
        const added_product = await shopify.product.create({
          title: product.title,
          vendor: collection_title,
          product_type: product.title,
          tags: `${shipping},manage,${gender}`,
          images: [{"src": product.img}]
        });
      }
      catch(err){
        console.log('Errored Index:', index)
        console.log(err)
      }
    }
    await new Promise((resolve, reject) => setTimeout(resolve, 500));
  });`
 

**The Response:**
`{ HTTPError: Response code 422 (Unprocessable Entity)
    at stream.catch.then.data (/srv/node_modules/got/index.js:386:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  name: 'HTTPError',
  host: undefined,
  hostname: '--removed--',
  method: 'POST',
  path: '/admin/products.json',
  protocol: 'https:',
  url: undefined,
  statusCode: 422,
  statusMessage: 'Unprocessable Entity',
  headers: 
   { server: 'nginx',
     date: 'Fri, 29 Mar 2019 18:02:16 GMT',
     'content-type': 'application/json; charset=utf-8',
     'transfer-encoding': 'chunked',
     connection: 'close',
     'x-sorting-hat-podid': '56',
     'x-sorting-hat-shopid': '--removed--',
     'referrer-policy': 'origin-when-cross-origin',
     'x-frame-options': 'DENY',
     'x-shopid': '--removed--',
     'x-shardid': '56',
     'x-stats-userid': '',
     'x-stats-apiclientid': '--removed--',
     'x-stats-apipermissionid': '--removed--',
     'x-shopify-api-terms': 'By accessing or using the Shopify API you agree to the Shopify API License and Terms of Use at https://www.shopify.com/legal/api-terms',
     http_x_shopify_shop_api_call_limit: '2/80',
     'x-shopify-shop-api-call-limit': '2/80',
     'strict-transport-security': 'max-age=7889238',
     'x-request-id': '--removed--',
     'x-shopify-stage': 'canary',
     'content-security-policy': 'default-src \'self\' data: blob: \'unsafe-inline\' \'unsafe-eval\' https://* shopify-pos://*; block-all-mixed-content; child-src \'self\' https://* shopify-pos://*; connect-src \'self\' wss://* https://*; frame-ancestors \'none\'; img-src \'self\' data: blob: https:; script-src https://cdn.shopify.com https://checkout.shopifycs.com https://js-agent.newrelic.com https://bam.nr-data.net https://dme0ih8comzn4.cloudfront.net https://api.stripe.com https://mpsnare.iesnare.com https://appcenter.intuit.com https://www.paypal.com https://maps.googleapis.com https://www.google-analytics.com https://v.shopify.com https://widget.intercom.io https://js.intercomcdn.com \'self\' \'unsafe-inline\' \'unsafe-eval\'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=create&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fproducts&source%5Bsection%5D=admin_api&source%5Buuid%5D=1e6591ee-ec93-42dc-bc08-b3bf46df86de',
     'x-content-type-options': 'nosniff',
     'x-download-options': 'noopen',
     'x-permitted-cross-domain-policies': 'none',
     'x-xss-protection': '1; mode=block; report=/xss-report?source%5Baction%5D=create&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fproducts&source%5Bsection%5D=admin_api&source%5Buuid%5D=1e6591ee-ec93-42dc-bc08-b3bf46df86de',
     'x-dc': 'chi2,gcp-us-east1' } }`

**Comment by lpinca** [comment]
> In the error response I get back there is no Body so I cannot tell what I am doing wrong.

Use

```js
console.log(err.response.body);
```

**Comment by BrownieBits** [comment]
Thank you @lpinca I had tried err.response.body.errors and didn't get anything but hadn't tried just looking at the body.
So I found that it is because the Handle has already been taken but I was under the impression that if the Handle was already used, Shopify would add a number to the end... Is this not always the case?

**Comment by lpinca** [comment]
I don't know but it doesn't seem to be an issue in this lib, is it?

**Comment by BrownieBits** [comment]
Nope seems like everything is fine here.

**Comment by impactcolor** [comment]
422 means you're not actively authorized
