### ISSUE TITLE
Support API versioning

### ISSUE THREAD

**Issue by tim-phillips** [MONEI/Shopify-api-node#266]
Shopify just released API versioning:

https://help.shopify.com/en/api/versioning

**Comment by lpinca** [comment]
With the current interface where would you specify the version to use? In the constructor?

**Comment by tim-phillips** [comment]
That seems reasonable. 

Obviously the existing calls still work, and I assume call the latest version of the api, so that should probably remain the default.

**Comment by lpinca** [comment]
Yes, I think most of the work would on updating URLs in tests.

**Comment by alexandrefarber2** [comment]
@tim-phillips better to use a no-versioned URL as the default. Shopify's behaviour is to use the oldest available stable version as a default if no version was specified.
cc @lpinca

**Comment by theRealPadster** [comment]
I've added basic support for this in #285 but it still needs tests.
