### ISSUE TITLE
[question] How to filter by fields on a "list" operations?

### ISSUE THREAD

**Issue by pmarconi** [MONEI/Shopify-api-node#271]
How can I filter by fields on a 'list' operation? 
for example for products I want to obtain the ones which `vendor` value have "nike"

And I can see it in my /admin store like this 
https://mystore.myshopify.com/admin/products/search.json?query=vendor:Nike

It should be possible to do something like this?
```
shopifyClient.product.list({  vendor: 'Nike'  })
.then(console.log)
.catch(console.log);
```

thx

**Comment by lpinca** [comment]
Please refer to https://help.shopify.com/en/api/reference/products/product#index. `vendor` is accepted so your example should work.
