### ISSUE TITLE
Support paginated results

### ISSUE THREAD

**Issue by obscure18** [MONEI/Shopify-api-node#292]
Could not retrieve all products (if 250 products and more) by just executing :  `shopifyApi.product.list()`. It would be great to be able to handle automatically calling all the products here instead of having to handle the pagination ourselves.

It's a very new issue for me and it seems to be a rather recent change to the Shopify Admin REST API : https://help.shopify.com/en/api/guides/paginated-rest-results

**Comment by tim-phillips** [comment]
Can't you do this using `params` object?

```js
shopifyApi.product.list({
  page_info: 'aljsd0foaisdnf',
  limit: 10
})
```

**Comment by korucam** [comment]
That's true, but filling the value of `page_info` is challenging - how can you access the `Link` header when [the `Shopify.prototype.request` function returns only the `.body` part of the response](https://github.com/MONEI/Shopify-api-node/blob/master/index.js#L131)?

**Comment by joelvh** [comment]
I created a pagination function like this, with a `processor` that is simply an async callback to allow you to do something per page as this paginates through all pages.

```es6

export async function pager ({
  client,
  target,
  operation,
  params = {}
}, processor = Promise.resolve.bind(Promise)
) {
  console.log('SHOPIFY PAGER', 'target', target, 'operation', operation, 'params', params)

  const request = client[target][operation]({ limit: 250, ...params })
  const thisPage = await request.then(response => formatData(response))

  await processor(thisPage)

  console.log('SHOPIFY PAGER', 'thisPage', thisPage)

  if (thisPage.length === 0 || thisPage.length < (params.limit || 250)) {
    return thisPage
  }

  return pager({
    client,
    target,
    operation,
    params: { ...params, page: (params.page || 1) + 1 }
  }, processor)
    .then(nextPage => thisPage.concat(nextPage))
}
```

**Comment by joelvh** [comment]
Similar pagination function for GraphQL:

```es6
export async function graphqlPager ({
  client,
  field,
  query,
  variables = {}
}, processor = Promise.resolve.bind(Promise)) {
  const request = client.graphql(query, variables)
  const response = await request.then(response => formatData(response))
  const { [field]: { pageInfo: { hasNextPage }, edges = [] } } = response

  // unwrap
  const thisPage = edges.map(({ node }) => node)

  // perform processing like persistence
  await processor(thisPage)

  if (!hasNextPage) {
    return thisPage
  }

  return graphqlPager({
    client,
    field,
    query,
    variables: {
      ...variables,
      cursor: edges[edges.length - 1].cursor
    }
  }, processor)
    .then(nextPage => thisPage + nextPage)
}
```

**Comment by kdolan** [comment]
The above solutions are not compliant with the `2019-07` API version. Attempting the above solutions will result in the following 400 Error:
```json
{
    "errors": {
        "page": "page cannot be passed. See https:\/\/help.shopify.com\/api\/guides\/paginated-rest-results for more information."
    }
}
```

**Comment by agentlewis** [comment]
@joelvh I did something very similar and have it in production. I will refactor mine and see if i can post something.

**Comment by lpinca** [comment]
> Pagination support either needs to be supported internally or the Link header needs to be returned in addition to the response body to allow a workaround.

I'm ok with returning response headers but I'm not sure how to do it in a non breaking way. I think the cleanest way would be to return the whole response object and remove the [wrap/unwrap](https://github.com/MONEI/Shopify-api-node#resources) done by the library.

**Comment by himanshu-singh1995** [comment]
> > Pagination support either needs to be supported internally or the Link header needs to be returned in addition to the response body to allow a workaround.
> 
> I'm ok with returning response headers but I'm not sure how to do it in a non breaking way. I think the cleanest way would be to return the whole response object and remove the [wrap/unwrap](https://github.com/MONEI/Shopify-api-node#resources) behavior.

I have the following solution in mind to support pagination in a non-breaking way (assuming page parameter is not being passed anymore for cursor-based pagination.):

1. Wrap the body into a sub-class of Array which has a function like `hasNext` and `next` to support pagination.
```
const shopify = new Shopify({
    shopName: shopName,
    apiKey: apiKey,
    password: password,
    autoLimit: { calls: 2, interval: 1000, bucketSize: 35 },
    apiVersion: '2019-07'
  });
const response = await shopify.product.list({ limit: 250}); // here response is a sub-class of array.
if (response.hasNext()) {
   const nextPage = await response.next();
}
```
2. Internally handle the pagination and return the combined results of all pages (Seems this would be a breaking change.)(Not Recommended).
3. Leave the existing methods as it is and just mark them as deprecated and add new list methods which will support cursor-based pagination. (Recommended)

**Comment by JasonZigelbaum** [comment]
Hey chiming in here since I just had to refactor a few other projects that didn't use this repo and am now getting around to this one.

I think it's a bizarre move for Shopify to put the next/prev page links in the header but I'm guessing theres a reason they couldn't just add next/previous to the body.

In any case can I suggest doing something like:

1. When you get the response from Shopify check for the links in the header.
2. If they exist, parse them out.
3. Append them the body JSON object using some sort of private notation like:

```
body._pagination_cursor.next = { The link sent from the Header (if exists) }
body._pagination_cursor.prevous = { The link sent from the Header (if exists) }
```

And then just document it so it's obvious for users that it deviates from the official docs.

It's not ideal but I don't think you run the risk of overriding any future body response if you use some sort of private notation. Also doing this keeps a single response object so it would be non-breaking. In my opinion updating the response object to be an array would end up being a lot more net work for consumers of your package than to append the extra private info.

**Comment by ozzyonfire** [comment]
For anyone else who is running into this issue, I just edited the `request` method to return an object containing both the headers and the body. Essentially what @lpinca suggested above.

i.e.
```javascript
...
return got(options).then(res => {
  ...
  if (key) {
    return {
      body: body[key],
      headers: res.headers
    }
  }
  return  {
    body: body || {},
    headers: res.headers
  }
}
...
```

Then we will able to pass page_info using the information in the link header. Of course, this will break any code that is currently using the API, but without pagination this API is pretty useless (imo).

**Comment by Art3miX** [comment]
Just FYI, pagination using {page: 1} passed as params still works @ozzyonfire.

I think @ozzyonfire idea is the best, but as is, it would be a breaking change, what if we will add some kind of a flag to the params we pass?

So lets take product list for example 

`const params = {
  limit: 250,
  returnHeaders: true
}

shopifyApi.product.list(params)
`  

And you just delete it from the params object before sending the request.

This will not break any existence code, because the headers will be sent only with this flag set to true.

**Comment by ShaunParsons** [comment]
> > Pagination support either needs to be supported internally or the Link header needs to be returned in addition to the response body to allow a workaround.
> 
> I'm ok with returning response headers but I'm not sure how to do it in a non breaking way. I think the cleanest way would be to return the whole response object and remove the [wrap/unwrap](https://github.com/MONEI/Shopify-api-node#resources) behavior.

I think a breaking change here is unavoidable unfortunately. So its probably worth discussing what the best way forward is to try and hide future breaking changes from the consumers of this package. Perhaps changing the response of `list` to be something like:

```json
{
    data: [], // current response
    hasNext: true/false,
    next: function (), // get the next page
}
```

Future changes can then be encapsulated within this object. This could also be compatible with the existing API if the `next` function just increased the current `page` parameter by one. So consumers of this package could upgrade the version of this package before upgrading to the latest version of the API.

**Comment by bogdanmarin** [comment]
Any updates on this? When it will be released? I think breaking is ok if the release notes tell you how to deal with it and offer some todo examples .

**Comment by lpinca** [comment]
I did not test it but something like this should work:

```diff
diff --git a/index.js b/index.js
index d2f65e7..448f5f3 100644
--- a/index.js
+++ b/index.js
@@ -11,6 +11,9 @@ const urlLib = require('url');
 const pkg = require('./package');
 const resources = require('./resources');
 
+const kNext = Symbol('kNext');
+const kPrevious = Symbol('kPrevious');
+
 /**
  * Creates a Shopify instance.
  *
@@ -74,6 +77,10 @@ function Shopify(options) {
   }
 }
 
+Object.defineProperty(Shopify, 'symbols', {
+  value: { kNext, kPrevious }
+});
+
 Object.setPrototypeOf(Shopify.prototype, EventEmitter.prototype);
 
 /**
@@ -139,8 +146,16 @@ Shopify.prototype.request = function request(url, method, key, params) {
         .then(() => this.request(newUrl, 'GET', key));
     }
 
-    if (key) return body[key];
-    return body || {};
+    const data = key ? body[key] : body || {};
+
+    if (res.headers.link) {
+      const cursor = parseLinkHeader(res.headers.link);
+
+      data[kNext] = cursor.next;
+      data[kPrevious] = cursor.previous;
+    }
+
+    return data;
   }, err => {
     this.updateLimits(
       err.response && err.response.headers['x-shopify-shop-api-call-limit']
@@ -246,4 +261,35 @@ function delay(ms) {
   return new Promise(resolve => setTimeout(resolve, ms));
 }
 
+/**
+ * Parses the `Link` header into an object.
+ *
+ * @param {String} header The field value of the header
+ * @return {Object} The parsed object
+ * @private
+ */
+function parseLinkHeader(header) {
+  return header.split(',').reduce(reducer, {});
+}
+
+/**
+ * The callback function for `Array.prototype.reduce()` used by
+ * `parseLinkHeader()`.
+ *
+ * @param {Array} acc The accumulator
+ * @param {Object} cur The current element being processed in the array
+ * @return {Object} The accumulator
+ * @private
+ */
+function reducer(acc, cur) {
+  const pieces = cur.trim().split(';');
+  const query = urlLib.parse(pieces[0].trim().slice(1, -1), true).query;
+  const rel = pieces[1].trim().slice(4);
+
+  if (rel === 'next') acc.next = query;
+  else acc.previous = query;
+
+  return acc;
+}
+
 module.exports = Shopify;
```

```js
const Shopify = require('shopify-api-node');

const { kNext, kPrevious } = Shopify.symbols;

const shopify = new Shopify({
  shopName: 'your-shop-name',
  apiKey: 'your-api-key',
  password: 'your-app-password'
});

(async function() {
  let params = { limit: 10 };

  do {
    const products = await shopify.product.list(params);

    console.log(products);

    params = products[kNext];
  } while(params);
})().catch(console.error);
```

**Comment by bogdanmarin** [comment]
And if you want to go directly to a specific page, do you need to iterate all the time?

**Comment by bogdanmarin** [comment]
Let me re-phrase if I want to get directly page 3, should I go to 1->2 to have the link to 3? So you can load them progressively but not jump to a specific page?

**Comment by akashkaushik33** [comment]
> I did not test it but something like this should work:
> 
> ```diff
> diff --git a/index.js b/index.js
> index d2f65e7..448f5f3 100644
> --- a/index.js
> +++ b/index.js
> @@ -11,6 +11,9 @@ const urlLib = require('url');
>  const pkg = require('./package');
>  const resources = require('./resources');
>  
> +const kNext = Symbol('kNext');
> +const kPrevious = Symbol('kPrevious');
> +
>  /**
>   * Creates a Shopify instance.
>   *
> @@ -74,6 +77,10 @@ function Shopify(options) {
>    }
>  }
>  
> +Object.defineProperty(Shopify, 'symbols', {
> +  value: { kNext, kPrevious }
> +});
> +
>  Object.setPrototypeOf(Shopify.prototype, EventEmitter.prototype);
>  
>  /**
> @@ -139,8 +146,16 @@ Shopify.prototype.request = function request(url, method, key, params) {
>          .then(() => this.request(newUrl, 'GET', key));
>      }
>  
> -    if (key) return body[key];
> -    return body || {};
> +    const data = key ? body[key] : body || {};
> +
> +    if (res.headers.link) {
> +      const cursor = parseLinkHeader(res.headers.link);
> +
> +      data[kNext] = cursor.next;
> +      data[kPrevious] = cursor.previous;
> +    }
> +
> +    return data;
>    }, err => {
>      this.updateLimits(
>        err.response && err.response.headers['x-shopify-shop-api-call-limit']
> @@ -246,4 +261,35 @@ function delay(ms) {
>    return new Promise(resolve => setTimeout(resolve, ms));
>  }
>  
> +/**
> + * Parses the `Link` header into an object.
> + *
> + * @param {String} header The field value of the header
> + * @return {Object} The parsed object
> + * @private
> + */
> +function parseLinkHeader(header) {
> +  return header.split(',').reduce(reducer, {});
> +}
> +
> +/**
> + * The callback function for `Array.prototype.reduce()` used by
> + * `parseLinkHeader()`.
> + *
> + * @param {Array} acc The accumulator
> + * @param {Object} cur The current element being processed in the array
> + * @return {Object} The accumulator
> + * @private
> + */
> +function reducer(acc, cur) {
> +  const pieces = cur.trim().split(';');
> +  const query = urlLib.parse(pieces[0].trim().slice(1, -1), true).query;
> +  const rel = pieces[1].trim().slice(4);
> +
> +  if (rel === 'next') acc.next = query;
> +  else acc.previous = query;
> +
> +  return acc;
> +}
> +
>  module.exports = Shopify;
> ```
> 
> ```js
> const Shopify = require('shopify-api-node');
> 
> const { kNext, kPrevious } = Shopify.symbols;
> 
> const shopify = new Shopify({
>   shopName: 'your-shop-name',
>   apiKey: 'your-api-key',
>   password: 'your-app-password'
> });
> 
> (async function() {
>   let params = { limit: 10 };
> 
>   do {
>     const products = await shopify.product.list(params);
> 
>     console.log(products);
> 
>     params = products[kNext];
>   } while(params);
> })().catch(console.error);
> ```

This is not working. I am using version 3.3.2 and this line throws error  `const { kNext, kPrevious } = Shopify.symbols` because symbols is undefined in Shopify object
