### ISSUE TITLE
assets cannot query with .list(id, params)

### ISSUE THREAD

**Issue by yongyi520** [MONEI/Shopify-api-node#295]
```
const shopify = new Shopify({
      shopName,
      accessToken
    })

shopify.asset.list(mainThem.id, {"asset[key]": "assets/gift-card.js"})
```

when I checked the console.log i got nothing in return

it works if I use 
```
shopify.asset.get(mainThem.id, {"asset[key]": "assets/gift-card.js"})
```

Am I doing something wrong here?

**Comment by Mistermo716** [comment]
Just ran into a  similar issue.

This will not work:
`shopify.asset.get(theme.id, { "key": "assets/bundles.js" })`
This will work:
`shopify.asset.get(theme.id, { "asset[key]": "assets/bundles.js" })`

However, when using the create asset this works:
`shopify.asset.create(theme.id, { "key": "assets/bundles.js", "value": `${data}` })`

Is this inconsistency intended?

**Comment by lpinca** [comment]
It works as documented. See https://help.shopify.com/en/api/reference/online-store/asset#show-2019-07

**Comment by yongyi520** [comment]
Ok I see, thank you @lpinca
