### ISSUE TITLE
Return Body of Shopify Responses for Failed Requests

### ISSUE THREAD

**Issue by jbgrunewald** [MONEI/Shopify-api-node#304]
When using shopify-api-node I'm left with vanilla http error messages for request failures, but in practice Shopify usually returns details about why the request failed. It would be valuable to return these message bodies for logging and debugging purposes. I find this especially useful as Shopify moves towards enforcing API versioning and intend to deprecate the older APIs.

**Comment by lpinca** [comment]
Use

```js
err.response.body
```

**Comment by EduardsE** [comment]
This should be somewhere in documentation. Kinda struggled finding this.
