### ISSUE TITLE
Exposing the raw response

### ISSUE THREAD

**Issue by lnenad** [MONEI/Shopify-api-node#307]
We have a use case when working with checkout when we receive a 202 response which indicates an invalid checkout state. Since it's not != 2xx we don't get an error and there is no way to access the status code nor the response headers for successful responses..

I would like to create a PR to add the possibility to return the full response object, or at least a new object that would contain the status code and response headers since we would need access to the Location and Retry-After headers. 

https://help.shopify.com/en/api/guides/sell-through-the-checkout-api#polling

Would this be ok with you?

**Comment by lpinca** [comment]
See https://github.com/MONEI/Shopify-api-node/pull/298.

**Comment by lnenad** [comment]
So essential this was resolved and should be automatically handled?

**Comment by lpinca** [comment]
Yes, exactly.
