### ISSUE TITLE
GraphQL Update Metafields on Collection.

### ISSUE THREAD

**Issue by BrownieBits** [MONEI/Shopify-api-node#310]
I am attempting to update the metafields on a collection. when I do so I get an error that says: `InputObject 'CollectionInput' doesn't accept argument 'metafields'`

The correct way to do it is the way I am doing it. 
`mutation{
  collectionUpdate(input:{id:"<id>", metafields:[ {id:"<meta_id>" value:"2019-10-30 11:59pm"}]}){
    collection{
      id
    }
  }
}`

any ideas?

**Comment by BrownieBits** [comment]
I have confirmed with the Shopify team that the Mutation I am doing and the way I am doing it is correct... is there a possibility something in this codebase isn't liking it?

**Comment by lpinca** [comment]
I don't know. Check that request (the HTTP method, the headers, and the body) sent by `shopify-api-node` is correct.

**Comment by BrownieBits** [comment]
@lpinca I am going to close this. The issue was, I was not being specific about which Shopify API version I wanted to use in the Init. When you don't specify API Version it defaults to the oldest published version out there. The oldest version out there is fairly limited when it comes to GraphQL... as soon as I specified the version, it worked. Thank you!
