### ISSUE TITLE
Does Pagination work?

### ISSUE THREAD

**Issue by morkro** [MONEI/Shopify-api-node#314]
First of all, thanks for this great API! It's been a real time saver. :)

However, I don't seem to get pagination working though. I am using your [example on Pagination](https://github.com/MONEI/Shopify-api-node/tree/9738c03cb533176cd14f9435e5a81b6fdfd9ee77#pagination) but `nextPageParameters` is always `undefined`. I've tried the API directly (per URL) and I clearly get the `page_info` in `Link` headers. I also traversed through your source code, but I don't see where it could go wrong.

My code:

```js
 try {
    let products = []
    let listParams = { limit: 10 }

    do {
      const fetched = await shopify.product.list(listParams)
      products = [...products, ...fetched]
      listParams = fetched.nextPageParameters
      console.log(`products: ${products.length}`)
    } while (listParams !== undefined)
  } catch (error) {
    console.error(error)
  }
```

The response is always (as expected) an array with products, but `nextPageParameters` is `undefined`.

What am I doing wrong?

**Comment by lpinca** [comment]
Try to specify the latest API version (2019-10). By default the oldest supported stable version is used.

**Comment by lpinca** [comment]
Also make sure to use `shopify-api-node@2.24.0`.

**Comment by morkro** [comment]
Upgrading to `2.24.0` did the trick! I was still on `2.23.0`. Thanks @lpinca! 👏

**Comment by lpinca** [comment]
Ok, closing then.
