### ISSUE TITLE
autoLimit should actually check Shopify response and wait to retry

### ISSUE THREAD

**Issue by fancydev18** [MONEI/Shopify-api-node#324]
Hi,

We're looking at switching to this library instead of https://github.com/christophergregory/shopify-node-api

There's an issue with autoLimit. The other library accepted a limit and it automatically checks Shopify's response with the remaining limit, and waits until it retries again. Simply said, it just works, we never had to worry about limits. Some calls will take longer to return.

Here we tried 
```
autoLimit: { calls: 1, interval: 1000, bucketSize: 16 }, 
```
according to https://github.com/MONEI/Shopify-api-node/issues/135

and it still gives error
```
"statusCode": 429,
	"statusMessage": "Too Many Requests",
```
after ~10 seconds. 

We can see the Shopify limit decreasing with ```.on('callLimits')```, but the library seems to ignore it.
Could it check that and wait automatically?

Checking it would also help if having multiple instances making simultaneous calls. Since the current limit is always returned by Shopify, no need to worry what limits to set in each case.

Thanks

**Comment by lpinca** [comment]
The limit is per instance, if you have multiple instances you need another strategy. See discussion in https://github.com/MONEI/Shopify-api-node/issues/199.

**Comment by fancydev18** [comment]
Right, it turns out there was another instance on the same app. This is quite complex to manage.

The fix seems simple: could you please check for 429 code, wait a little and retry? Here's how the other library does it in 4 lines:
https://github.com/christophergregory/shopify-node-api/blob/master/lib/shopify.js#L196

It would all be hidden from this library users and it will work no matter how many instances are used (across multiple servers).

**Comment by lpinca** [comment]
No, that's wrong, you should never get 429, it's a user error. Tweak the `autoLimit` config to handle multiple instances or use a queue. I will not add a retry + backoff solution based on the 429 status code.

If you want it disable the `autoLimit` option and implement it yourself, the `http.ServerResponse` and its status code is attached to the `error` object.

```js
p.catch((err) => console.log(err.response.statusCode))
```

**Comment by joantune** [comment]
@lpinca  - 'just use a queue' - erm we have a hint from the server on both the response code and the headers.
Why is it `wrong`? it's definitely something I'm willing to implement - as it's much easier than the answer of: change your whole architecture
Serverless? tough luck - make it a queue somehow.. that somehow takes into account the time..

**Comment by joantune** [comment]
Also - the Retry-after header exists for the same purpose - from Shopify's docs:
https://help.shopify.com/en/api/reference/rest-admin-api-rate-limits
```
    Use the rate limits header to balance your request volume.

Handling exceeded rate limits

If your app is throttled, then it won't be able to make any more requests until enough time has passed and your bucket has capacity again. You can calculate this wait time manually using the bucket size and leak rate properties, or by using the Retry-After response header. Your app can also use a more general exponential backoff algorithm to complete the call at a later time.
```
