### ISSUE TITLE
get single asset returns 'undefined'

### ISSUE THREAD

**Issue by achieveapplabs** [MONEI/Shopify-api-node#325]
How do I retrieve a single asset without using .list? This is my code:

shopify.asset.get(themeId, {key: 'snippets/example.liquid'}).then((asset) => {console.log(asset)});

Pretty sure I'm getting params wrong. Should I be using the asset's ID instead of key? I'm concerned because I'll also want to use shopify.asset.delete and not sure.

**Comment by achieveapplabs** [comment]
Solved!

`let params = {

'asset[key]', 'snippets/example.liquid'

}`

Params should be an object and the key name is literally 'asset[key]' what a weird keyname.

**Comment by mysticaltech** [comment]
Thanks @achieveapplabs, same goes for asset.delete for those getting a 406 error!
