### ISSUE TITLE
customers.orders returns blank array.

### ISSUE THREAD

**Issue by FutureHits3Dev** [MONEI/Shopify-api-node#333]
According to the doc you need to pass a customer id into the customer.orders method but it returns a blank array to any customer id I put in.
https://github.com/MONEI/Shopify-api-node/blob/master/resources/customer.js#L67

**Comment by lpinca** [comment]
Yes, see https://help.shopify.com/en/api/reference/customers/customer#orders-2020-01. Try to make the same request with `curl`, https://insomnia.rest/ or any other client and see if you get the same results.

**Comment by FutureHits3Dev** [comment]
It's weird sometimes the method shopify.customer.orders() will bring back a customer orders and sometimes it doesn't. But I know all the customer exists. I get the customer id from /admin/api/2020-01/customers.json. Weird.

**Comment by Process-Dom** [comment]
I was pulling my hair out over this, try;
`shop.customer.orders(123456t789, { status: 'any' })`

**Comment by lpinca** [comment]
I'm closing this as it does not seem to be an issue in the library. Discussion can continue if needed.

**Comment by mkhizeryounas** [comment]
Same issue for me as well, any news?

**Comment by FutureHits3Dev** [comment]
@mkhizeryounas @Process-Dom has the solution. It worked for me.
