### ISSUE TITLE
Using callLimits on Paginated Request

### ISSUE THREAD

**Issue by 3daddict** [MONEI/Shopify-api-node#337]
Would I be able to use call limits to see the status of a Paginated request?
Things like: { remaining: 30, current: 10 } or is the callLimits object for something else?

**Comment by lpinca** [comment]
`callLimits` allows you to monitor the [API rate limits](https://help.shopify.com/en/api/reference/rest-admin-api-rate-limits) not the status of paginated requests.

**Comment by 3daddict** [comment]
> `callLimits` allows you to monitor the [API rate limits](https://help.shopify.com/en/api/reference/rest-admin-api-rate-limits) not the status of paginated requests.

Thanks for letting know.
