### ISSUE TITLE
Timeout when calling discountCode.create

### ISSUE THREAD

**Issue by schlaegerz** [MONEI/Shopify-api-node#343]
In my code I am attempting to create a discount and getting a timeout after 60 seconds. 

```
return shopify.discountCode.create(priceRuleId, {code: code}).then((item)=>{
               // do stuff
            }).catch(err=>{
                console.error("Error making coupon",  err)
            })
```
I went into the package and logged what was being called inside of index.ks
I20200213-14:19:30.816(-8)? {
I20200213-14:19:30.816(-8)?   pathname: '/admin/price_rules/<MY PRICE RULE ID HERE>/discount_codes.json',
I20200213-14:19:30.816(-8)?   hostname: '<MY HOST NAME HERE>,
I20200213-14:19:30.817(-8)?   protocol: 'https:',
I20200213-14:19:30.817(-8)?   username: '<MY USERNAME HERE>',
I20200213-14:19:30.817(-8)?   password: '<MY PASSWORD HERE>'
I20200213-14:19:30.817(-8)? } POST discount_code { code: 'TEST_TEST_TEST' } undefined {
I20200213-14:19:30.817(-8)?   headers: { 'User-Agent': 'shopify-api-node/3.1.0' },
I20200213-14:19:30.818(-8)?   timeout: 60000,
I20200213-14:19:30.818(-8)?   responseType: 'json',
I20200213-14:19:30.818(-8)?   retry: 0,
I20200213-14:19:30.818(-8)?   method: 'POST',
I20200213-14:19:30.819(-8)?   json: { discount_code: { code: 'TEST_TEST_TEST' } }
I20200213-14:19:30.819(-8)? }

And then I mimmicked it with a curl command 
curl -d '{ "discount_code": { "code": "TEST_TEST_TEST" } }'  -H "Content-Type: application/json"  -X POST https://<USERNAME>:<PASSWORD>@<HOST>/admin/price_rules/<PRICERULE_ID>/discount_codes.json

Which did work just fine.

This means that this is definitely a problem within this package. I reached out to shopify support and they said they could not help me with this.

This was working a few months ago on our production server, and only recently started breaking.

**Comment by lpinca** [comment]
There is not much we can do without a clear description of what the package does wrong. Please create a working example to reproduce the issue.

**Comment by schlaegerz** [comment]
Here is the full example that was breaking. I don't know what else to give you, Shopify claimed this wasn't even hitting their endpoint.
```

import Shopify from 'shopify-api-node'
let shopify = null

    shopify = new Shopify({
        apiKey: <MY API KEY>
        password: <MY PASSWORD>,
        shopName: <MY SHOP NAME>,

    })
    return shopify.discountCode.create(<MY PRICE RULE ID>, {code: "TEST_TEST_TEST"}).then((item)=>{
      //...
    }).catch(err=>{
        console.error("Error making coupon", priceRuleId, code, type, user,  err)
        return {error: true, message:"request failed"}
    })

```

**Comment by lpinca** [comment]
I've just tested it and it works as expected:

```js
const Shopify = require('shopify-api-node');

const shopify = new Shopify({
  shopName: 'redacted',
  apiKey: 'redacted',
  password: 'redacted'
});

(async function() {
  const priceRule = await shopify.priceRule.create({
    title: 'SUMMERSALE10OFF',
    target_type: 'line_item',
    target_selection: 'all',
    allocation_method: 'across',
    value_type: 'fixed_amount',
    value: '-10.0',
    customer_selection: 'all',
    starts_at: '2017-01-19T17:59:10Z'
  });

  const discountCode = await shopify.discountCode.create(priceRule.id, {
    code: 'SUMMERSALE10OFF'
  });

  console.log(discountCode);
})().catch(console.error);
```

```
{
  id: 3942938968099,
  price_rule_id: 634120503331,
  code: 'SUMMERSALE10OFF',
  usage_count: 0,
  created_at: '2020-02-14T15:27:14-05:00',
  updated_at: '2020-02-14T15:27:14-05:00'
}
```

**Comment by schlaegerz** [comment]
With that same code I get this error:
```
W20200214-12:46:40.898(-8)? (STDERR) GotError: Timeout awaiting 'request' for 60000ms
W20200214-12:46:40.899(-8)? (STDERR)     at onError (/Users/zacholigschlaeger/toyboxwebsite/node_modules/got/dist/source/request-as-event-emitter.js:136:29)
W20200214-12:46:40.899(-8)? (STDERR)     at ClientRequest.<anonymous> (/Users/zacholigschlaeger/toyboxwebsite/node_modules/got/dist/source/request-as-event-emitter.js:156:17)
W20200214-12:46:40.900(-8)? (STDERR)     at ClientRequest.emit (events.js:215:7)
W20200214-12:46:40.900(-8)? (STDERR)     at ClientRequest.EventEmitter.emit (domain.js:475:20)
W20200214-12:46:40.900(-8)? (STDERR)     at ClientRequest.origin.emit (/Users/zacholigschlaeger/toyboxwebsite/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
W20200214-12:46:40.901(-8)? (STDERR)     at Timeout.timeoutHandler [as _onTimeout] (/Users/zacholigschlaeger/toyboxwebsite/node_modules/got/dist/source/utils/timed-out.js:40:17)
W20200214-12:46:40.909(-8)? (STDERR)     at listOnTimeout (internal/timers.js:533:17)
W20200214-12:46:40.909(-8)? (STDERR)     at Timeout.timeoutHandler [as _onTimeout] (/Users/zacholigschlaeger/toyboxwebsite/node_modules/got/dist/source/utils/timed-out.js:40:31)
W20200214-12:46:40.910(-8)? (STDERR)     at listOnTimeout (internal/timers.js:533:17)
W20200214-12:46:40.910(-8)? (STDERR)     at processTimers (internal/timers.js:475:7)
W20200214-12:46:40.910(-8)? (STDERR)  => awaited here:
W20200214-12:46:40.911(-8)? (STDERR)     at Function.Promise.await (/Users/zacholigschlaeger/.meteor/packages/promise/.0.11.2.1ixw4hn.8uhlk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20200214-12:46:40.911(-8)? (STDERR)     at server/lib/shopifyHelpers.js:24:18
W20200214-12:46:40.915(-8)? (STDERR)     at /Users/zacholigschlaeger/.meteor/packages/promise/.0.11.2.1ixw4hn.8uhlk++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40 {
W20200214-12:46:40.915(-8)? (STDERR)   name: 'TimeoutError',
W20200214-12:46:40.916(-8)? (STDERR)   code: 'ETIMEDOUT',
W20200214-12:46:40.916(-8)? (STDERR)   event: 'request',
W20200214-12:46:40.916(-8)? (STDERR)   timings: {
W20200214-12:46:40.918(-8)? (STDERR)     start: 1581713140760,
W20200214-12:46:40.919(-8)? (STDERR)     socket: 1581713140763,
W20200214-12:46:40.919(-8)? (STDERR)     lookup: 1581713140767,
W20200214-12:46:40.919(-8)? (STDERR)     connect: 1581713140773,
W20200214-12:46:40.919(-8)? (STDERR)     secureConnect: 1581713140798,
W20200214-12:46:40.920(-8)? (STDERR)     upload: 1581713140799,
W20200214-12:46:40.921(-8)? (STDERR)     response: 1581713141186,
W20200214-12:46:40.921(-8)? (STDERR)     end: 1581713200771,
W20200214-12:46:40.921(-8)? (STDERR)     error: 1581713200767,
W20200214-12:46:40.921(-8)? (STDERR)     abort: 1581713200771,
W20200214-12:46:40.922(-8)? (STDERR)     phases: {
W20200214-12:46:40.931(-8)? (STDERR)       wait: 3,
W20200214-12:46:40.932(-8)? (STDERR)       dns: 4,
W20200214-12:46:40.932(-8)? (STDERR)       tcp: 6,
W20200214-12:46:40.932(-8)? (STDERR)       tls: 25,
W20200214-12:46:40.932(-8)? (STDERR)       request: 1,
W20200214-12:46:40.933(-8)? (STDERR)       firstByte: 387,
W20200214-12:46:40.933(-8)? (STDERR)       download: 59585,
W20200214-12:46:40.933(-8)? (STDERR)       total: 60011
W20200214-12:46:40.933(-8)? (STDERR)     }
W20200214-12:46:40.933(-8)? (STDERR)   }
W20200214-12:46:40.934(-8)? (STDERR) }
```

Since you can't repro anything do you have any suggestions on what I can investigate? This is definitely not resolved.

This was all working for met a few months ago without me changing any relevant code, but I may have changed some packages, but I don't even know which ones to look at.

**Comment by schlaegerz** [comment]
I reverted back to 2.25.1 and there is no problem, so it is definitely caused by this package. After digging around it looks like this package updated the "got" dependency from 8.x.x to 10.x.x which has some pretty big breaking changes.


https://github.com/sindresorhus/got/releases/tag/v10.0.0

https://github.com/sindresorhus/got/releases/tag/v9.0.0

I don't know nearly enough about this package to know what changes are relevant, but I'm guessing that my environment means that not correctly handling this update is what is causing problems. I would suggest re-opening this bug, since I am not likely to be the only person who will hit this, and it should at least be apparent that if someone sees this bug they should revert the version.

**Comment by lpinca** [comment]
I will not reopen because I can't reproduce the issue.

Make sure you are using the latest version of `shopify-api-node` and reinstall all dependencies. Also when you open an issue please specify more details like the OS, the OS version, the Node.js version, etc.
 
Issues with a description like "look this code does not work" are not very useful. We (maintainers) don't know nothing about the environment where your code is run.

**Comment by schlaegerz** [comment]
Well for anyone else who has a similar setup, my bug is with:

node 12.14.0, on both my dev machine (Mac OS) and a Heroku linux instance. 

This is only reproing on version 3.x.x and not 2.x.x

**Comment by stefanosala** [comment]
@schlaegerz I had the same issue, check if you have a `agent-base` dependency version v4. They were overriding a code https method that was causing issues with `got`.
