### ISSUE TITLE
Get all orders (status=any)

### ISSUE THREAD

**Issue by rounsmith** [MONEI/Shopify-api-node#347]
I am trying to get all the orders from shopify for private api (make analytics short of outside of shopify for a private app i am building) and i need to get all orders closed or not. How can we do this? When i am trying to get all orders at the moment i am getting the open ones(not fullfilled or paid)

**Comment by lpinca** [comment]
See https://shopify.dev/docs/admin-api/rest/reference/orders/order#index-2020-01.

```js
const orders = await shopify.order.list({ status: 'any' });
```

should work.

**Comment by rounsmith** [comment]
oh seems good. I guess params can get any param from shopify api(i didn't test it out tbh). Thank you!
