### ISSUE TITLE
Script tag create with local URL in nextjs on authentication

### ISSUE THREAD

**Issue by hamzah-bao** [MONEI/Shopify-api-node#349]
Hi,
I have added the following code which i am trying to run on authentication of a shopify app:
```
server.use(
    createShopifyAuth({
      apiKey: SHOPIFY_API_KEY,
      secret: SHOPIFY_API_SECRET,
      scopes: [SCOPES],
   async afterAuth(ctx) {
   ...
```

```
const shopify = new Shopify({
   shopName: shop,
   accessToken,
 });

const a = await shopify.scriptTag.create({
     event: "onload",
      src: `scriptFile.js`,
});
console.log('\nscriptTag create: , a');
```

My problem is trying to load the script file if it is hosted locally in NEXT JS in my app. NextJs only  has the option to serve static files by placing them in the 'public' folder which i have tried and it doesn't work. What are my options if i dont want to specify the absolute URL?

**Comment by lpinca** [comment]
I don't know but it does not seem to be a library issue.
