### ISSUE TITLE
Create asset return 406

### ISSUE THREAD

**Issue by Popesites** [MONEI/Shopify-api-node#350]
Have been working on this issue for hours, cannot create asset using asset() resource.

Here is example query:

    const id = this.themeId;
    
    const query = {
      asset: {
        key: "snippets/test.liquid",
        value: "Content"
      }
    };
    
    const asset = await this.shopify.asset.create(id, query); // throws 406 Not Acceptable error

By the way I notice 2 small errors on asset create test... 

1. Using the asset 'update' fixin instead of the 'create' fixin
2. Using the res fixin data instead of the req - basically an invalid request on the test itself?

**Comment by lpinca** [comment]
I don't see the error:

https://github.com/MONEI/Shopify-api-node/blob/f91e090c57b08008c3ecf53718c130111daf5aa3/test/asset.test.js#L62-L71

https://github.com/MONEI/Shopify-api-node/blob/f91e090c57b08008c3ecf53718c130111daf5aa3/test/fixtures/asset/req/create.json#L1-L6

https://github.com/MONEI/Shopify-api-node/blob/f91e090c57b08008c3ecf53718c130111daf5aa3/test/fixtures/asset/res/create.json#L1-L11

In your usage example the second argument of the `create()` method should only be 

```js
const params = { key: 'snippets/test.liquid', value: 'Content' };
```

**Comment by Popesites** [comment]
@lpinca 

Thanks for quick reply.

Could you please check req.json:

https://github.com/MONEI/Shopify-api-node/blob/master/test/fixtures/asset/req/create.json

Looks like:

    {
      "asset": {
        "key": "assets/empty.gif",
        "attachment": "R0lGODlhAQABAPABAP///wAAACH5BAEKAAAALAAAAAABAAEAAAICRAEAOw==\n"
      }
    }

I think this syntax is different than what you suggested?

**Comment by lpinca** [comment]
It's ok. See,

https://github.com/MONEI/Shopify-api-node/blob/f91e090c57b08008c3ecf53718c130111daf5aa3/test/asset.test.js#L69

`input.asset` is

```js
const params = { 
   key: 'assets/empty.gif', 
   attachment: 'R0lGODlhAQABAPABAP///wAAACH5BAEKAAAALAAAAAABAAEAAAICRAEAOw==\n' 
} ;
```
