### ISSUE TITLE
Product List Pagination

### ISSUE THREAD

**Issue by bluedge** [MONEI/Shopify-api-node#352]
I'm having a hard time converting my old code using `page` to the next pointer for pagination.
I would really appreciate your help.
Simplified code:
```
const shopify = new Shopify({
	shopName: req.session.shop,
	accessToken: req.session.access_token,
	apiVersion: '2019-10'
});
shopify.product.list({ limit: 10, page: 2, collection_id: collection_id, fields:'id,title,image,variants,vendor'})
	.then((products) => { 
		console.log(products);
	})
	.catch(err => {
		console.log(err);
		
	}
);
```

**Comment by nazrdogan** [comment]
What is the exact problem  ?

**Comment by bluedge** [comment]
I console.log() every possible variable but I can't find nextPageParameters nor prevPageParameters.
Also I don't understand how to replace the original "page: 2" argument with the new pointer system. Shopify documentation on this left me with more questions than answers.

**Comment by nazrdogan** [comment]
well , first of all you need to change api version like this `apiVersion: '2020-01',` then you can use do pagination like this https://github.com/MONEI/Shopify-api-node#pagination. or if you want to still use  promise you need to do similar to this https://stackoverflow.com/questions/28549164/how-can-i-do-pagination-with-bluebird-promises

**Comment by bluedge** [comment]
Thank you I though '2019-10' already had this., thx.
Just so I learn something, why a classic callback won't catch the new params?

**Comment by nazrdogan** [comment]
you mean why old api  don't get new params ?

**Comment by bluedge** [comment]
I mean why do I have to use new code notation async / await (versus a regular callback)

**Comment by nazrdogan** [comment]
ahh. so basically shopify deprecated page based pagination. now they are using cursor based pagination. so you will need nextpage token to call next page or previous one. you dont need to use async/await.  you can still use promise way similiar to stackoverflow link which i added above.

**Comment by nazrdogan** [comment]
if you want to use promise way you can use that but i prefer async/await. its very elegant and clean
``` 
let params = { limit: 10 };
function getAllProduct(params) {
    var allProducts = [];
    function getProducts(params) {
        return shopify.product.list(params).then(function (products) {
            allProducts = allProducts.concat(products);
            params = products.nextPageParameters;
            if (params !== undefined) {
                return getProducts(params);
            } else {
                return allProducts;
            }
        }).catch(function (e) {
            console.log(e.stack);
        })
    }
    return getProducts(params)
}
getAllProduct(params).then(function (result) {
    console.log(result.length);
})

**Comment by bluedge** [comment]
Changing the API date to '2020-01' was really the trick. Thank you so much for the guidance and code example.
