### ISSUE TITLE
No Mechanism for When Curser Based Pagination Isn't Supported

### ISSUE THREAD

**Issue by jbgrunewald** [MONEI/Shopify-api-node#354]
The current documentation indicates we should check for unknown to indicate that we are done with paginating using the cursor based pagination. This creates an issue in versions of the client that don't support the cursor based pagination yet, because this value will always be unknown. Rather than simply not setting that field, can we update to specify a more specific value like 'complete'. This would allow for differentiation between the client not support this logic, versus the pagination is actually done.

**Comment by lpinca** [comment]
How is it different? If the client does not support cursor based pagination there is no way to signal completion simply because the client does not even try to see if there is a next and/or previous page.  The `nextPageParameters` and `previousPageParameters` properties will never be set.

**Comment by jbgrunewald** [comment]
It’s different because right now both success and failure look the same. They are both undefined. I can’t tell if there’s a mistake or we just completed pagination through the client in a programmatic manner. Unless perhaps I check to see the product count before hand.  

With a value other than undefined being used, if I made the same error the second attempt to paginate would occur and result in an exception because I passed undefined as the params for the request. 

At a minimum it might be worth mentioning in the docs that you need to be using version three of the client to get the cursor based pagination logic.
