### ISSUE TITLE
Install Broken by Bad GOT Version

### ISSUE THREAD

**Issue by jbgrunewald** [MONEI/Shopify-api-node#355]
When I install any 3.x.x version of the client, I get the below error. This seems to be due to to the auto upgrade rules in the package.json for the client.

micro: Error when importing /Users/jbgrunewald/work/services/ecom-plugin/src/restApi/service.js: /Users/jbgrunewald/work/services/ecom-plugin/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {

I'm running node 8.15.1. This is the only package I know of with a GOT dependency in the application I'm using the client with.

**Comment by lpinca** [comment]
Yes version 3 requires Node.js >= 10.

**Comment by jbgrunewald** [comment]
Is this documented somewhere?

James Grunewald

**Comment by lpinca** [comment]
Yes https://github.com/MONEI/Shopify-api-node/blob/master/package.json#L10. You should get a warning from npm/yarn if you install it on Node.js < 10.

**Comment by jbgrunewald** [comment]
Thanks, I just tried installing and didn’t see any warning about the node version. I do see the setting in the package.json for the client. I’ll have to dig some more. Maybe my npm tool is too far out of date?

James Grunewald

**Comment by lpinca** [comment]
I don't know. Here is the documentation: https://docs.npmjs.com/configuring-npm/package-json.html#engines

> Unless the user has set the `engine-strict` config flag, this field is advisory only and will only produce warnings when your package is installed as a dependency.
