### ISSUE TITLE
Metfields API not Working for Resources Other than Shop

### ISSUE THREAD

**Issue by jbgrunewald** [MONEI/Shopify-api-node#356]
The metfields.list() documentation shows an example passing the owner_id and owner_resource like below. However, the actual implementation doesn't use those parameters and always returns the shop resource metafields.

`shopify.metafield
  .list({
    metafield: { owner_resource: 'product', owner_id: 632910392 }
  })
  .then(
    (metafields) => console.log(metafields),
    (err) => console.error(err)
  );`

**Comment by alxvallejo** [comment]
I'm having issues creating a metafield for `owner_resource: 'variant'` but i don't see where you see it's being set to `shop`?

**Comment by jbgrunewald** [comment]
I was referring to the list functionality. If you attempt to list the metafields for a product by giving product as the owner_resource and the id as owner_id you won’t get back the correct metafields. They will be metafields for the shop resource. This is because the request url is not being built correctly. It’s even more complicated for images and variants. 

James Grunewald

**Comment by alxvallejo** [comment]
@jbgrunewald I still don't see where in the code this is happening. But i'm still unable to create any metafields and get this error: Not sure if its related

```
(node:66769) UnhandledPromiseRejectionWarning: HTTPError: Response code 422 (Unprocessable Entity)
[0]     at EventEmitter.<anonymous> (/Users/alexvallejo/Sites/som-mgmt/node_modules/shopify-api-node/node_modules/got/dist/source/as-promise.js:118:31)
```

**Comment by jbgrunewald** [comment]
Can I see a sample payload? The code is in the base,js file under mixins. That's where the urls are built. This is failing for the same reason the list function returns the wrong metafields. The url being built is always using the metafield as the name, but each resource type has its own path.

I'll be able to work on this eventually, since we want to use these endpoints. Unfortunately, we're two weeks from a launch and it's a bit of a time crunch right now.

**Comment by lpinca** [comment]
I can't reproduce.

```js
const assert = require('assert');
const Shopify = require('shopify-api-node');

const shopify = new Shopify({
  shopName: 'shopName',
  apiKey: 'apiKey',
  password: 'password'
});

(async function() {
  const products = await shopify.product.list();

  assert.deepStrictEqual(products, []);

  const product = await shopify.product.create({
    body_html: '<strong>Good snowboard!</strong>',
    product_type: 'Snowboard',
    title: 'Burton Custom Freestlye 151',
    vendor: 'Burton'
  });

  const params = {
    metafield: { owner_resource: 'product', owner_id: product.id }
  };
  let metafields = await shopify.metafield.list(params);

  assert.deepStrictEqual(metafields, []);

  const metafield = await shopify.metafield.create({
    key: 'warehouse',
    namespace: 'inventory',
    owner_id: product.id,
    owner_resource: 'product',
    value: 25,
    value_type: 'integer'
  });

  console.log(metafield);

  metafields = await shopify.metafield.list(params);

  console.log(metafields);

  await Promise.all([
    shopify.product.delete(product.id),
    shopify.metafield.delete(metafield.id)
  ]);
})().catch(console.error);
```

Works as expected.

**Comment by jbgrunewald** [comment]
@lpinca I think there is not an issue after all. I must have been dropping the metafield part of the params and only including the owner_id owner_resource fields. That seems to reproduce the issue. The [documentation](https://shopify.dev/docs/admin-api/rest/reference/metafield) doesn't show using this pattern for accessing product metafields, which led to some confusion. This pattern is used to access product_imge metafields though... 

Documentation example url path for products: /admin/products/#{id}/variants/#{id}/metafields.json
Documentation example url path for product images: /admin/metafields.json?metafield[owner_id]=#{id}&metafield[owner_resource]=product_image

Anyway, it seems like things are still working. At least for now there's nothing to update. Though it's clear Shopify has added an alternative method for accessing this data. I'm going to reach out on the forums and try to get some clarification and which is the preferred route and if they intend to deprecate either version.

@alxvallejo I'm going to close this issue, since it's unrelated to yours. Feel free to open a new one with an example payload. The error you're receiving indicates that Shopify doesn't like one of the inputs you're using. It's likely a typing issue.

**Comment by lpinca** [comment]
> Though it's clear Shopify has added an alternative method for accessing this data

The alternative method you are referring to has been there for a long time. At least since 2016 (when I started contributing to this library).

I hope they will not deprecate the method used here as it would require quite a bit of work to adapt to it.
