### ISSUE TITLE
API UPDATE - PAGINATION - ISSUE

### ISSUE THREAD

**Issue by Bek81** [MONEI/Shopify-api-node#361]
> A developer needs to change your private apps within 14 days
Private apps installed on your store have made calls to unsupported APIs. To continue working, these apps require changes by a developer to how they handle pagination. Contact the developer of the apps listed below to request the changes, or if you can’t contact the original developer, you can find one on the Shopify Experts Marketplace. This message is based on the last 14 days and may not reflect recently fixed apps.

I updated your API and modified the product listing excluding pagination and usgin your cursor-based version.
I uploaded everything to my server and ran some tests. There were no mistakes, and it seems everything works.
Unfortunately, there is still a WARNING in the Shopify backend.
Do you know why?

Thanks in advance.

**Comment by chhatch** [comment]
How long ago was the app fixed?

> This message is based on the last 14 days and may not reflect recently fixed apps.

In our store the message hung around for a while after the app was updated.

**Comment by Bek81** [comment]
Hi @chhatch .

Exactly yesterday. So I don't have to worry?

Thanks and regards.

**Comment by chhatch** [comment]
It's no trouble @Bek81 

I don't know how long it took for the message to go away for us. If you fixed the issue, I suspect there's nothing to worry about. When in doubt contact Shopify support.

Good luck!

**Comment by Bek81** [comment]
I have already asked for assistance; unfortunately I didn't have much help and they told me to search the forum. 
This is why I trusted more to open an issue here.

Hopefully everything is fine!

Thanks again.

Bek
