### ISSUE TITLE
Required params for customer.list()

### ISSUE THREAD

**Issue by TAnas0** [MONEI/Shopify-api-node#369]
Hey,

My VS Code IntelliSense is signaling an error of usage as such:

![Screenshot from 2020-04-16 17-17-49](https://user-images.githubusercontent.com/12121506/79480670-f01b5d00-7ffd-11ea-98d2-b89096d6040e.png)

I was wondering why `params` is required for customers, but not for products and orders:

```
  customer: {
    ....
    list: (params: any) => Promise<Shopify.ICustomer[]>;
    ....
  };
```

while `order` for example has `params` marked as optional:
```
  order: {
    ....
    list: (params?: any) => Promise<Shopify.IOrder[]>;
    .....
  };
```

**Comment by lpinca** [comment]
It's optional, see the README. Free free to send a PR to fix the type definition.
