### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by NTXAggie** [MONEI/Shopify-api-node#373]
When trying to use pagination in nodejs ("shopify-api-node": "^3.3.1") it throws a syntax error saying that .nextPageParameters does not exist on type IProducts[].

I followed exactly what is in the readme. I also confirmed that there is not any extra pagination data that comes back, it is just a simple array of results. Please help!

**Comment by lpinca** [comment]
Try to specify the API version in the constructor options. See https://github.com/MONEI/Shopify-api-node/issues/372 and https://github.com/MONEI/Shopify-api-node/issues/357.

**Comment by NTXAggie** [comment]
![image](https://user-images.githubusercontent.com/16783541/81484524-9fb5aa80-920b-11ea-9b37-65783003ca36.png)

@lpinca  It does not fix the typescript issue, but

**Comment by lpinca** [comment]
Yes the TypeScript issue is a known issue and it being discussed here https://github.com/MONEI/Shopify-api-node/issues/288.
