### ISSUE TITLE
Shopify.asset.get( themeID, params ) not working

### ISSUE THREAD

**Issue by max-sadlowski** [MONEI/Shopify-api-node#374]
Hi there, and TIA for any assistance. Trying to get an asset file using the following:

```
let params = {
      'key': 'templates/article.liquid'
}

assetDetails = await shopify.asset.get(themeID, params );
```

However assetDetails comes back as undefined. Am I missing something? I have tried multiple different params but can't seem to find the right setup, which makes me think this might be an issue?

**Comment by max-sadlowski** [comment]
As found elsewhere, asset[key] is the key you want to pass. 

```
let params = {
      'asset[key]': 'templates/article.liquid'
}
```

**Comment by lpinca** [comment]
Yes, this is documented here https://shopify.dev/docs/admin-api/rest/reference/online-store/asset?api[version]=2020-04#show-2020-04.
