### ISSUE TITLE
Can we create/install multiple hooks with create method ?

### ISSUE THREAD

**Issue by Tekrajs** [MONEI/Shopify-api-node#375]
The sample code shows us, that we can only create a hooks at one time.
Can't we send params as under and create multiple hooks at once ?

        `this.shopify.webhook.create(
                            {
                                "topic": "products/create",
                                "address": forwardingAddress + "/shopify/product_update",
                                "format": "json"
                            },
                            {
                                "topic": "products/delete",
                                "address": forwardingAddress + "/shopify/product_delete",
                                "format": "json"
                            }
                        ).then(webhook => {
                            console.log(webhook);
                        }).catch(error => {
                            console.log(error);
                        })`

By the right now on doing so, only first one"products/create" is created.

**Comment by jbgrunewald** [comment]
No, this also isn't supported in the Shopify API either. This would just be a helper/wrapper around the create functionality if implemented.

**Comment by Tekrajs** [comment]
@jbgrunewald okay thank you very much for the reply. I will iterate the operation then. Will be following the repo for more update.
Thanks
