### ISSUE TITLE
Missing status code of Shopify API response in error object

### ISSUE THREAD

**Issue by jarold87** [MONEI/Shopify-api-node#383]
We can't identify the type of error, for example 401 Unauthorized. We get it only the error stack string, but it is ceremonious. Could you make available the status code of Shopify API response in the error object. It would be very helpful.

I browsed the "got" readme. It could be a solution:
[https://github.com/sindresorhus/got#hooksbeforeerror](https://github.com/sindresorhus/got#hooksbeforeerror)

(index.js - request method):
![before-error-hook](https://user-images.githubusercontent.com/15094117/82555969-200fd000-9b69-11ea-9cff-76bf6276e79d.png)

![response-status-code](https://user-images.githubusercontent.com/15094117/82555346-e094b400-9b67-11ea-9979-ff5339896aa6.png)

**Comment by lpinca** [comment]
It looks like it's already in the error object in the `responseStatusCode` property.
