### ISSUE TITLE
Question: Polling for Checkout API 303 Response Codes?

### ISSUE THREAD

**Issue by tylerpharand** [MONEI/Shopify-api-node#384]
The Shopify documentation mentions that the creation of checkouts may be throttled in some circumstances, causing the API to send `HTTP 303 See Other` response codes. These responses need to be polled with the provided `Location` header.

From what I can tell, `shopify-api-node` only polls for `202` response codes:
https://github.com/MONEI/Shopify-api-node/blob/master/index.js#L138

Although I was personally not able to reproduce a `303` code through this module, I'm wondering if the polling is missing? Or is it being handled somewhere else?

Reference:
https://shopify.dev/tutorials/sell-through-the-checkout-api#checkout-throttle-polling

**Comment by lpinca** [comment]
`got` the underlying HTTP client we use in `shopify-api-node` already follows redirect automatically unless the feature is disabled (which is not currently).

**Comment by tylerpharand** [comment]
Great. Thanks for the info!
