### ISSUE TITLE
Context influences requests (Response code 401 (Unauthorized))

### ISSUE THREAD

**Issue by BjoernRave** [MONEI/Shopify-api-node#385]
I am trying to create a public app. 

When trying to create a product from inside my application it throws with : `Response code 401 (Unauthorized) `

However when I create a node script like this: 
```
const Shopify = require('shopify-api-node')

const createProduct = async () => {
  const shopify = new Shopify({
    accessToken: ****,
    shopName: ****,
    apiVersion: '2020-04',
  })

  const res = await shopify.product.create({ title: 'Test' })
  console.log(res)
}

createProduct()
```

the product gets created successfully.

I tried to paste the exact same code in my application, but I still get the 401.

My application is built apollo-server-micro and running as an api route from next.js

If you need more info, I am happy to provide.

**Comment by lpinca** [comment]
Unless there is something, like a proxy, that intercepts the requests and changes them this is not possible.

**Comment by BjoernRave** [comment]
this is the error, that I get: 

```
[3] HTTPError: Response code 401 (Unauthorized)
[3]     at onResponse (/Users/bjoern/projects/inventhora/main/node_modules/got/dist/source/as-promise/index.js:124:28)
[3]     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
[3]   code: undefined,
[3]   timings: {
[3]     start: 1594129870674,
[3]     socket: 1594129870674,
[3]     lookup: 1594129870674,
[3]     connect: 1594129870697,
[3]     secureConnect: 1594129870716,
[3]     upload: 1594129870716,
[3]     response: 1594129870910,
[3]     end: 1594129870911,
[3]     error: undefined,
[3]     abort: undefined,
[3]     phases: {
[3]       wait: 0,
[3]       dns: 0,
[3]       tcp: 23,
[3]       tls: 19,
[3]       request: 0,
[3]       firstByte: 194,
[3]       download: 1,
[3]       total: 237
[3]     }
[3]   }
[3] }

```

**Comment by raffi1300** [comment]
> ```js
> const https = require('https');
> ```

That worked for me as well! Thank you! Was quite a headache trying to figure this out

**Comment by raffi1300** [comment]
> ```js
> const https = require('https');
> 
> const request = https.request;
> 
> const auth0 = require('auth0');
> 
> https.request = request;
> ```

That worked for me. Thank you!

**Comment by szmarczak** [comment]
@lpinca I just checked and unfortunately there is no universal solution to check whether the `http`/`https` module was tampered or not. It's not possible to clear the require cache for native modules. The best I can suggest is if all Node.js native modules were read only.

**Comment by lpinca** [comment]
I'm closing this as the issue has been fixed in `superagent-proxy@2.1.0`.

**Comment by BjoernRave** [comment]
okay, `auth0` also just made a new release which includes the updated dependency, will check it later today, but should be good now I guess: https://github.com/auth0/node-auth0/releases

**Comment by lpinca** [comment]
Yes, I ran `npm ls agent-base` after installing the latest version of `auth0` and everything looks good. It should work without issues.

**Comment by BjoernRave** [comment]
can confirm, that it is working now
