### ISSUE TITLE
custom collection update

### ISSUE THREAD

**Issue by yash-habilelabs** [MONEI/Shopify-api-node#388]
Hi
i am trying to update a custom collection using update method under custom collection section as per following.
shopify.customCollection.update(id,{ custom_collection: list });
list is looking like -> {
  id: '165748',
  collects: [
    {
      id: 16576,
      collection_id: 165748,
      product_id: 3822026784816,
      created_at: '2020-06-25T07:51:46-04:00',
      updated_at: '2020-06-27T07:02:01-04:00',
      position: 1,
      sort_value: '0000000001'
    }]}

but the collection isn't updating

**Comment by lpinca** [comment]
Use `list` directly as second argument without using the wrapper object.

**Comment by yash-habilelabs** [comment]
Thanks for the reply. as i got you want to say if i want to update any custom collection then use list fn and pass my object there.
Note list one is my sorted product list which i want to update for the specific collection under custom collection section.

**Comment by yash-habilelabs** [comment]
got the reason. thanks for the help.
