### ISSUE TITLE
Can I use this to provide tax rates from an external source to the Shopify Checkout?

### ISSUE THREAD

**Issue by jamieroyce** [MONEI/Shopify-api-node#391]
I am building an app that needs to make a call at Checkout to an external API that has more accurate tax rate information than is available with Shopify's defaults. I want to return the tax rate by line item and then apply this to the checkout total. Is this possible using the shopify-api-node?

**Comment by lpinca** [comment]
I think it is but you should verify by checking the documentation: https://shopify.dev/docs/admin-api/rest/reference

The issue tracker is only for feature requests and bug in the library.
