### ISSUE TITLE
[Graphql] Do not have restoreRate in callGraphqlLimits object

### ISSUE THREAD

**Issue by rporcon** [MONEI/Shopify-api-node#393]
When doing any call to the graphql API.

The package sent us data related to throttle in `callGraphqlLimits`

However we don't get the `restoreRate` value in the `callGraphqlLimits`:

<img width="473" alt="Screen Shot 2020-07-15 at 14 31 04" src="https://user-images.githubusercontent.com/16135143/87507229-fde98880-c6a7-11ea-92f9-cd2073465b09.png">

In my case I need this information, it can be useful especially that the "Standard limit" and "Shopify Plus Limit" have different restore rate:

<img width="806" alt="Screen Shot 2020-07-15 at 14 32 56" src="https://user-images.githubusercontent.com/16135143/87507330-325d4480-c6a8-11ea-9326-bd2d77ffd466.png">

I'm currently on the version `3.2.1` of the package.

I noticed that it could easily be fixed by adding in the `updateGraphqlLimits` function the following line:
`limits.restoreRate = throttle.restoreRate;`

Then the restoreRate become available in the `callGraphqlLimits` object.

**Comment by lpinca** [comment]
Can you elaborate on why you need it? How would you use it?

**Comment by rporcon** [comment]
Hey @lpinca 

I needed it to be able to throttle the graphql api calls.

Depending on the `restoreRate` the waiting time between each request can be different
