### ISSUE TITLE
Feature: Check for right credentials

### ISSUE THREAD

**Issue by NishargShah** [MONEI/Shopify-api-node#394]
I am making one project that includes all CRUD operations regarding Shopify and I found this package and it's awesome.

Today, I noticed that if I have wrong credentials, It throw something weird error like below

```
{
    "timings": {
        "start": 1595255318397,
        "socket": 1595255318399,
        "lookup": 1595255318482,
        "connect": 1595255318566,
        "secureConnect": 1595255318735,
        "upload": 1595255318736,
        "response": 1595255319366,
        "end": 1595255319377,
        "phases": {
            "wait": 2,
            "dns": 83,
            "tcp": 84,
            "tls": 169,
            "request": 1,
            "firstByte": 630,
            "download": 11,
            "total": 980
        }
    }
}
```

**Feature I want**

1. If there is one feature that tells in boolean that credentials are correct or wrong, it better for error handling 
2. if in the above error there is a unique code or name that specified the error like "CredentialsError" so it is better for error handling.

**Comment by lpinca** [comment]
If the token or username/password are invalid you should get an HTTP response with a 401 status code which is the standard way to indicate that the client is not authenticated.

**Comment by lpinca** [comment]
You can read the response status code as show below:

```js
if (error.response.statusCode === 401) {
  // Do something.
}
```

**Comment by NishargShah** [comment]
> You can read the response status code as show below:
> 
> ```js
> if (error.response.statusCode === 401) {
>   // Do something.
> }
> ```

Thanks, I also checked this and I found a new problem in it

If I enter the wrong password it will give me 401 error
If I enter the wrong apiKey it will give me 403 error
If I enter the wrong shopName it will give me 404 error

with the same name = 'HTTPError'.

Thanks for the quick reply
