### ISSUE TITLE
HTTPError: Response code 401 (Unauthorized)

### ISSUE THREAD

**Issue by AlfredoDevMx** [MONEI/Shopify-api-node#402]
I made a Shopify integration using the following scopes:
"Read products" and "Read Orders"

I've got an accessToken which I'm using in the Shopify-api-node options :

    const shopify = new Shopify({
        shopName: 'xxxx.myshopify.com',
        accessToken: '"shpat_xxxxxxxx",
        apiVersion: "2020-07"
    });

When I try to make a request I'm getting this error : 

`   await shopify.order
        .list({ limit: 5 })
        .then((orders) => {
            res.json({ orders: orders });
        })
        .catch((err) => console.error(err));`

```
HTTPError: Response code 401 (Unauthorized)
    at onResponse (d:xxxxxxxx\node_modules\shopify-api-node\node_modules\got\dist\source\as-promise\index.js:142:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'HTTPError',
  code: undefined,
  timings: {
    start: 1596637872892,
    socket: 1596637872893,
    lookup: 1596637872895,
    connect: 1596637872938,
    secureConnect: 1596637872987,
    upload: 1596637872987,
    response: 1596637873277,
    end: 1596637873281,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 2,
      tcp: 43,
      tls: 49,
      request: 0,
      firstByte: 290,
      download: 4,
      total: 389
    }
  }
}
```

I already tested the accessToken with a postman request and it is working.

Could somebody help me?
Thanks

**Comment by j0rd** [comment]
Same issue. I cloned my app on a new site via a new private API key.

Code the same and continues to work on my other sites.

The only thing I can think of is that when I created this new private app, I originally created it as "Webhook API version: 2020-10 (unstable)". When I got this error I changed it to 2020-07, but it still doesn't work.

**Comment by f1rstsurf** [comment]
Same issue here, can you help please ? here is the result of npm ls agent-base : 
```
(node:7067) [DEP0139] DeprecationWarning: Calling process.umask() with no arguments is prone to race conditions and is a potential security vulnerability.
dropshapp@1.0.0 /home/adrien/Documents/dropshapp
└─┬ aliexpress-product-scraper@1.0.5
  └─┬ puppeteer@1.20.0
    └─┬ https-proxy-agent@2.2.4
      └── agent-base@4.3.0
```

**Comment by lpinca** [comment]
@f1rstsurf see https://github.com/MONEI/Shopify-api-node/issues/385#issuecomment-678330920

**Comment by f1rstsurf** [comment]
@lpinca thank you guy !

**Comment by szmarczak** [comment]
There's a new Got update https://github.com/sindresorhus/got/releases/tag/v11.7.0

**Comment by lpinca** [comment]
I'm closing as the issue is caused by `agent-base@<=4`. There is not much we can do.
