### ISSUE TITLE
Please support decoding & verifying signature of JWT sessionToken

### ISSUE THREAD

**Issue by fancydev18** [MONEI/Shopify-api-node#408]
There's a new `sessionToken` authentication (not to be confused with existing `accessToken`)
https://shopify.dev/tools/app-bridge/authentication

Would you please add support for decoding & verifying signature of JWT `sessionToken`?
Obtain session details manually (decoding)
Verify the signature

**Comment by lpinca** [comment]
That is for App bridge. This library is for the API. See https://shopify.dev/concepts/about-apis/authentication.

**Comment by fancydev18** [comment]
sessionToken (given by App bridge) must be decoded & verified on server.

**Comment by lpinca** [comment]
It's out of the scope of the module. This only an API client.
