### ISSUE TITLE
FulfillmentService Create doesn't work with 422 response

### ISSUE THREAD

**Issue by cedriclajato** [MONEI/Shopify-api-node#416]
Even though I have the correct params fulfillmentService.create doesn't work with response of HTTPError: Response code 422 (Unprocessable Entity) others are okay except .create

**Comment by RoudaniMED** [comment]
check your callback_url in your request if it is correct maybe that's the problem

**Comment by cedriclajato** [comment]
I actually tried using postman and it's working fine but not when using .create node here's my data

const fulfillment_params = {
  "fulfillment_service": {
    "name": "Test Twozzz",
    "callback_url": "http://google.com",
    "inventory_management": true,
    "tracking_support": true,
    "requires_shipping_method": true,
    "format": "json"
  }
};

**Comment by lpinca** [comment]
```js
console.log(error.response.body);
```

should give you more details.

**Comment by cedriclajato** [comment]
Yes, the error

{
  errors: {
    response_format: [
      'response format must be xml or json',
      "can't convert nil to String"
    ],
    name: [ 'may not be empty' ]
  }
}

But the name parameter is clearly not empty at all.

**Comment by cedriclajato** [comment]
No worries, I figured it out. Look like this one doesn't need at all

**Comment by cedriclajato** [comment]
fulfillment_service
