### ISSUE TITLE
Improve docs Resources section to mention GET payload gotcha explicitly 

### ISSUE THREAD

**Issue by m-adilshaikh** [MONEI/Shopify-api-node#422]
The `parameters` is in lean format for creating and updating resources but not for getting. Had to dig in buildUrl function to find out myself.

`When using shopify-api-node you don't have to specify the full object but only the nested one as the module automatically wraps the provided data. Using the above example this translates to:`

The `Resources` section could be split into creating/updating and getting sub-sections or have an explicit note about `.get` query exception.

Example:
``` javascript
shopify.asset.get(themeId, {
    asset: {
      key: "layout/theme.liquid"
    }
})
```

**Comment by lpinca** [comment]
I think this is made obvious by examples like:

```js
shopify.order
  .list({ limit: 5 })
  .then((orders) => console.log(orders))
  .catch((err) => console.error(err));
```

**Comment by m-adilshaikh** [comment]
@lpinca It wasn't obvious to me but I am The Smartest.

**Comment by lpinca** [comment]
Feel free to send a PR to improve the docs.
