### ISSUE TITLE
fulfillment_service: [ 'is not defined for your shop' ]

### ISSUE THREAD

**Issue by paragonitDFW** [MONEI/Shopify-api-node#423]
When product create

    "variants": [
      {
        "fulfillment_service": "Stitchy",
        "sku": 123,
        "price": 0,
        "presentment_prices": [
          {
            "price": {
              "currency_code": "USD",
              "amount": 0
            },
            "compare_at_price": null
          },
        ]

      }

Even though I have Stitchy on my shop 

having this error

{
  errors: {
    fulfillment_service: [ 'is not defined for your shop' ],
    base: [ 'Missing image src' ]
  }
}

**Comment by lpinca** [comment]
This is not an issue in the library. You can probably find more info on the error on Google or the Shopify Community forum.
