### ISSUE TITLE
Error messages are undefined

### ISSUE THREAD

**Issue by philliprognerud** [MONEI/Shopify-api-node#424]
So I've been using this library for a little bit now, but I've noticed errors are undefined. It shows the status code which is great, but it never has an error message associated with it. So it makes it difficult to debug. Is this the expected behavior or is something setup wrong on my end? The API works and I have been using it.

Here's an example of an error for invalid domain for email while registering a new user, it doesn't tell me anything actually other than status code 422.
```
HTTPError: Response code 422 (Unprocessable Entity)
    at Request.<anonymous> (/var/task/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1603474753970,
    socket: 1603474753988,
    lookup: 1603474754027,
    connect: 1603474754048,
    secureConnect: 1603474754070,
    upload: 1603474754071,
    response: 1603474754607,
    end: 1603474754647,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 18,
      dns: 39,
      tcp: 21,
      tls: 22,
      request: 1,
      firstByte: 536,
      download: 40,
      total: 677
    }
  }
}
```

This is the error message I was expecting (below). I used a default Shopify theme to get this error message, and I'm assuming the Shopify API should reproduce the same error message, but I'm not getting that.
![image](https://user-images.githubusercontent.com/17166224/97040401-b6825c00-1522-11eb-8db9-2e115eae60e7.png)

**Comment by lpinca** [comment]
Use `error.response.body`.

**Comment by philliprognerud** [comment]
@lpinca got the following message once console logging `error.response.body`
```
Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "ReferenceError: error is not defined",
    "reason": {
        "errorType": "ReferenceError",
        "errorMessage": "error is not defined",
        "stack": [
            "ReferenceError: error is not defined",
            "    at /var/task/app.js:82:19",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
            "    at async Promise.all (index 0)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: ReferenceError: error is not defined",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:315:20)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
```

**Comment by lpinca** [comment]
Your error is called `err` so you should log `err.response.body` not `error.response.body`.

**Comment by philliprognerud** [comment]
Thank you.. that was the problem! Closing this. 👍

**Comment by keslert** [comment]
Experienced this same problem. Would be nice to have this documented.
