### ISSUE TITLE
IInventoryItem interface is missing properties.

### ISSUE THREAD

**Issue by MBogdan18** [MONEI/Shopify-api-node#425]
According to both the Shopify API documentation and the screenshot below, when I retrieve an inventory item I should be prompted with the cost field. However, I can not access it because the property doesn't exist on the interface itself and TypeScript returns an error as a result.

GET /admin/api/2020-10/inventory_items/808950810.json
docs: https://shopify.dev/docs/admin-api/rest/reference/inventory/inventoryitem#show-2020-10

Mentioning that I do have the latest version installed (3.5.1 as of the date this was written).

![Screenshot_1](https://user-images.githubusercontent.com/43849364/97166739-660f3680-178e-11eb-89b7-96f0e7ced51c.png)

![Screenshot_2](https://user-images.githubusercontent.com/43849364/97166794-7fb07e00-178e-11eb-9b30-b6546558b658.png)

**Comment by lpinca** [comment]
Feel free to open a PR to fix the type definitions. It looks like `country_harmonized_system_codes` and `province_code_of_origin ` are also missing and `country_code_of_origin`, and `harmonized_system_code` can be `null`.
