### ISSUE TITLE
Shopify.smartCollection.products not working for me

### ISSUE THREAD

**Issue by samjross** [MONEI/Shopify-api-node#431]
Hi. I'm transitioning to this library after a long time of using `shopify-node-api` and I'm having some teething problems.

When I run this code, `const collection = await Shopify.smartCollection.get(id);` it works just fine, no problem, I get the object that represents that collection back from the api.

But when I do `const products = await Shopify.smartCollection.products(id, {limit:10});` it alwas gives me a 404 error:

Response code 404 (Not Found)
https://x.myshopify.com/admin/smart_collections/56384815175/products.json?limit=10

I feel like I must be making a very simple mistake. I'm trying to use this api to mainly get the order that items should appear in this collection. Help would be appreciated, thank you.

**Comment by lpinca** [comment]
The `/smart_collections/{smart_collection_id}/products.json` endpoint is no longer [documented](https://shopify.dev/docs/admin-api/rest/reference/products/smartcollection). I guess it has been removed, but according to https://stackoverflow.com/questions/24228734/how-to-retrieve-all-products-from-a-smart-collection-through-shopify-api you can use `await Shopify.collection.products(smartCollectionId, { limit: 10 })`.

**Comment by lpinca** [comment]
Closing as answered. Discussion can continue if needed.

**Comment by samjross** [comment]
using `await Shopify.collection.products(smartCollectionId, { limit: 10 })` gives me the same problem: 404 at this url: `https://x.myshopify.com/admin/collections/56384815175/products.json?limit=10`
