### ISSUE TITLE
Shopify-api-node not working with puppeteer

### ISSUE THREAD

**Issue by f1rstsurf** [MONEI/Shopify-api-node#433]
Hi, 

i just noticed that if puppeteer module is called before a query, then the query never ends, here is my code in case you would like to reproduce : 

this works : 

```
const Shopify = require('shopify-api-node');

const shopify = new Shopify({
    shopName: 'yourshopname',
    apiKey: 'yourapikey',
    password: 'yourapppass'
  });

app.post('/test', (req, res) => {
  shopify.product.list()
  .then((prod) => console.log(prod))
  .catch((err) => console.error(err));
});
```

but this not : 
```
const Shopify = require('shopify-api-node');
const puppeteer = require('puppeteer');

const shopify = new Shopify({
    shopName: 'yourshopname',
    apiKey: 'yourapikey',
    password: 'yourapppass'
  });

app.post('/test', (req, res) => {
  shopify.product.list()
  .then((prod) => console.log(prod))
  .catch((err) => console.error(err));
});
```

I can't figure it out, any help would be appreciated.

**Comment by lpinca** [comment]
Check if `agent-base@<=4` is in the dependencies tree. You can do that by running `npm ls agent-base`. `agent-base@<=4` patches `https.request()` in way that prevents `got`, the HTTP client library used by `shopify-api-node`, from working properly.

**Comment by f1rstsurf** [comment]
Hi, 

thanks for the very fast reply, I just updated agent-base to 6.0.2 but i also had to downgrade shopify-api-node to 3.3.1 to get it working, otherwise I was getting "undefined".

Definitely thank you for your help !
