### ISSUE TITLE
UI and API response for order numbers are offset.

### ISSUE THREAD

**Issue by MBogdan18** [MONEI/Shopify-api-node#437]
Hello!

I am currently working on an app that focuses mainly on fetching orders through the API Orders endpoint. Upon doing so and checking the data against what the UI shows me for the same store, I have noticed that the UI and the API response is giving me two different order numbers for the same order. For example, the order in the UI would give me 54435 while the API response would give me 53435 (offset by 1000). This is troublesome as we don't know for sure if this can be reproduced on other stores, if it happens on all stores or if it's an exclusive bug for the store I'm testing it on. The order number is especially important to us as we fetch orders from a different API than Shopify based on it and we can't exactly have different configurations for different stores when and if this hits the public app store.

I have attached below one such example of the offset.

![MBogdan18_0-1605859346560](https://user-images.githubusercontent.com/43849364/100449849-43d64480-30bd-11eb-9a79-f166c8b95b1f.png)
![MBogdan18_1-1605859428172](https://user-images.githubusercontent.com/43849364/100449850-446edb00-30bd-11eb-81be-012b9bc8f34c.png)

**Comment by lpinca** [comment]
I don't know but this is not an issue in the library. Try to ask on Shopify community forum.

**Comment by MBogdan18** [comment]
Figured as much. Issue was that I posted the same topic on the community forum a week ago and still no answer and I had hoped I'd find some answers here. Thanks nonetheless!
