### ISSUE TITLE
order.list() is empty

### ISSUE THREAD

**Issue by geongeorge** [MONEI/Shopify-api-node#438]
Orders list is empty although the store has more than 100 recent orders

UPDATE: It's only for some stores. Is there something I might be missing here?

**Comment by geongeorge** [comment]
# Solution

Passing `{ status: 'any' }` as parameter seems to fix this

```js
shop.order.list({ status: 'any' })
```

**Comment by geongeorge** [comment]
@lpinca Do you think we should mention this in the docs?

**Comment by lpinca** [comment]
It's like any other allowed parameter listed in the official documentation so I would say no.
