### ISSUE TITLE
Cursor based pagination does not work and page filter will be removed April 2021

### ISSUE THREAD

**Issue by The4star** [MONEI/Shopify-api-node#440]
Hi, 

I have back end services for a client who has over 1400 products on their shopify store so need to be able to retrieve them all using  the shopify.product.list method. Currently i'm just passing the page number as a param but this is being deprecated and removed in April 2021 according to the email Shopify has sent me.

 I've tried the method for pagination in the docs (below) but it does not work at all and their is no typing for it either. Will support for cursor based pagination be added before then? I see there is a merged pull request for it here: https://github.com/MONEI/Shopify-api-node/pull/313 but no references as to how to use it anywhere. 

```
(async () => {
  let params = { limit: 10 };
 
  do {
    const products = await shopify.product.list(params);
 
    console.log(products);
 
    params = products.nextPageParameters;
  } while (params !== undefined);
})().catch(console.error);
```

**Comment by lpinca** [comment]
Cursor based pagination works and is actively used by many users. Try to update your `shopify-api-node` version if you are not already using the latest version.

**Comment by The4star** [comment]
Thanks for the reply Luigi,

my version is "shopify-api-node": "^3.5.3", but products.nextPageParameters
is always undefined and there is no type definition for it.

Clinton Forster

clintonforster@gmail.com

**Comment by lpinca** [comment]
See https://github.com/MONEI/Shopify-api-node/issues/288 for the TypeScript type definitions.

**Comment by The4star** [comment]
i still get undefined even if i add my own definition, not quite sure what i'm doing wrong here, thanks for your help

**Comment by lpinca** [comment]
I don't know. Try to specify an API version.

**Comment by The4star** [comment]
Perfect, thanks mate I owe you a beer.

**Comment by kamranblueeast** [comment]
HI @lpinca,
Actually I have tried shopiy-api-node with both plain JS as well with typscript, with plain JS I can see the next page and unique tokens but with typescript I am unable to get next page and unique tokens.
Any advise?

**Comment by The4star** [comment]
@kamranblueeast i needed to declare my own types. 

```typescript
interface IProductList extends Array<IProduct> {
  nextPageParameters?: IPageParameters,
  previousPageParameters?: IPageParameters,
}

interface IPageParameters {
  limit: string;
  page_info: string;
}
```
