### ISSUE TITLE
How to mock with Jest

### ISSUE THREAD

**Issue by pradosh987** [MONEI/Shopify-api-node#445]
Hi
How do I mock this module when testing with Jest? This package is mocking http calls which is too low level. 

Thanks

**Comment by lpinca** [comment]
I don't know if jest automatic mock works but manual mock works for sure so you can use that.

**Comment by pradosh987** [comment]
Thanks @lpinca. I am not familiar with manual mock testing. Could you please elaborate or may be point me in right direction. Any suggestion is greatly appreciated.

**Comment by pradosh987** [comment]
@lpinca 

I have created "shopify-api-node" with following content. So far its working. Let me know if there's better way.

```
import _ from "lodash";

export default class Shopify {
  constructor(data: any) {
    console.log("fake");
  }

  priceRule = {
    create: () => {
      console.log("creating pricing rule");
      return { id: _.random() };
    },
  };

  discountCode = {
    create: () => {
      console.log("Creating discount");
      return { code: _.random().toString(), id: _.random(10000000000) };
    },
  };
}

```

**Comment by lpinca** [comment]
Yes I think that it is ok. I'm closing this as it is not an issue in the library.
