### ISSUE TITLE
dispute.list returns a 404

### ISSUE THREAD

**Issue by micktaiwan** [MONEI/Shopify-api-node#453]
Hello,

const rv = await shopify.dispute.list();
const rv = await shopify.dispute.list({});
const rv = await shopify.dispute.list({status: 'won'});

all return a 404.

Mickael.

**Comment by lpinca** [comment]
Did you try with another client like `curl` or [Insomnia](https://insomnia.rest/) to see if you get the same result?

**Comment by lpinca** [comment]
Also make sure payments are enabled. Open `https://<yourShopName>.myshopify.com/admin/settings/payments` in a browser.

**Comment by micktaiwan** [comment]
Thanks for your reply.

Payments are enabled.
It works with insomnia (https://key:pwd@<shop>.myshopify.com/admin/api/2021-01/shopify_payments/disputes.json).
It returns a empty body, but it is not a 404.

It returns a 404 with the node library.

**Comment by lpinca** [comment]
Then it's not an issue in `shopify-api-node`.
