### ISSUE TITLE
I cant get the full list of products or orders to save the life of me! Help 2021-01!

### ISSUE THREAD

**Issue by JashanKhela** [MONEI/Shopify-api-node#454]
I am following a different solution that I found on this board but essentially I am trying to just get all my products from Shopify.  Here is my code :(

 `app.get('/', (req, res) => {
  const Shopify = require('shopify-api-node');

  const shopify = new Shopify({
  shopName: CAD_STORE,
  apiKey: SHOPIFY_API_KEY_CAD,
  password: SHOPIFY_API_PASSWORD_CAD
});

let params = { limit: 250 };
function getAllProduct(params) {
    var allProducts = [];
    function getProducts(params) {
        return shopify.product.list(params).then(function (products) {
            allProducts = allProducts.concat(products);
            params = products.nextPageParameters;
            if (params !== undefined) {
              console.log('still running');
                return getProducts(params);
            } else {
              console.log("stopped running");

                return allProducts;
            }
        }).catch(function (e) {
            console.log(e.stack);
        })
    }
    return getProducts(params)
}
getAllProduct(params).then(function (result) {
    console.log(result.length);
}) 
res.send('hello world , please work')

  });`

My console only shows that this runs once and doesn't keep checking for more products via cursor-based pagination. What am I doing wrong? My API version is 2021-01! I have attached my console output as well. I just need to know how to get all products or all orders from my Shopify store and export them to CSV so I can import them into MySQL. Please any help is greatly appreciated.

![Screen Shot 2021-01-29 at 2 54 38 PM](https://user-images.githubusercontent.com/25163420/106335565-ed62bf00-6241-11eb-9bbf-d68d6958c61c.png)

**Comment by mikhailarden** [comment]
At a glance, I can say that it's because your 'allProducts' variable isn't being populated. What you need here is an async function https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by lpinca** [comment]
I think this happens because `products.nextPageParameters` is `undefined` but I don't know why. Are you sure the number of product is > 250? Also try to explicitly specify an API version.

I'm closing this. Discussion can continue if needed.
