### ISSUE TITLE
graphql method does not return throttle rate information

### ISSUE THREAD

**Issue by steveburchfield** [MONEI/Shopify-api-node#456]
The graphql method does not return any throttle rate information https://github.com/MONEI/Shopify-api-node/blob/608ff96051ca5b0b2682e622667fb6fa7231d5a6/index.js#L248. Our application acts as a middleware to Shopify, so it would be helpful to expose the throttle rate information in the responses from our endpoints so that the calling code can make decisions based off of the remaining bucket size.

Are there any plans to include this kind of support?

**Comment by lpinca** [comment]
See https://github.com/MONEI/Shopify-api-node#shopifycalllimits.
