### ISSUE TITLE
How do I get the MyShopify address of a user before they are authenticated?

### ISSUE THREAD

**Issue by Lisen-Kaci** [MONEI/Shopify-api-node#458]
I am building a public app but in the example the config contains the MYSHOP name of the store. How can I get this value for any merchant that is downloading my app from the marketplace?

var Shopify = new shopifyAPI({
shop: 'MYSHOP'
other stuff
});

Thank you for your help!

**Comment by YourWishes** [comment]
Not really related to this API, but Shopify will typically provide that information as part of the request sent to your app from your App Authorize install URL as either a Query String, or as a header such as X-Shopify-Domain or similar. The api here is only concerned with connecting to a shop _after_ it has been authorized.

**Comment by lpinca** [comment]
I'm closing this as answered (by @YourWishes).
