### ISSUE TITLE
Removing discount allocation method "one"

### ISSUE THREAD

**Issue by LuKaa** [MONEI/Shopify-api-node#468]
With the change to **2020-07** the discountAllocation method does not support 'one' anymore but 'each' and 'accros'

The interface does seem to still be specifying the option 'one'.

[https://github.com/MONEI/Shopify-api-node/blob/88d5e04a6446523a358d7f2db8017bd7e20df2e3/index.d.ts#L1360](https://github.com/MONEI/Shopify-api-node/blob/88d5e04a6446523a358d7f2db8017bd7e20df2e3/index.d.ts#L1360)

Also I'am getting the error meassge in my shopify admin panel that I'am still using this option in one of my api calls but I'am not using it. 
_Is there any chance that this is correlated_? 
I just checked and I'am not using any calls inside my app bellow 2020-10.

![image](https://user-images.githubusercontent.com/6472013/111649108-5c04d780-8804-11eb-9b66-1b9f11c9c839.png)

This is the changelog:
[changelog](https://shopify.dev/changelog/removing-discount-allocation-method-one-1)

**Comment by lpinca** [comment]
> Is there any chance that this is correlated?

No, I see no correlation. Type definitions do not change what is sent in the HTTP request body.

**Comment by LuKaa** [comment]
@lpinca That's what I assumed. Thank you.

**Comment by umang135** [comment]
Any solution to solve this?

**Comment by lpinca** [comment]
If you have already migrated just ignore the warning. I'm closing this as the deadline in the issue description expired.
