### ISSUE TITLE
AssignedFulfillmentOrder Endpoint Missing

### ISSUE THREAD

**Issue by jmgunter** [MONEI/Shopify-api-node#473]
It seems that the AssignedFulfillmentOrder endpoint from the Shopify REST API is missing from this library. Am I missing this somewhere?

https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/assignedfulfillmentorder?api%5Bversion%5D=2020-10#index-2021-01

Endpoint:
GET: /admin/api/2020-10/assigned_fulfillment_orders.json?assignment_status=cancellation_requested&location_ids[]=48752903

**Comment by lpinca** [comment]
This is available as `shopify.fulfillmentOrder.list()`. See https://github.com/MONEI/Shopify-api-node/commit/0505308fddec4556efcfc736bef08cdd85fbcfa4.

**Comment by jmgunter** [comment]
Got it, thanks!
