### ISSUE TITLE
Error response undefined

### ISSUE THREAD

**Issue by Haideralee** [MONEI/Shopify-api-node#474]
Hi, I am trying to create a customer and if a customer already existing then I am expecting '`error.response.body`' to have error detail but it's sending an unexpected and inconsistent response.
sometimes it's given me a complete proper error and sometimes gives an incomplete error where the response undefined.

I am attaching an errors screenshot

incomplete error screenshot
![shopify-error-1](https://user-images.githubusercontent.com/4715743/112602623-bff75380-8e35-11eb-92fb-328bc6aa06c0.png)

complete error screenshot
![shopify-error-2](https://user-images.githubusercontent.com/4715743/112602615-be2d9000-8e35-11eb-89fd-fe9014bc2f1f.png)

**Comment by lpinca** [comment]
Not all errors have the `response` property. Sometimes the error occurs before the HTTP response is received.

**Comment by Haideralee** [comment]
I understand not all errors have response property but errors have some legit detail about the error right ?
if you look 1 screenshot there no clue why and what kind of error was it.

and it's the same endpoint I was calling with same credentials but it's send me sometimes proper error detail and sometimes it's just send me wired error object.

**Comment by lpinca** [comment]
If you google `EAI_AGAIN` you'll see that it's a DNS lookup timeout error.

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.
