### ISSUE TITLE
Create Order Trasactions don't work

### ISSUE THREAD

**Issue by MonetizPay** [MONEI/Shopify-api-node#484]
Hi,
First thanks for the library, it has helped me a lot, but I found a problem or I am doing something wrong I have tried to create a new transaction but it always returns error 422 (Unprocessable Entity)

I tried to send 
`let data={
  transaction: {
    currency: 'BRL',
    amount: '24.89',
    kind: 'capture',
    parent_id: 4665713787012
  }
}`

I have also tried 

`let data = JSON.stringify(
{
  transaction: {
    currency: 'BRL',
    amount: '24.89',
    kind: 'capture',
    parent_id: 4665713787012
  }})`

`shopify.transaction
        .create(order, data)
        .catch((err) => console.error(err));`

**Comment by lpinca** [comment]
Use

```js
let data = { currency: 'BRL', amount: '24.89', kind: 'capture', parent_id: 4665713787012 };
```

See https://github.com/MONEI/Shopify-api-node#resources.

**Comment by lpinca** [comment]
I'm closing this as answered.
