### ISSUE TITLE
Getting the GraphQl Cost for the query

### ISSUE THREAD

**Issue by ozzyonfire** [MONEI/Shopify-api-node#489]
Is there any way to get the requested and actual query costs back? 

When running a graphQL query natively we get back an "extensions" object, like so:
```javascript
"extensions": {
    "cost": {
      "requestedQueryCost": 502,
      "actualQueryCost": 502,
      "throttleStatus": {
        "maximumAvailable": 1000,
        "currentlyAvailable": 498,
        "restoreRate": 50
      }
    }
  }
```

I understand that we get the throttle status back from the `shopify.on('callLimits', (limits) => console.log(limits));` but limits only contains restoreRate, current, remaining and max. 

I'd like to be able to create a throttling function that will wait for the required number of seconds. For example, if I know my query is going cost 502, and my available cost is 498, then with a restore rate of 50, I only have to wait for 1 second. However, without knowing what the cost of my query will be, I can't properly throttle my requests. 

Thanks, keep up the great work on the library!

**Comment by lpinca** [comment]
I'm fine with adding that info in the [`limits`](https://github.com/MONEI/Shopify-api-node/blob/d1fd13e65738de833312b77888ebacd1d33c8616/index.js#L198) object that is emitted as an argument of the `'callGraphqlLimits'` event. It should be very easy to do that. Feel free to open a PR.

**Comment by pociej** [comment]
@ozzyonfire i think my https://github.com/MONEI/Shopify-api-node/issues/451 is related, as well as #490.
