### ISSUE TITLE
FulfillmentOrder list of a specific order method is missing

### ISSUE THREAD

**Issue by joaohedy** [MONEI/Shopify-api-node#491]
Cannot find this
```
GET /admin/api/2021-04/orders/{order_id}/fulfillment_orders.json
Retrieves a list of fulfillment orders for a specific order.
```

as explained in documentation here: 
https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillmentorder#index-2021-04

**Comment by lpinca** [comment]
It is available as `shopify.order.fulfillmentOrders(id)`. See https://github.com/MONEI/Shopify-api-node/commit/a14f89bae015820cb59959d5ff8c558d0cae1b50.

**Comment by joaohedy** [comment]
Missed that.
Sorry and Thank you.
