### ISSUE TITLE
Shop metafield deprecated value_type, new field: type

### ISSUE THREAD

**Issue by yongyi520** [MONEI/Shopify-api-node#505]
**Issue**: **When creating new metafield with the new 'type' field,** 
```
shopify.metafield.create({
    namespace: 'exampleNameSpace',
    key: 'exampleKey',
    value: object,
    type: 'json'
  });
```
I get this error:
![Screen Shot 2021-08-21 at 7 58 41 PM](https://user-images.githubusercontent.com/10789851/130322596-23a3cf5f-d16b-43aa-97e8-c191ddec30d1.png)

**Solution: Update metafield type**
Shopify partners has given a notice to update to
1. not use the deprecated field: value_type 
2. use type instead

https://shopify.dev/api/admin/rest/reference/metafield#index-2021-07
![Screen Shot 2021-08-21 at 7 54 56 PM](https://user-images.githubusercontent.com/10789851/130322501-c952ca37-b64c-474a-abcf-566a05e2a700.png)

https://shopify.dev/apps/metafields/definitions/types
![Screen Shot 2021-08-21 at 8 03 32 PM](https://user-images.githubusercontent.com/10789851/130322690-da8ce342-d21a-4995-a756-6fefbec681d0.png)

**Comment by lpinca** [comment]
I will update the TypeScript type definitions but the error you are receiving has nothing to do with it. You already specified `type` so it can't be blank. TypeScript type definitions do not change what is sent and received.

**Comment by lpinca** [comment]
Make sure you are using the `2021-07` API version.
