### ISSUE TITLE
Use a logical approach for resource modules (ie: stop using dynamic imports)

### ISSUE THREAD

**Issue by panoply** [MONEI/Shopify-api-node#506]
Why do this?
https://github.com/MONEI/Shopify-api-node/blob/master/resources/index.js

The implications for loading modules in this manner for exceed the benefits. Bundlers are unable to efficiently treeshake and those mapped dynamic requires wreak absolute havoc when one attempts to re-route them in transpilation. Please, move to ESM or are the very least process the project through a bundler that prevents that dynamic mapping.

**Comment by reecefenwick** [comment]
Facing this issue as well, are there any implications with changing from lazy/dynamic imports?

I understand the rationale, but feel it could be an unnecessary optimisation. I'm working in large server side project with a large dependency tree and this is the only dependency I have that is not compatible for bundling

**Comment by reecefenwick** [comment]
I've raised https://github.com/MONEI/Shopify-api-node/pull/634 to fix this with backwards compatibility
