### ISSUE TITLE
Question regards autoLimit feature

### ISSUE THREAD

**Issue by lukeclifton** [MONEI/Shopify-api-node#510]
Hey. Thanks for a great lib and all of the work here.

Question...if our app supports multiple shops, does the **autoLimit** feature only take into account **each shops limits** per `shopName` and `accessToken`?

**Comment by lukeclifton** [comment]
****

**Comment by lpinca** [comment]
Yes, it takes into account a single `Shopify` instance per shop.

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.
