### ISSUE TITLE
shopName does not accept alias

### ISSUE THREAD

**Issue by AlexXmartlabs** [MONEI/Shopify-api-node#511]
Hey there, 

Does shopName support domains outside myshopify.com? We have a primary domain configured on our store. Like shop.MYDOMAIN.com

The error we are getting is: 

equestError: Hostname/IP does not match certificate's altnames: Host: shop.MYDOMAIN.com.myshopify.com. is not in the cert's altnames: DNS:myshopify.com, DNS:*.myshopify.com

Thanks!

**Comment by lpinca** [comment]
No, see https://github.com/MONEI/Shopify-api-node/issues/432.

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.

**Comment by Hpanday** [comment]
@lpinca does the api still not accept alias names?
My website also has the domain **_shop.XX.com_** and I too get the error 

_RequestError: Hostname/IP does not match certificate's altnames: Host: shop.XX.com.myshopify.com. is not in the cert's altnames: DNS:*.myshopify.com, DNS:myshopify.com_

Is there a workaround?
