### ISSUE TITLE
Can't update product metafield

### ISSUE THREAD

**Issue by tman16** [MONEI/Shopify-api-node#522]
I am having issues updating the product metafield, I am using the following:

`let params = {metafield: {id: 123456789, value: "new value here", type: "single_line_text_field"}}`

`await shopify.metafield.update(123456789, params);`

The response gives the original value and not what it should be updated to.

**Comment by lpinca** [comment]
See https://github.com/MONEI/Shopify-api-node#metafields

**Comment by lpinca** [comment]
`params` should be

```js
{id: 123456789, value: "new value here", type: "single_line_text_field"}`
```

and not

```js
{metafield: {id: 123456789, value: "new value here", type: "single_line_text_field"}}
```

**Comment by lpinca** [comment]
I'm closing this as answered.
