### ISSUE TITLE
unable to find the password in shopify private app

### ISSUE THREAD

**Issue by sahiltuteja09** [MONEI/Shopify-api-node#524]
As we notice that some changes have been done by shopify team. Now the password is not required for admin api. How we can use the new private app with Shopify-api-node REPO. 

Can you please check the new changes and update the Package accordingly ?

**Comment by pgiu** [comment]
I've been using private apps for a while but after migrating to the new app page I can't seem to make it work using the api key and password. 

![image](https://user-images.githubusercontent.com/6964377/152239547-8d2a953f-13ae-4053-9455-8f47fe57368c.png)

Any thoughts?

**Comment by sahiltuteja09** [comment]
@pgiu I am using admin api access token as a password for now.
