### ISSUE TITLE
unable to fetch metafield by its id

### ISSUE THREAD

**Issue by kambojidileep98** [MONEI/Shopify-api-node#526]
shopify.metafield.get(eula_195, {
      id: eula_195, //metafield key
      metafield: {
        owner_resource: 'page',
        owner_id: 8708459742912
 }
 I am trying to fetch that particular metafield from the node js server but I am getting the response as

ERROR:
  error: {
    success: false,
    message: 'Order could not be verified',
    status: 403
  }
}

**Comment by lpinca** [comment]
Use only the ID. For example

```js
const metafield = await shopify.metafield.get(721389482);
```

**Comment by kambojidileep98** [comment]
thanks it worked
