### ISSUE TITLE
Private apps (and Basic auth) are deprecated as of January 2022

### ISSUE THREAD

**Issue by Pwuts** [MONEI/Shopify-api-node#529]
According to the [docs](https://shopify.dev/apps/auth/basic-http), private apps have been deprecated, and new apps can use the access token obtained when creating a custom app in the Shopify admin.

Could the [docs](https://github.com/MONEI/Shopify-api-node#options) of this library be updated accordingly? I'm not sure if it still works for existing apps, but if not the Basic auth can also be removed from the client.

**Comment by lpinca** [comment]
We can remove the documentation for the `apiKey` and `password` options but removing the functionality does not make much sense in my opinion. It is an unnecessary breaking change.

**Comment by Pwuts** [comment]
Well if Shopify has removed support on their side it also wouldn't make sense to keep the (then useless) code. But as I said, I don't know if they have really disabled it or just disabled creating new private apps.

**Comment by lpinca** [comment]
I just tested it. `apiKey` and `password` still works for existing apps.
