### ISSUE TITLE
Implement the new menu endpoint

### ISSUE THREAD

**Issue by torbrandt** [MONEI/Shopify-api-node#535]
It would be nice to have the new menu endpoint implemented
https://shopify.dev/api/admin-graphql/2021-07/objects/NavigationItem#fields

**Comment by lpinca** [comment]
I can't find this in the [REST Admin API reference](https://shopify.dev/api/admin-rest).

**Comment by torbrandt** [comment]
Ah sorry, I wasn't aware, it's not available there :/
