### ISSUE TITLE
Fetch published blogs

### ISSUE THREAD

**Issue by djdonmil** [MONEI/Shopify-api-node#537]
Hi, in my Node project I am fetching articles from shopify app. 
Code:

`await shopify.article.list(blockId, { limit: 2 });
`
Now here I am getting both published/unpublished articles. I only want to fetch published articles. 
Can you suggest me, which params I need to pass to fetch only published articles?

Thanks in advance.

**Comment by lpinca** [comment]
See https://shopify.dev/api/admin-rest/2022-04/resources/article#get-blogs-blog-id-articles

```js
await shopify.article.list(blogId, { limit: 2, published_status: 'published' });
```

**Comment by djdonmil** [comment]
@lpinca thanks a lot... It helped me
