### ISSUE TITLE
HTTPError: Response code 503 (Service Unavailable)

### ISSUE THREAD

**Issue by rounsmith** [MONEI/Shopify-api-node#538]
Hello , 

i am getting randomly HTTPError: Response code 503 (Service Unavailable) which makes my app crash (i haven't used try catch on this error because it was never happening).

It seems to happen when i am getting the list of products

with this similar code 
```
(async () => {
  let params = { limit: 10 };


  do {
    const products = await shopify.product.list(params);

    console.log(products);

    params = products.nextPageParameters;
  } while (params !== undefined);
})().catch(console.error);
```

**Comment by lpinca** [comment]
It means that the Shopify API is down. There is not much do other than handling the error.

**Comment by lpinca** [comment]
I'm closing this as answered.
