### ISSUE TITLE
can I use an auto limit with promises.all?

### ISSUE THREAD

**Issue by guilhermeprokisch** [MONEI/Shopify-api-node#543]
Hello there.

If I store all promises in an array and use with promises.all the autolimit it's should work? I tried but still get some Rate Limit error.

**Comment by lpinca** [comment]
Yes it should. Try to reduce the value of the `autoLimit.bucketSize` option. Also keep in mind that the limit is applied to a single `Shopify` instance. If you have multiple `Shopify` instances for the same shop you have to further tweak the configuration.

**Comment by guilhermeprokisch** [comment]
Thanks
