### ISSUE TITLE
currentQuantity field is missing in IOrderLineItem type

### ISSUE THREAD

**Issue by JSsantana** [MONEI/Shopify-api-node#545]
I found that Order Line Item interface do not have the currentQuantity field.

`interface IOrderLineItem `

LineItem.
currentQuantity
[Int!](https://shopify.dev/api/admin-graphql/2022-07/scalars/Int)
non-null
The line item's quantity, minus the removed quantity.

[https://shopify.dev/api/admin-graphql/2022-07/objects/LineItem](url)

**Comment by lpinca** [comment]
Feel free to open a PR to add it.

**Comment by lpinca** [comment]
On second look, the documentation you linked is for the GraphQL API. I can't see the `currentQuantity` field in the [Order `line_items`](https://shopify.dev/api/admin-rest/2022-07/resources/order#resource-object) of the REST API.

I'm closing this. Discussion can continue if needed.
