### ISSUE TITLE
Cannot read property 'extensions' of undefined

### ISSUE THREAD

**Issue by guilhermeprokisch** [MONEI/Shopify-api-node#547]
When I'm using the `product.update` method with  variant info on the payload I'm getting an error `Cannot read property 'extensions' of undefined`.

**Comment by lpinca** [comment]
Can you please post the full stack trace?

**Comment by lpinca** [comment]
My guess is that the error is thrown here

https://github.com/MONEI/Shopify-api-node/blob/49a52f778529632887e717848fe4214ac2d97cc6/index.js#L383

If so, can also log somehow `body.errors` and the response status code?

**Comment by guilhermeprokisch** [comment]
Thanks for the fast reply! 

It's hard to replicated this error locally. It's happening just with some products of some clients on products. This why I also have difficult to post the trace here cause it will have the client payload. Any idea how we can do it?

**Comment by guilhermeprokisch** [comment]
But I just had some progress, seems indeed related with the auto retry option. I take off and now I got a different error. HTTPError: Response code 422 (Unprocessable Entity)

**Comment by lpinca** [comment]
Ok, thank you for the additional info. The 422 status code should not be retried. I think there is a bug in got. This needs to be investigated.
