### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by nubdevie** [MONEI/Shopify-api-node#549]
Hey guys. I'm getting this error when bundling my code. I can't seem to find out what causes the issue.

Importing the package -> bundling already gives this error.

so with only : import Shopify from "shopify-api-node"; as code it gives the error. 

Everything works fine in VScode though when I run my code, just when its bundled and I try it out on the browser it crashes.. 

I already tried using the ES5 require syntax as in the readme, but this also did not work.

**Comment by lpinca** [comment]
Can you post the stack trace of the error? Anyway, the library can't be used in the browser. See https://github.com/MONEI/Shopify-api-node/issues/409#issuecomment-679107964.

**Comment by nubdevie** [comment]
> Can you post the stack trace of the error? Anyway, the library can't be used in the browser. See [#409 (comment)](https://github.com/MONEI/Shopify-api-node/issues/409#issuecomment-679107964).

Okay that makes complete sense, I did not know it! Thank you!
