### ISSUE TITLE
Need to reposition all variants through API

### ISSUE THREAD

**Issue by rounsmith** [MONEI/Shopify-api-node#557]
Hello ,

I am trying to reposition all product variants based on their grams and what i need to do is to use update the product.

I found this solution in shopify forums https://community.shopify.com/c/shopify-apis-and-sdks/reorder-options-variants/m-p/473817/highlight/true#M30070

but this apply to an PUT(update call).

Is there any change you can elaborate how i can do it through this library?

I can't seem to find the way to send all variants and their values sorted through this library.

I am using this library for 2 production apps and it's going pretty smooth so far.

**Comment by lpinca** [comment]
Use `shopify.product.update(id, params)`, where `params ` is an object like this:

```js
{
  id: 123456789,
  variants: [
    {
      option1: 'S'
    },
    {
      option1: 'M'
    }
  ],
  options: [
    {
      name: 'Size',
      values: ['S', 'M']
    }
  ]
}
```

**Comment by lpinca** [comment]
I'm closing this as answered.
