### ISSUE TITLE
assigned_fulfillment_orders

### ISSUE THREAD

**Issue by HaakonStromsnes** [MONEI/Shopify-api-node#558]
Hi there.

Can see that assigned_fulfillment_orders is not an option. Is it possible to add that?

**Comment by lpinca** [comment]
Use `shopify.fulfillmentOrder.list(params)`. See https://github.com/MONEI/Shopify-api-node/blob/fc41cf4ab92ef1a8cdcc1da71ded7425b562c9e6/resources/fulfillment-order.js#L24-L38

**Comment by lpinca** [comment]
I'm closing this as answered.
