### ISSUE TITLE
QUESTION: Params options?

### ISSUE THREAD

**Issue by andykimchris** [MONEI/Shopify-api-node#562]
Hello, this is mostly a question on the documentation. There is no mention of which params options can be passed for query? Is it only limit that can be used?

```
(async () => {
  let params = { limit: 10 };

  do {
    const products = await shopify.product.list(params);

    console.log(products);

    params = products.nextPageParameters;
  } while (params !== undefined);
})().catch(console.error);
```

**Comment by lpinca** [comment]
> Is it only limit that can be used?

No, you can use all [supported parameters](https://shopify.dev/api/admin-rest/2022-10/resources/order#get-orders?status=any).

**Comment by lpinca** [comment]
I'm closing as answered.

**Comment by andykimchris** [comment]
Thank you @lpinca much appreciated.
