### ISSUE TITLE
Product API doesn't show all medias only images

### ISSUE THREAD

**Issue by offjeff91** [MONEI/Shopify-api-node#569]
Hi, we use shopify-api-node^3.10.0, and we have products with videos and images into their media files but by the product API we only access images (not the videos). So we have some weird side-effects (like, for example, if we delete replace all images by other the remaining video (which, again, is not listed by the API) is set as the product thumbnail.

Can we configure somehow to have access to all media files and not only the images?

Thanks!

**Comment by lpinca** [comment]
Hello @offjeff91, sorry for the late reply.

> Can we configure somehow to have access to all media files and not only the images?

Check the Shopify API documentation. If there is a setting for this it should be in the request parameters. There is nothing specific about this in `shopify-api-node`.

**Comment by offjeff91** [comment]
Thanks, @lpinca
