### ISSUE TITLE
Get product variant with query not working though url is correctly returning results

### ISSUE THREAD

**Issue by lacabra-dev** [MONEI/Shopify-api-node#571]
Hi

I am doing the following:

`shopifyStore.productVariant
          .get(null, { query: 'sku:XXA12TA0804080000' })
          .then((result) => {
            console.log(result);
          })
          .catch((error) => {
            console.error(error);
          });
`
And the result is null. However if i step into the function and observe the url being composed and i try to paste it in the browse and make the request it shows me results. How can this be?

**Comment by lpinca** [comment]
`shopify.productVariant.get()` requires the product variant ID. It can't be `null`. See https://shopify.dev/api/admin-rest/2023-01/resources/product-variant#get-variants-variant-id.

**Comment by lacabra-dev** [comment]
roger that 👍
