### ISSUE TITLE
npm audit issue

### ISSUE THREAD

**Issue by quintmouthaan** [MONEI/Shopify-api-node#579]
I'm getting the following audit issue with v3.12.2 of shopify-api-node:

node_modules/cacheable-request
  got  8.0.0 - 12.4.1
  Depends on vulnerable versions of cacheable-request
  node_modules/got
    shopify-api-node  >=2.10.0
    Depends on vulnerable versions of got

**Comment by lpinca** [comment]
See https://github.com/sindresorhus/got/issues/2220.
