### ISSUE TITLE
productVariant.update causes bad request

### ISSUE THREAD

**Issue by JoshMealing** [MONEI/Shopify-api-node#583]
version 3.12.2

When using the productVariant.update method, I am experiencing an issue where the network request which is sent returns a 400 response. 

```javascript
project-repo/node_modules/got/dist/source/as-promise/index.js:118
request._beforeError(new types_1.HTTPError(response));
                                         ^
HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (project-repo/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1677021238174,
    socket: 1677021238224,
    lookup: 1677021238226,
    connect: 1677021238240,
    secureConnect: 1677021238266,
    upload: 1677021238267,
    response: 1677021238572,
    end: 1677021238573,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 50,
      dns: 2,
      tcp: 14,
      tls: 26,
      request: 1,
      firstByte: 305,
      download: 1,
      total: 399
    }
  }
}
```

The code which is responsible for the error is as follows:
```javascript
  shopify.productVariant.update(44458699161887, {
    inventory_quantity: 100,
    price: '99.98'
  });
```

I can verify the issue is not caused by passing in an incorrect variant Id as using the **productVariant.get(44458699161887)** method returns the variant data as expected.

If you need any additional information please let me know.

Thanks.

**Comment by RobWiddick** [comment]
Try logging the response body to see what Shopify is complaining about. Usually it has something to do with the posted data.

I ended up needing to switch everything to GraphQL due to the weird inconsistencies with the REST API -- very similar issues as yours.

**Comment by Process-Admin** [comment]
Forgot about this post. 

I'm pretty sure the error was being caused by trying to change the inventory_quantity using the productVariant resource. I needed to use the inventoryLevel resource.

**Comment by JoshMealing** [comment]
Forgot about this post.

I'm pretty sure the error was being caused by trying to change the inventory_quantity using the productVariant resource. I needed to use the inventoryLevel resource.

**Comment by JoshMealing** [comment]
Forgot about this post.

I'm pretty sure the error was being caused by trying to change the inventory_quantity using the productVariant resource. I needed to use the inventoryLevel resource.
