### ISSUE TITLE
[Improvement]: implementation of delay function without setTimeout

### ISSUE THREAD

**Issue by jeevan-jp** [MONEI/Shopify-api-node#585]
Since setTimeout doesn't guarantee the delay of specified ms, the implementation of delay function in index.js can be improved with the help of while loop.
```js
function delay(ms) {
  return new Promise((resolve) => {
    const now = new Date().getTime();
    while (new Date().getTime() < now + ms) {
      /* Do nothing */
    }
    resolve(null); 
  });
}
```

Reference Reading: https://www.gimtec.io/articles/settimeout-does-not-guarantee-time-to-execution/

**Comment by lpinca** [comment]
I'm closing this as per https://github.com/MONEI/Shopify-api-node/pull/586#issuecomment-1458841811.
