### ISSUE TITLE
Question: How to update shopify-node-api

### ISSUE THREAD

**Issue by kristiandm** [MONEI/Shopify-api-node#587]
Good day,
We are currently using shopify-node-api in our app and I wanted to know how to update it's version and/or how to update it in general to abide by the breaking changes shopify made regarding fulfillmentsWe are currently using shopify-node-api in our app and I wanted to know how to update it's version and/or how to update it in general to abide by the breaking changes shopify made regarding fulfillments.

I am still unclear on what to do whether I have to update both the version and the usage of the functions, or do I just need to update the function usage in our app? 

Responses will be greatly appreciated thanks!

**Comment by lpinca** [comment]
If the version you are using supports the new methods/endpoint, then there is no need to update, otherwise yes you need to update.

**Comment by lpinca** [comment]
I'm closing this as answered.
