### ISSUE TITLE
Feature Request: autoLimit + maxRetries

### ISSUE THREAD

**Issue by ikudosi** [MONEI/Shopify-api-node#590]
Hello,

Is it possible to have both options working? It would be great to have both options working instead of having to build logic everywhere on dev side to handle API nuances like end point temporarily unreachable. For now I am just enclosing all processes in a queue job that retries on failure (on my case I sometimes get failures from end point being momentarily unreachable). However, it would be easier if this package does both rate limit and retries given on an amount so that I don't have to start over big processes like updating 10K+ products.

**Comment by lpinca** [comment]
No, because the options use two completely different strategies. The goal of `autoLimit` is to never get a 429 error and to never retry. The goal of `maxRetries` is to retry a number of times after getting a 429 error.

**Comment by ikudosi** [comment]
That I understand and the auto limit works wonders, though if it's 5xx status codes, would it make sense to allow certain number of retries to account for intermittent outages? I believe it would simplify alot of development challenges when doing scheduled bulk operations.
