### ISSUE TITLE
Metafields.update() not updating

### ISSUE THREAD

**Issue by ikudosi** [MONEI/Shopify-api-node#594]
API version: 2023-01

I'm trying to do a `PUT /admin/api/2023-01/variants/49148385/metafields/323119633.json` (taken from API docs), is this currently supported in this package?

I see a `metafields.update()` , though the first argument is `id` and don't know how it knows whether it's variants or blog?

**Comment by ikudosi** [comment]
Just to update:

I tried the `metafield.update` and request went through but did not do any update:

![image](https://user-images.githubusercontent.com/5790073/228929708-a60ce2be-4795-4cf3-b053-d415e1cc5395.png)

Doing it manually with Postman with same payload:

![image](https://user-images.githubusercontent.com/5790073/228930044-302fe550-9118-46b3-8953-b864d0b8a51b.png)

**Comment by utkarsh-24** [comment]
Hey,
I have updated this code please visit this  https://github.com/utkarsh-24/Shopify-api-node/tree/update/metafield
I have also created the pull request and waiting for it to get merged  https://github.com/MONEI/Shopify-api-node/pull/599
Let me know if there is any issues.
Thanks.

**Comment by lpinca** [comment]
@ikudosi the `params` object should be

```js
{ id: 1899923639543, value: 'false', type: 'string' }
```

```js
await service.metafield.update(1899923639543, { id: 1899923639543, value: 'false', type: 'string' });
```

**Comment by ikudosi** [comment]
@lpinca Oy. Yea that did it. Didn't realize it was doing some other transformation as the root key for the params is metafield. Also surprised no error was thrown or something xD. Ty ty!
