### ISSUE TITLE
shopify.productImage.create giving unprocessable entity (res code 422).

### ISSUE THREAD

**Issue by raghav17083** [MONEI/Shopify-api-node#600]
When trying to create image using `shopify.productImage.create(id , {src : validImageURL})`, where id is the product_id for which the image is to be added,  I get `Response code 422 (Unprocessable Entity)`

What is the correct way to send the parameters to create the image by this method?

**Comment by lpinca** [comment]
Reading `error.response.body`, where `error` is the error with which the promise is rejected, might give you more details.

**Comment by lpinca** [comment]
I'm closing this as answered.
