### ISSUE TITLE
Getting "403 Forbidden myshop.myshopify.Com" When Creating A Webhook With The Topic "Orders/Create"

### ISSUE THREAD

**Issue by pcldev** [MONEI/Shopify-api-node#601]
I'm creating a mini-app to track revenue for merchants. In the progress of building my app. I got an issue about getting "403 Forbidden xxx.myshopify.com" when I create a webhook with the topic "orders/create".
Screenshot:
![image](https://user-images.githubusercontent.com/76110296/233793033-ce92985f-e945-4c7d-a99e-b693938ecda2.png)
More information surrounding ShopifyAuth:

Scopes: read_orders
Shopify API Versions: 2022-10
The accessToken and session are still valid (because I still login the app normally)

**Comment by lpinca** [comment]
I'm closing this as it does not seem an issue in the library. The server returns 403 so there is something wrong with permissions.
