### ISSUE TITLE
Cannot get products metafields

### ISSUE THREAD

**Issue by aurelien-robineau** [MONEI/Shopify-api-node#606]
Hi! I need to retrieve metafields for a product, but it returns the shop metafields.
My code:
```
const productMetafields = await shopify.metafield.list({
    owner_resource: 'product',
    owner_id: lineItem.product_id,
    namespace: 'global',
    limit: 250
});
```

All the returned metafields have the `owner_resource` set to `shop` and are indeed shop metafields.

Package version: `3.12.5`.

Any clue on why this is happening ?

Thank you!

**Comment by lpinca** [comment]
See https://github.com/MONEI/Shopify-api-node#metafields. You are missing the `metafield` key in your option object.

**Comment by lpinca** [comment]
I'm closing this as answered.
