### ISSUE TITLE
Unable to add a product with a metafield list

### ISSUE THREAD

**Issue by alexislepresle** [MONEI/Shopify-api-node#608]
Hi! I can create the product with simple metafields, but as soon as I add a metafield list, it doesn't work. return HTTPError: Response code 400 (Bad Request).

My code : 
```
const features = ['test', 'test'];
...
metafields: [
        {
          key: 'features',
          value: features,
          value_type: 'single_line_text_field',
          namespace: 'custom'
        },
        ...
 ]
```
        
Package version: `^3.12.3`

Thank you!

**Comment by lpinca** [comment]
> as I add a metafield list, it doesn't work.

AFAIK this is not supported by the Shopify REST Admin API. You have to create one at time.

**Comment by alexislepresle** [comment]
Oh right, thanks for your reply, I hadn't seen that :)
