### ISSUE TITLE
Get list productions do not show next page

### ISSUE THREAD

**Issue by newit-longdh** [MONEI/Shopify-api-node#617]
I want to use pagination for get list products, using limit parameter 
but in the products response it doesn't show any information for pagination page. 
Can someone help me?

Code:
![image](https://github.com/MONEI/Shopify-api-node/assets/60906943/40c101f2-d122-4c0d-9cef-001e81153feb)

Response
![image](https://github.com/MONEI/Shopify-api-node/assets/60906943/0c2e3ba8-09d0-449a-8c8e-cd2f377b69b3)

**Comment by lpinca** [comment]
See https://github.com/MONEI/Shopify-api-node#pagination. The `nextPageParameters` and `previousPageParameters` are not enumerable which is probably the reason why you don't see them.

**Comment by newit-longdh** [comment]
> See https://github.com/MONEI/Shopify-api-node#pagination. The `nextPageParameters` and `previousPageParameters` properties are not enumerable which is probably the reason why you don't see them.

Yes, i am using document you shared, but you can see my response image above, the response have not return `nextPageParameters` or `previousPageParameters parameter`

**Comment by newit-longdh** [comment]
> See https://github.com/MONEI/Shopify-api-node#pagination. The `nextPageParameters` and `previousPageParameters` properties are not enumerable which is probably the reason why you don't see them.

So , What do I have to do to be able to display them? 
Actually I have 2 products and I want to paginate with 1 product

**Comment by newit-longdh** [comment]
> See https://github.com/MONEI/Shopify-api-node#pagination. The `nextPageParameters` and `previousPageParameters` properties are not enumerable which is probably the reason why you don't see them.

Yes, i can't see it in response but i can console log the `nextPageParameters`. thank you
