### ISSUE TITLE
Get Shopify shop name from object with correct type

### ISSUE THREAD

**Issue by danielvoelk** [MONEI/Shopify-api-node#649]
When I try to get the shop name, I get the error: 

shopify.baseUrl.hostname

Property 'baseUrl' does not exist on type 'Shopify'.

I checked the type definition and it's not there. Why?

What is the correct approach to get the shop name from the shopify instance?

  `const shopify: Shopify = new Shopify({
    shopName: '',
    accessToken: '',
    autoLimit: true,
    apiVersion: process.env.SHOPIFY_API_VERSION,
  });

// get shop name
shopify...`

**Comment by lpinca** [comment]
> What is the correct approach to get the shop name from the shopify instance?

```js
const shop = await shopify.shop.get();
```

**Comment by danielvoelk** [comment]
Great, that worked. thank you
