### ISSUE TITLE
Metaobject support

### ISSUE THREAD

**Issue by danieltroger** [MONEI/Shopify-api-node#652]
Does this library support creating and modifying [metaobjects](https://help.shopify.com/en/manual/custom-data/metaobjects)? Doesn't seem like it, would love to see that as a feature!

**Comment by mickeyambrosius** [comment]
It does not and I don't think it ever will. The object specific methods are all targeted against REST but metaobjects exists only for the graphql API. So you need to use graphql queries and then use .graphql method https://www.npmjs.com/package/shopify-api-node#graphql

**Comment by lpinca** [comment]
I'm closing this as answered.
