### ISSUE TITLE
Discount webhook topics and types are missing

### ISSUE THREAD

**Issue by sleepdotexe** [MONEI/Shopify-api-node#658]
Hi there,

I noticed that some of the available webhook topics do not have type definitions for either the topic or payload resource. Particularly important ones include:
- `discounts/create`
- `discounts/delete`
- `discounts/redeemcode_added`
- `discounts/redeemcode_removed`
- `discounts/update`

The reference for these can be found in the [Shopify docs here](https://shopify.dev/docs/api/webhooks?reference=rest#list-of-topics-discounts/create). I believe this relates to the topic type definition [starting on this line](https://github.com/MONEI/Shopify-api-node/blob/159c2e7664b858ced9ee68bad2b03781b9dda377/types/index.d.ts#L3194) and payload type map [starting on this line](https://github.com/MONEI/Shopify-api-node/blob/159c2e7664b858ced9ee68bad2b03781b9dda377/types/index.d.ts#L3362).

Could we please have types added for these?

Thank you!

**Comment by lpinca** [comment]
Feel free to open a PR.
