### ISSUE TITLE
Abandoned checkouts

### ISSUE THREAD

**Issue by alihamza1214** [MONEI/Shopify-api-node#667]
How to retrieve Abandoned checkouts using this package? I could not find any resource for that in the api documentation

**Comment by lpinca** [comment]
See https://shopify.dev/docs/api/admin-rest/2024-10/resources/abandoned-checkouts#get-checkouts?limit=1

```js
const checkouts = await shopify.checkout.list();
```

**Comment by lpinca** [comment]
I'm closing this as answered.
